### ISSUE TITLE
make maven artifact as osgi bundle

### ISSUE THREAD

**Issue by hlavki** [stleary/JSON-java#189]
Would be fine to have json jar with OSGi compatible manifest

**Comment by johnjaylward** [comment]
I don't use OSGi myself, can you reference any docs we could use to see what's missing? Or, can you offer a pull request?

**Comment by stleary** [comment]
No objection here, providing that existing users are not impacted.
@hlavki Can you please describe what benefits that an OSGi bundle would provide to the JSON-Java deliverable?

**Comment by hlavki** [comment]
Benefit is prosaic. You can use it as bundle in OSGi container. Of course you can use [wrap protocol](https://ops4j1.jira.com/wiki/display/paxurl/Wrap+Protocol) to wrap non-osgi jar, but that's not clean solution.

**Comment by johnjaylward** [comment]
So is this a "release only" change in the way the JAR is packaged? if so, I believe @BGehrels would be able to update the release pom to include the necessary options.

**Comment by johnjaylward** [comment]
I found this for
* gradle: https://docs.gradle.org/current/userguide/osgi_plugin.html
*maven: http://wso2.com/library/tutorials/develop-osgi-bundles-using-maven-bundle-plugin/

but I'm unsure which headers would be needed at a minimum. Do we actually need an "Activator" for the bundle when there is nothing to activate?

**Comment by hlavki** [comment]
@johnjaylward, of course. If you use maven, then this lines should help:

first, change packaging to bundle
  ```xml
  <packaging>bundle</packaging>
  ```
second, add plugin to `build/plugins` element
  ```xml
  <plugin>
      <groupId>org.apache.felix</groupId>
      <artifactId>maven-bundle-plugin</artifactId>
      <version>3.0.1</version>
      <extensions>true</extensions>
      <configuration>
          <instructions>
              <Export-Package>
                  org.json
              </Export-Package>
              <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
          </instructions>
      </configuration>
  </plugin>
```

**Comment by stleary** [comment]
Will this change be entirely transparent to users who have no OSGi framework and just want to use the JSON-Java jar as a jar file?

**Comment by hlavki** [comment]
@stleary yes. The only difference will be enriched META-INF/MANIFEST.MF
There is no need to implement Activator or other OSGi features.

**Comment by stleary** [comment]
@hlavki thanks, you caught my question before I deleted it. @BGehrels, Do you have any thoughts about including this change the next time JSON-Java is released?

**Comment by stleary** [comment]
Still no objections to an OSGi bundle. Please propose a pull request if you want to pursue this.

**Comment by BGehrels** [comment]
No objections from my side, never worked with OSGI, so i do not know, if i'm able to test it, but adding the enriched Manifest file should not be that dificult.

**Comment by stleary** [comment]
Thanks @BGehrels. I think I closed this issue prematurely. Since no files are changed in the repository, there is no change to propose for a pull request. @hlavki, is your proposal to change the packaging line and add the bundle plugin section to the POM file, exactly as given in your earlier post?

**Comment by hlavki** [comment]
@stleary yes, that's my proposal. I can also do some tests before release if @BGehrels provides some snapshot binary.

**Comment by hlavki** [comment]
Btw why is build descriptor (pom.xml) out of sources on github?

**Comment by stleary** [comment]
The project does not have any external or build tool dependencies.The Maven repository is used for making a jar file available, and for those who want build tool support.

**Comment by BGehrels** [comment]
@hlavki The pom.xml is maintained here: https://github.com/BGehrels/JSON-java

If you want to contribute the changes - you are welcome!

**Comment by stleary** [comment]
@hlavki thanks for the suggestion. I think OSGi bundle is now implemented in http://search.maven.org/#artifactdetails%7Corg.json%7Cjson%7C20160212%7Cbundle
Please try it out, and open a new issue if problems are found
