### ISSUE TITLE
dead link in readme

### ISSUE THREAD

**Issue by raleighr3** [stleary/JSON-java#191]
The link to http://www.json.org/java/ in the README is now dead, along with all the associated JavaDocs and other related content that used to be hosted there.
Would be nice if that content were made available again.

**Comment by stleary** [comment]
@raleighr3  thanks for catching this. The link is archived here if anyone wants to review it: https://web.archive.org/web/20160117035820/http://www.json.org/java/ 
Looks like a front end for some JavaDoc pages. It may be best to host it on GitHub going forward. 
If anyone has other suggestions, please post them here.

**Comment by stleary** [comment]
Removed the website link until a new home for the JavaDoc is set up.
