### ISSUE TITLE
Maven or Gradle project?

### ISSUE THREAD

**Issue by nhajratw** [stleary/JSON-java#192]
Any interest in having this be a proper maven or gradle project? I'd be happy to contribute a pull request for either. Let me know, and i'll get working :-)

**Comment by erosb** [comment]
Recently I found this repo: https://github.com/eskatos/org.json-java
I think this is where the maven arifacts are built from and are deployed to maven central. It includes https://github.com/stleary/JSON-java as a git submodule. But I'm not sure.

Anyway I'd also like to see this repo as a maven project, so +1

**Comment by nhajratw** [comment]
interesting -- this is kind of a strange setup. Seems like it should all be in a single repo.

**Comment by johnjaylward** [comment]
no, that one is different.

The main reason that this is not a gradle or a maven project is that when it first started there were no test cases, and still to this day, there are no external dependencies. This makes building the project very straightforward and easy; e.g. ```javac *.java```

Historically and PR that have been given to mavenize or gradleize the project have been denied due to the original maintainers lack of interest in it and the easy of use in building it. You can search the old PR and issues.

However, now that we have a decent test bench, I think it makes more sense to combine the 2 projects into a single one and possible use Maven or Gradle to manage the tests. It would make contributing easier since we wouldn't need 2 pull requests, one for the bug/feature and the other for tests.

If you do create a PR for this, I'd recommend including the test bench code and updating the README to reflect the new tests location. The test bench currently had some gradle build info in it that may be a good place to start.

**Comment by nhajratw** [comment]
Thanks @johnjaylward -- I am certainly happy to pull all of this together. I expect it won't take more than a couple hours. I'll give it a shot and submit a pull request. If it ultimately is denied, it will have been an interesting exercise anyway.

**Comment by stleary** [comment]
@nhajratw, appreciate the effort of putting together the pull request. Agree with @johnjaylward that it is clumsy to have the unit tests in a separate project. However, for now I think there is still value in a simple project that only requires the tools provided by the JDK. Will leave this issue open for a few more days in case anyone wants to voice an opinion.

**Comment by erosb** [comment]
@nhajratw kudos for working on it! I'd really like to see it merged. Not only because of gradle, but because having the tests in the same repo is essential for external contributors. When #187 came up, the lack of tests stopped me to start fixing it on my own (I couldn't find them anywhere).

**Comment by nhajratw** [comment]
@stleary fwiw, this project is still fully self contained. No additional manual installations are needed. It uses the gradle wrapper (as is recommended), which bootstraps itself and downloads the necessary components to build.

The other thing that integrating this build tool buys us is the ability to easily add it as a job to https://travis-ci.org -- and then do more automated maven repository deployments that don't rely on individuals building and deploying from their own machines, where configurations/jdk versions/etc are unknown & potentially non-repeatable.

Also makes it easy to get automated test coverage metrics, static analysis, etc, etc...

**Comment by johnjaylward** [comment]
Linking in with Travis would be great and reduce the need to manually verify the tests for a pull request.

**Comment by stleary** [comment]
Maintaining the project with no unnecessary changes was part of the agreement, so modifying the build on the master branch is not an option. However, a branch can be made available where devs can arrange the source directories, build tools, and unit tests per their liking. Hopefully you all can find a way to make this work.  
https://github.com/stleary/JSON-java/tree/Build-and-Integration

The JSON-Java and JSON-Java-unit-test source code will be merged **from master to this branch** to keep them in sync. I don't have objections to using this branch to populate the Maven repository, so long as the executable jar is functionally identical to the code on the master branch. I also opened an account on Travis CI and registered the JSON-Java project. My understanding is that if you populate this branch with an appropriate YAML file, it can be built and tested automatically. Let me know if this will work for you.

**Comment by nhajratw** [comment]
I'm not familiar with the history of this project, so curious as what "the agreement" is.

Anyway, if the goal is to leave this project as is, then perhaps the best thing to do would be to create a new repo entirely, and simply include this project and the unit test project as submodules. Then, people who wanted this project alone could use it, and people who wanted a fully buildable/deployable system with tests could use the integration module "JSON-Java-package" perhaps?

If this seems agreeable, I can mock it up to show how it looks. Let me know. Thanks!

**Comment by stleary** [comment]
@nhajratw sorry, for the context, please see: https://github.com/stleary/JSON-java/wiki. Those were the conditions which I proposed for managing the project, and to which I think I am bound going forward. 

Regarding the history, if you go back over the pull requests and issues, build tools requests are relatively frequent, and have received a consistent response. The integration and build branch was created in the hope that it would provide a path for devs wanting to incorporate build tools; it will remain open for a few weeks in case anyone wants to use it.
