### ISSUE TITLE
JSONObject#accumulate has unexpected behavior for new keys

### ISSUE THREAD

**Issue by alexleigh** [stleary/JSON-java#196]
If accumulate is called with a key that is not yet in the object, the method checks if the value to be accumulated is a JSONArray. If it is, it creates a new JSONArray, puts the passed-in JSONArray inside of the new JSONArray, and puts the new array inside the object. If the value to be accumulated is not a JSONArray, it puts the value directly inside the object, without wrapping it in a JSONArray. This produces very strange results, for example using the code below:
```java
JSONObject test = new JSONObject();
test.accumulate("key1", new JSONArray().put("test1"));
test.accumulate("key2", "test2");
```

Results in the following JSON:
```json
{"key1":[["test1"]],"key2":"test2"}
````

Where test1 is nested two levels deep while test2 is not nested at all. The desired effect is probably something opposite of that: when the passed-in value is already a JSONArray, do not wrap it, but if it is not, wrap it in a JSONArray before setting it in the object. Alternatively, never wrapping the value and always directly setting it in the JSONObject would make sense as well.

**Comment by johnjaylward** [comment]
No, it's working as expected.

**Comment by johnjaylward** [comment]
To expand on my comment, the javadoc says this:```If only one value is accumulated that is not a JSONArray, then the result will be the same as using put```

It doesn't expand on what happens if the first object is a JSONArray, but as you can see it pre-wraps it in an array for you. If you continued to call accumulate the exact same way for test1, you'd see a result like this:

```java
JSONObject test = new JSONObject();
test.accumulate("key1", new JSONArray().put("test1"));
test.accumulate("key1", new JSONArray().put("test1"));
test.accumulate("key1", new JSONArray().put("test1"));
test.accumulate("key1", new JSONArray().put("test1"));
test.accumulate("key2", "test2");
```

```json
{"key1":[["test1"],["test1"],["test1"],["test1"]],"key2":"test2"}
```

If the initial array was not prewrapped, you would get this instead:
```json
{"key1":["test1",["test1"],["test1"],["test1"]],"key2":"test2"}
```

which is not the same thing.

**Comment by alexleigh** [comment]
Thanks for the explanation. We wanted something where the first value is consistently wrapped (or not wrapped) regardless of its type. Looks like `append` does the trick.
