### ISSUE TITLE
Recompile at JDK 1.6

### ISSUE THREAD

**Issue by kt-ssp** [stleary/JSON-java#197]
Including _JSON-java_ using maven:

```
        <dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20151123</version>
		</dependency>
```

for a project that is to be deployed to [IBM WebSphere Application Server] (http://www-03.ibm.com/software/products/en/appserv-was) (WAS) on versions ``8.0`` and ``8.5``, so require code compiled for ``Java 1.6``. 

Currently, _JSON-java_ is compiled for ``1.7`` so it does not load. Found two classes `org.json.JSONObject` and `org.json.JSONArray` that would not compile at ``1.6`` due to the use of multi-catch parameters. With these two adjusted, all compiled at ``1.6`` and the code works in WAS.

Would it be possible to make these changes permanent and release (through Maven at least) a version compiled at ``Java 1.6``?

**Comment by johnjaylward** [comment]
a PR has already been accepted for this. You can close this, the change should be in the next release.

**Comment by johnjaylward** [comment]
#195

**Comment by stleary** [comment]
Fixed in https://github.com/stleary/JSON-java/releases/tag/20160212. Let us know if there are an problems. Maven release pending.

**Comment by kt-ssp** [comment]
Appreciate the speed with which this was resolved and happy to confirm that having updated to the later maven version that all is working.

**Comment by stleary** [comment]
Great, thanks for confirming it is working.
