### ISSUE TITLE
Maven release needed

### ISSUE THREAD

**Issue by stleary** [stleary/JSON-java#198]
@BGehrels, can you please publish the latest release to the Maven repository when you have time?
The JSON-Java code can be found here: https://github.com/stleary/JSON-java/releases/tag/20160212
1. If you feel comfortable with the OSGi changes proposed in https://github.com/stleary/JSON-java/issues/189, feel free to include that in the Maven release as well.
2. If you can figure out some reasonable way to include the unit tests, that would be fine as well. See https://github.com/stleary/JSON-Java-unit-test/releases/tag/20160212. 

But only if 1 and 2 do not cause any issues with the JSON-Java code in the repository. If there are any questions or concerns, it would be best to leave them out.
Thanks, Sean

**Comment by johnjaylward** [comment]
Don't forget the new release should change the source/target compatibility to 1.6 instead of 1.7

**Comment by stleary** [comment]
Thanks @johnjaylward, yes, that too.

**Comment by BGehrels** [comment]
sadly the unit tests do no support the same language level as the main code:

    src\test\java\org\json\junit\JSONObjectTest.java:[1374,46] error: diamond operator is not supported in -source 1.6

so i had to compile and test it using java 1.7, then downgrade to java 1.6 and release it

But now they are on their way and should appear on maven central in the next hours - including the OSGI bundle descriptor. Please have a look at the jar when its in central and check, if everything is fine.

**Comment by stleary** [comment]
Thank you @BGehrels, the new Maven release and the OSGi bundle implementation looks good.
