### ISSUE TITLE
Javadocs should be hosted

### ISSUE THREAD

**Issue by stleary** [stleary/JSON-java#199]
Previously, the JSON-Java Javadocs were published on www.json.org/java, but that page is no longer accessible. A new home is needed.

**Comment by erosb** [comment]
What about something like stearly.github.io/json-java ?

**Comment by stleary** [comment]
Good idea @erosb, will try that.

**Comment by erosb** [comment]
You just have to create a github repository called stearly.github.io and
put the generated javadoc under a json-java/ directory. Making it
version-aware would be a plus (so the current javadoc goes
to json-java/20160212/ etc).

2016-02-14 17:02 GMT+01:00 Sean Leary <notifications@github.com>:

> Good idea @erosb <https://github.com/erosb>, will try that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stleary/JSON-java/issues/199#issuecomment-183907992>.
>



-- 


*Bence Erősme@github <https://github.com/erosb>*

**Comment by stleary** [comment]
Added gh-pages branch which is served up via http://stleary.github.io/JSON-java/index.html. For now, it contains the JavaDoc files generated from the Maven repository 20160212 release. I hesitate to include the original www.json.org/java page since the text, layout, and graphic does not belong to this project.

**Comment by erosb** [comment]
Thanks, just updated my link in my library ( https://github.com/everit-org/json-schema/commit/f89212f6a1a7372861bd457b81cdf4fd36634f7e )

**Comment by johnjaylward** [comment]
just checked out the new javadocs. They look good to me. I don't think we need to include the original javadocs. if we needed to, we could also just checkout the code at those points and gneerate/upload to version directories like @erosb mentioned earlier.

**Comment by stleary** [comment]
Thanks, will leave the pages as is for now, with an option to set up pages by release if it becomes necessary.

**Comment by jinahya** [comment]
If @stleary or any one else deploys the artifact to the central, [javadoc.io](http://www.javadoc.io/) should be a new way.
See what I just found.
http://www.javadoc.io/doc/org.json/json/20160212

**Comment by stleary** [comment]
@jinahya Good catch! Will include a link for released code, freeing up the local page (http://stleary.github.io/JSON-java/index.html) for the latest commits.
