### ISSUE TITLE
mavenize the project

### ISSUE THREAD

**Issue by yusuke** [stleary/JSON-java#2]
Currently maven is the most popular project build system.
By mavenizing the project, it'll be much easier to maintain, do continuous integration and more.

**Comment by jinahya** [comment]
For anyone's information, [JSON-Java-MG](https://github.com/jinahya/JSON-Java-MG) is in action.

**Comment by johnjaylward** [comment]
yeah, I did something similar on my clone as well. https://github.com/johnjaylward/Json-Java-Combined

To be honest, I'm not a fan or working with the modules. I think long term, the 2 projects will just need to be merged. How that looks is up for debate, but so far all the pull requests for something similar to what we did have been declined.
