### ISSUE TITLE
External hosting for JSON-Java Maven release JavaDocs

### ISSUE THREAD

**Issue by stleary** [stleary/JSON-java#207]
For example, see http://www.javadoc.io/doc/org.json/json/20160212
The readme should have links to released code JavaDocs,
and the local JavaDoc page should be updated after any commit that changes the JavaDoc.
The local page is overdue for an update now.

**Comment by johnjaylward** [comment]
I tested the url without the release, http://www.javadoc.io/doc/org.json/json/, and it redirects to the latest version. The readme could just use that.

**Comment by stleary** [comment]
Do we want the main link (which is not actually in the readme) to go to the JavaDoc for the latest Maven release, or the latest GitHub commit?
Whichever is selected, the Readme can contain a link to the other.

**Comment by johnjaylward** [comment]
hmm, I can't imagine there will ever be a huge difference between the 2 other than clarifications and spelling/grammar fixes. At most the latest commit may contain 1 or 2 new methods which would have new docs.

I think just having the latest release javadocs should be fine. Most github projects I see use the readme as a release document as well, so it makes sense to me to just use that.

**Comment by johnjaylward** [comment]
we could also just have the readme show both:

```
For the latest release javadocs see http://www.javadoc.io/doc/org.json/json/

For HEAD commit javadocs see http://stleary.github.io/JSON-java/
```

**Comment by stleary** [comment]
Not going to try to maintain multiple javadocs at this time.
