### ISSUE TITLE
JSONObject should maintain keys insert-order

### ISSUE THREAD

**Issue by ArifChishti** [stleary/JSON-java#210]
It would be nice to preserve keys order.
I am using [datatables](https://datatables.net/) in my project and I need to decide columns (and columns-order) on server side. DataTables renders columns in the order it receives column-keys. Currently, `JSONObject` does not preserve key-order. Will it be as simple as changing `HashMap` to `LinkedHashMap` in `JSONObject`.

**Comment by johnjaylward** [comment]
JSON does not guarantee ordered keys. See the specifications referenced in the readme. You should open a bug with datatables to allow an ordered configuration using an array of key names or some such.

**Comment by johnjaylward** [comment]
looking at the documentation it already supports this:
https://datatables.net/manual/ajax#Column-data-points

use the "columns" option

**Comment by ArifChishti** [comment]
@johnjaylward You are right. Thank you for your recommendation of DataTables manual reference.

This feature is not valid according to JSON specifications.
