### ISSUE TITLE
Request to support quotes within quotes as defined by RFC 4180

### ISSUE THREAD

**Issue by captainIowa** [stleary/JSON-java#217]
In some cases, it is necessary to process CSV files that contain quotation marks within the field's enclosing double quotes. [RFC 4180](https://tools.ietf.org/html/rfc4180) explains this behavior as follows:

> 7.  If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.  For example:

       "aaa","b""bb","ccc"

When encountering such a file, my quick/hacky fix in the  CDL.java file was as follows:

>case '\'':
            q = c;
            sb = new StringBuffer();
            for (;;) {
                c = x.next();
                if (c == q ) {
                	//Fix - check to ensure that this is not an escaped quote 
                	if(x.next() != '\"')
                	{	
                		x.back();
                		break;
                	}
                }
                if (c == 0 || c == '\n' || c == '\r') {
                    throw x.syntaxError("Missing close quote '" + q + "'.");
                }
                sb.append(c);
            }
            return sb.toString();

**Comment by kushieda-minori** [comment]
I've never used the CDL portion of this project. I'll leave it to @stleary to evaluate.

@captainIowa, are you able to publish this as a pull request or at least a patch. It will be easier to compare the changes that way.

**Comment by johnjaylward** [comment]
I've never used the CDL portion of this project. I'll leave it to @stleary to evaluate.

@captainIowa, are you able to publish this as a pull request or at least a patch. It will be easier to compare the changes that way.

**Comment by captainIowa** [comment]
@johnjaylward Excuse my naivety, but can I open a pull request when I'm not a member of this repo? Also, I'd be happy to submit a patch but need some instructions about the process (I don't know of a formal GitHub one). 

If it's equally as helpful, I cloned the repo, made the change (only a few lines in CDL.java), and zipped it up. The zip file is attached to this comment.
[JSON-java.zip](https://github.com/stleary/JSON-java/files/215625/JSON-java.zip)

**Comment by johnjaylward** [comment]
Generally the way to use github is to:
* Use the "FORK" button
* Branch your own fork
* Commit to your own branch.
* From the Github UI, use the "Submit Pull Request" button for your branch

It's a lot of extra work and kind of annoying, but it's how github works...

**Comment by captainIowa** [comment]
Thanks for the info! I just added a new [pull request](https://github.com/stleary/JSON-java/pull/219)

**Comment by stleary** [comment]
Thanks, we can continue the discussion in the pull request.
