### ISSUE TITLE
RFC 6901 (JSON Pointer) support

### ISSUE THREAD

**Issue by erosb** [stleary/JSON-java#218]
What do you think about adding [JSON Pointer](https://tools.ietf.org/html/rfc6901#section-5) support to the library?

From the API point of view I think it would mean a new method with a signature like `Object query(String jsonPointer)`, both in `JSONObject` and `JSONArray`.

@stleary if you give green light for this proposal then I may work on it.

**Comment by johnjaylward** [comment]
is this like XML Path but for JSON?

**Comment by erosb** [comment]
Exactly (and simpler too).

**Comment by stleary** [comment]
Torn between liking the idea and thinking maybe it is not part of the purpose of the lib. Hard to decide because I am not familiar with it - I use JsonPath in the unit tests. JsonPointer does not seem to have wildcards. Is this the case?

**Comment by erosb** [comment]
I've never used JsonPath, but it doesn't seem to be a standard, so I would still prefer implementing JSON Pointer. JsonPath also seems to be a more complex language, deserving its own library, while a JSON Pointer implementation would be small-enough to fit into only a few methods in this project.

**Comment by stleary** [comment]
Please proceed with JSON Pointer if you are still interested. Let's see what it would look like.

**Comment by stleary** [comment]
Please see https://github.com/stleary/JSON-java/pull/222

**Comment by erosb** [comment]
@stleary will youl merge #222 ?

**Comment by stleary** [comment]
@erosb I expect so. The implementation looks good so far. Have not had a chance to go over the unit test cases or coverage yet.
