### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by johnjaylward** [stleary/JSON-java#220]
Personally, I have no issue with using the license as-is, however some people apparently don't like the grey areas of the "The Software shall be used for Good, not Evil." clause.

In case you aren't aware of the history of it (as I wasn't until a few moments ago), here are a few links:

*https://github.com/restlet/restlet-framework-java/issues/1193
*https://en.wikipedia.org/wiki/Douglas_Crockford#.22Good.2C_not_Evil.22

**Comment by stleary** [comment]
Haha, yeah, I know some people hate it, but if we change the license now, then surely some bad people will figure they can finally use the lib to achieve their nefarious ends.   But seriously, thanks for the links. The wiki article has a reference to a YouTube talk Douglas gave on the history of JSON. Skip ahead to 39:46 where he mentions that he first used this license in 2002,  for our very own JSON-Java reference implementation. https://www.youtube.com/watch?v=-C-JoyNuQJs&t=39m50s Do we really want to change this unique bit of history?

**Comment by stleary** [comment]
Closing for now. Will reopen if Douglas decides to replace the current license.
