### ISSUE TITLE
Problem JSONObejct(Object bean) 

### ISSUE THREAD

**Issue by zhayunjie** [stleary/JSON-java#221]
JSONObejct(Object bean)  don't support the inner class

**Comment by erosb** [comment]
Could you please provide an example (with input and expected output, or something similar)?

**Comment by zhayunjie** [comment]
import org.json.JSONObject;

/**
 * Created by TBird on 2016/4/15.
 */
public class Main {

    public static void main(String args[]){
        Person p = new Person("TBird",24);

        JSONObject json = new JSONObject(p);
        System.out.println(json);



    }
}

class Person{
    private String name;
    private int age;

    public Person(){}

    public Person(String name,int age){
        this.name = name;
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
}

**Comment by stleary** [comment]
@zhayunjie I can't determine any problem with how JSONObject handles nested classes. Please see https://github.com/stleary/JSON-Java-unit-test/pull/44, which I will be merging soon. Open a new issue if you still think the code is not working right; maybe I am just not seeing what is not working.
