### ISSUE TITLE
Does not compile with Java 1.6

### ISSUE THREAD

**Issue by baszero** [stleary/JSON-java#223]
although the documentation says it should compile under 1.6, it currently doesn't:

`JSONObject.java:1845: illegal start of type
    [javac]         Map<String, Object> results = new HashMap<>();
`

it should be 

`
Map<String, Object> results = new HashMap<String, Object>();
`

**Comment by stleary** [comment]
@baszero Sorry, that was a new method added in https://github.com/stleary/JSON-java/pull/203. I neglected to check for 1.6 compatibility, will get this fixed soon.

**Comment by deprilula28** [comment]
Is 1.6 relevant anymore?

**Comment by johnjaylward** [comment]
yes

**Comment by baszero** [comment]
Thanks @stleary !
@deprilula28 : I just thought that if the library says it IS compliant, it should be. And there are still many applications relying on 1.6 as well...

**Comment by baszero** [comment]
Seems to be fixed now with ebf08f5651558a5384685b8dd977f16d37e688b0

**Comment by stleary** [comment]
Fixed in https://github.com/stleary/JSON-java/pull/226.
