### ISSUE TITLE
license

### ISSUE THREAD

**Issue by JackLauu** [stleary/JSON-java#224]
Hello, any license for this project? Can you add a license?

**Comment by johnjaylward** [comment]
It's at the top of every file

**Comment by stleary** [comment]
Although GitHub defaults to providing a license.txt file for each project, so far as I am aware, a separate license file is not required. But let me know if you think this is not the case.

**Comment by JackLauu** [comment]
Yes，if you add a license.txt file, it will be better for developer to aware this, or you can declaim it on the readme
