### ISSUE TITLE
JSON.toString for the string including utf-16 code \u2019

### ISSUE THREAD

**Issue by tjliupeng** [stleary/JSON-java#225]
I use the version json-20160212.jar.
I have the code below:
                       import org.json.JSONObject;
                       JSONObject json = new JSONObject();
			json.put("content", "\u00e9es permettant \u2019acc\u00e9der \u00e0 des donn\u00e9es issues de");
			String s = json.toString();
                        System.out.println(s);
And the print result is:
                        {"content":"ées permettant \u2019accéder à des données issues de"}
Why the character '\u2019' is displayed as UTF-16 code instead of the "right single quotation mark"? If I define a Java String which value is that string, this string can be printed correctly.

Thanks

**Comment by tjliupeng** [comment]
More comments:
If I debug the code, I can see that the HashMap of the JSONObject displays correctly. 

With this issue, I will get wrong byte array stream:

ByteArrayOutputStream out = new ByteArrayOutputStream();
OutputStreamWriter writer = new OutputStreamWriter(out, "utf-8");
json.write(writer); //this line should call JSONObejct.toString()
writer.flush();

ByteArrayInputStream in = new ByteArrayInputStream(out.toByteArray());

**Comment by stleary** [comment]
Is your issue that \u2019 is not handled correctly?

**Comment by johnjaylward** [comment]
The JSON spec dictates that that is valid output. I'm not sure what the request is either.

**Comment by tjliupeng** [comment]
@johnjaylward , I should say it is valid output according to the implementation. However, why do we set the range condition to  (c >= '\u0080' && c < '\u00a0') or (c >= '\u2000' && c < '\u2100')? With this code, \u2109 can not be handled correctly.

**Comment by tjliupeng** [comment]
@stleary , according to the code it is valid behavior. But for the library user, it should be an issue that \u2019 is not handled correctly.

**Comment by johnjaylward** [comment]
@tjliupeng I think you are using the word "correctly" wrong here. A JSON string does not need to be readable and can correctly be encoded entirely in \u escape notations.

I think that what you are asking is that all printable characters actually show up as unescaped. Maybe changing the check to something more like this:
http://stackoverflow.com/questions/220547/printable-char-in-java

I'm not sure what the performance implications of those block/character checks equates to though compared to the range checking. Historically other contributors have sent performance improvements to that method, so I'd prefer a solution that does not impact performance.

**Comment by tjliupeng** [comment]
@johnjaylward , you are right, A JASON string does not need to be readable. I am curious that why we set the code range like that. And for the JASON string including \u2109, with below code:
ByteArrayOutputStream out = new ByteArrayOutputStream();
 OutputStreamWriter writer = new OutputStreamWriter(out, "utf-8");
 json.write(writer); //this line should call JSONObejct.toString()
 writer.flush();

ByteArrayInputStream in = new ByteArrayInputStream(out.toByteArray());

The byte array will be wrong because \u2109 is treated as a normal string instead of UTF-16 code.

**Comment by johnjaylward** [comment]
The byte array is not wrong. I believe it's just your expectation is wrong. The value you are encoding is a JSON String. Not a java string. The 2 strings have 2 different properties and you are trying to treat them as though they are the same.

**Comment by tjliupeng** [comment]
@johnjaylward , could you give me some advices how to handle it that it can work normally as a Java string?

**Comment by johnjaylward** [comment]
They way you are doing it, it can't. You are byte encoding a JSONObject, so it has to be a JSON-String. The only way to get it back to a JAVA String would be to convert it again after doing the byte-decode.

```java
import org.json.JSONObject;
JSONObject json = new JSONObject();
json.put("content", "\u00e9es permettant \u2019acc\u00e9der \u00e0 des donn\u00e9es issues de");

ByteArrayOutputStream out = new ByteArrayOutputStream();
OutputStreamWriter writer = new OutputStreamWriter(out, "utf-8");
json.write(writer); 
writer.flush();

String reconstitutedJSONString = new String(out.toByteArray(),"utf-8");
JSONObject newJSON = new JSONObject(reconstitutedString);
String javaStringValue = newJSON.getString("content");
```

**Comment by tjliupeng** [comment]
@johnjaylward , wow, cool, thanks.

**Comment by johnjaylward** [comment]
If that solves your issue, feel free to close this

**Comment by qiuwei** [comment]
@johnjaylward  could you please explain why character like  (c >= '\u2000' && c < '\u2100') should be escaped?

I skim through the RFC of json, but couldn't figure out why.
Thanks in advance!

**Comment by qiuwei** [comment]
I was wondering why the range check was used and found this explanation.
https://stackoverflow.com/questions/24152678/json-character-encoding-in-javascript-different-from-java/24152844#24152844

It might be helpful for others.
