### ISSUE TITLE
Old version (20090211) source code?

### ISSUE THREAD

**Issue by flozano** [stleary/JSON-java#227]
I am suffering a library that depends on some behaviours(bugs?) of 20090211 version. I can't find the corresponding sources.jar in maven, and I can't find the relevant tags/branches in current github. Any idea where to find it?

**Comment by stleary** [comment]
Please upload someplace the original jar,  and post a description of the bugs/features of interest. We might be able to figure something out.

**Comment by johnjaylward** [comment]
The oldest commit in github is from Dec 21, 2010, so I'm not sure where you found that release. Does anyone know if this project was hosted elsewhere before that?

**Comment by flozano** [comment]
the JAR this library is using is http://search.maven.org/remotecontent?filepath=org/json/json/20090211/json-20090211.jar

This library is http://search.maven.org/remotecontent?filepath=org/brickred/socialauth/4.12/socialauth-4.12.jar.

The problem is related to data-type parsing. This library does very nasty stuff, and expects this to work:
```
		JSONObject o = new JSONObject();
		o.put("a", 1).getString("a");
```
which doesn't in latest versions. The lib doesn't have any unit-test, so it's quite challenging. We plan to fork it and fix it, but in meantime we need the source of the version of the org.json that it depends on.

**Comment by erosb** [comment]
The tests for the current version can be found here: https://github.com/stleary/JSON-Java-unit-test

**Comment by flozano** [comment]
@johnjaylward well, that version is in maven central and is depended on by this library I'm suffering.

**Comment by johnjaylward** [comment]
Yeah, I see that the only version there without source associated with it is the one you need. It looks like the only.

It seems that before using github, the only place the source was kept was on Json.org, which has since deleted the files.

What you may want to do is look up an old project like the opensymphony xwork project (what apache struts2 is now based on) as that had the old json.org source embedded into it. It is likely old enough that the source will match up pretty well.

**Comment by flozano** [comment]
wow... that's hard. thanks...

**Comment by johnjaylward** [comment]
It's in here: https://code.google.com/archive/p/opensymphony-webwork-backup/source/default/source

If you download the source, it's under the /tags/webwork_2-2-7/src/java/com/opensymphony/webwork/dispatcher/json/ folder

**Comment by stleary** [comment]
Or we can try decompiling the code. FYI, I still use Jad from http://varaneckas.com/jad/. 

Seems to me the only difference in this case may be that the old lib has getString(), but the new lib only has toString().

**Comment by johnjaylward** [comment]
I copied it to github for easier searching and browsing: https://github.com/johnjaylward/opensymphony-webwork-backup

**Comment by flozano** [comment]
From decompilation, versions don't match. This is a nightmare...
