### ISSUE TITLE
Serializable Classes

### ISSUE THREAD

**Issue by gauravjhs** [stleary/JSON-java#231]
JSONObject and JSONArray should be Serializable

**Comment by stleary** [comment]
Please provide some justification for why this feature is needed, and any ideas you have about how it should be implemented.

**Comment by gauravjhs** [comment]
Some cache provide option to Cache data on disk as well if cache size increases. We get java.io.NotSerializableException when we try to persist JSONObject in cache.

**Comment by stleary** [comment]
Thanks for making the suggestion. We only get to make the choice to serialize once. After that, we would seem to be stuck with it forever. A proposed implementation would be worth considering, but in addition to a solid use case, it would have to address the known problems, as described, for example, in Effective Java by Joshua Bloch.
