### ISSUE TITLE
RFC 6902 (JSON Patch) support

### ISSUE THREAD

**Issue by erosb** [stleary/JSON-java#232]
Hello,

I would like to add support to the library to understand the [JSON Patch format](https://tools.ietf.org/html/rfc6902)

It is used to describe modifications of a JSON document in a patch document. I think it fits into the scope of this library, and also it doesn't require a lot of code, so it won't drastically increase the size of this library.

@stleary what do you think?

Update: there are actually two RFCs used to describe changes to a JSON document:

* [RFC 7386 - JSON Merge Patch](https://tools.ietf.org/html/rfc7386)
* [RFC 6902 - JSON Patch](https://tools.ietf.org/html/rfc6902)

I've just created an [introductory description & comparison of them](http://erosb.github.io/post/json-patch-vs-merge-patch/).

I would prefer implementing both of these RFCs in this library, since both of them are simple.

**Comment by stleary** [comment]
Thanks, it's an intriguing idea, but at the present time JSONPointer is as far as I want to go with code that is not central to the purpose of JSON-Java.

**Comment by erosb** [comment]
No worries, then I think I will implement it as a separate library, maybe.

Do you think I can use a package name like org.json.patch for this work? Or
should it be com.github.erosb.jsonpatch instead ?

2016-05-15 17:00 GMT+02:00 Sean Leary <notifications@github.com>:

> Thanks, it's an intriguing idea, but at the present time JSONPointer is as
> far as I want to go with code that is not central to the purpose of
> JSON-Java.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/stleary/JSON-java/issues/232#issuecomment-219290727>
>



-- 


*Bence Erősme@github <https://github.com/erosb>*

**Comment by stleary** [comment]
Either is fine for GitHub. I think you will need to own the domain for the Maven repository.
