### ISSUE TITLE
Ignoring caught exceptions makes this library unusable

### ISSUE THREAD

**Issue by successhawk** [stleary/JSON-java#237]
The profuse usage of the anti-pattern of ignoring caught exceptions makes this library unusable.
try{...} catch (Exception ignore) {}

Please modify all occurrences to perform proper exception handling like throwing some form of RuntimeException wrapping the cause.
At a minimum, make it be able to log the exceptions in some type of debug mode.  I had to download and modify the source to debug my problem.

I found at least 5 occurrences in JSONObject.

**Comment by johnjaylward** [comment]
I've never had a problem with it using the library for 10+ years. can you give some examples of your data input, calls, etc so we can know what you are trying to do? In  many cases in the library, like all the opt* methods, it is proper and expected to eat the exceptions and return either null or a default value.

**Comment by successhawk** [comment]
All of my problems stemmed from the class not being public.  Here is a simple example.  I admit that I should have read the javadocs closer.  But it was surprising to me that when I explicitly told it what field to parse, it didn't throw an exception when it couldn't, and it wasn't easy for me to determine why it couldn't (there are many things that could go wrong when you catch Exception) until I modified the JSONObject code to print the exception.
 
`
System.out.println( new JSONObject(new Test(), new String[] {"message"}) );
`
```
// non-public class
class Test {
	public String message = "test";
}
```

**Comment by johnjaylward** [comment]
yes, I see what you mean now. It would make sense to split that exception handling up and ignore only specific exceptions that we knew about, or possibly expand the logic to prevent them in the first place.

**Comment by stleary** [comment]
Thanks for the suggestion. If interested, you can offer a pull request with your proposed changes. More information about what kinds of code changes are accepted can be found here: https://github.com/stleary/JSON-java/wiki/FAQ

**Comment by Mormuig** [comment]
It's a reasonably old post, but I run into that kind of problem to.
I have made some changes so that it's possible to get logs of otherwise ignored Exceptions, without changing the actual behavior.
May I post a pull request ?

**Comment by stleary** [comment]
Sure, if you can do it without using 3rd party libs, and if the logging is opt-in (not enabled by default).

**Comment by Mormuig** [comment]
I've done it using only Java Logging, so no 3rd party libs.
To keep the logging disabled by default, I used a low log level, as the goal is to give the possibility to log just by tweaking JSONObject and/or JSONArray loggers (or parents).
