### ISSUE TITLE
License Terms

### ISSUE THREAD

**Issue by vasdevdua** [stleary/JSON-java#245]
Hi,

Can you please help me with license term..we need to use this library in distributed environment

**Comment by stleary** [comment]
@vasdevdua, the license terms are not mine to change.

**Comment by johnjaylward** [comment]
@vasdevdua you can find the license terms on the top of each source file. If you are unsure if the terms will work in your environment, you should consult your company's lawyer. The license is fairly permissive as long as you are not using it for evil, so in general you should be OK.

**Comment by stleary** [comment]
A separate GitHub-compatible license file will be added to the repository. Please see #246.
