### ISSUE TITLE
Is any new release in schedule?

### ISSUE THREAD

**Issue by likel** [stleary/JSON-java#250]
I found some new feature such toMap, toList are very exciting, looking forward to using next release.

**Comment by stleary** [comment]
Anyone have an issue with cutting a release in the next few days or so?

**Comment by erosb** [comment]
I'd like it. A new version of `everit-org/json-schema` is also coming quite soon (1-2 weeks), it would be great to ship it with an updated `org.json:json` version.

**Comment by johnjaylward** [comment]
sorry, I still have to review pr #241, but I don't see an issue releasing all the currently merged items.

**Comment by stleary** [comment]
No issues apparently, so that is good. Are there any open PRs that you think need to be in this release? Being open at this time means that is is not considered critical and has not yet been verified. If you want one of the open PRs in this release, now is the time to mention it.

**Comment by johnjaylward** [comment]
#249 looks mergable to me.

**Comment by stleary** [comment]
Will be tagging a release in the next few days.

**Comment by likel** [comment]
@stleary That's great!
