### ISSUE TITLE
"has" function doesn't work for do-while statement

### ISSUE THREAD

**Issue by Frodgy** [stleary/JSON-java#252]
JSONObject jsontemp = JSONReader.readJsonFromUrl(url);
if(jsontemp.has("id")) { ... } - ok
but do { ... } while (jsontemp.has("id")); - wrong because Java "cannon find symbol".

**Comment by johnjaylward** [comment]
Cannot find symbol is usually a compile time error due to an undeclared variable or a class path issue.

**Comment by Frodgy** [comment]
Well, I worried, that it actually works with if statement.

**Comment by Frodgy** [comment]
Ok, so sorry, it worked...
