### ISSUE TITLE
JSONObject#toString(String indent) may be useful

### ISSUE THREAD

**Issue by erosb** [stleary/JSON-java#254]
It just came into my mind that a `JSONObject#toString(String indent)` method could be useful, which pretty-prints the object with repeated `indent` strings. For example it would be possible to indent with tabs, instead of with a given number of spaces.

It is not urgent at all, can be omitted from the next release. But if you give green light then I can create a PR in the (not so near) future.

**Comment by stleary** [comment]
@erosb, thanks, but not planning any changes in toString() at the present time.
