### ISSUE TITLE
warp of Sets of Enums is broken

### ISSUE THREAD

**Issue by Simulant87** [stleary/JSON-java#255]
When I use an Enum with a "getter"-method and put this value into a set and this set as a value of a JSONObject the String representation of the Enum is not the same as when I put the Enum directly as a value of the JSONObject. This issue depends on the `wrap` method of JSONObject that is called when a JSONArray (used for the Set) is created from a collection.

Here is an example.
```
    enum ToStringEnum{
        a,
        d(false);

        private final boolean flag;

        ToStringEnum() {
            this(true);
        }

        ToStringEnum(boolean disabledOnDefault) {
            this.flag = disabledOnDefault;
        }

        public boolean isFlag() {
            return this.flag;
        }
    }

    ToStringEnum a = ToStringEnum.a;
    JSONObject object = new JSONObject();
    Set<ToStringEnum> set = new HashSet<ToStringEnum>();
    set.add(a);
    object.put("testset", set);
    object.put("test", a);
    System.out.println(object.toString());
    //result: {"testset":[{"flag":true}],"test":"a"}
    //expected: {"testset":["a"],"test":"a"}
```

**Comment by stleary** [comment]
Enums have partial support in JSON-Java. You can get an idea of the extent of that support by reviewing the tests and comments in  https://github.com/stleary/JSON-Java-unit-test/blob/master/src/test/java/org/json/junit/EnumTest.java. Let me know if you think this needs to be more clearly documented in the JSON-Java README file.

**Comment by johnjaylward** [comment]
@stleary I think this is a valid concern we should look at fixing. Now that we are openly supporting java1.6+ I think it would be good to come up with a good definition of how Enums are handled and make sure it's consistent.

Having the same value produce 2 different results does not seem optimal to me. Would you like me to start a PR for this?
