### ISSUE TITLE
optBoolean isn't optional

### ISSUE THREAD

**Issue by quidryan** [stleary/JSON-java#260]
[JSONObject::optBoolean](https://github.com/stleary/JSON-java/blob/master/JSONObject.java#L944) no longer catches the exception thrown by [JSONObject::get](https://github.com/stleary/JSON-java/blob/master/JSONObject.java#L472).  This means that while it's called "opt" (optional), it throws an exception if not found. It's broken in a few recent versions of org.json.

**Comment by stleary** [comment]
Thanks for catching this! Will fix it soonest.

**Comment by johnjaylward** [comment]
@stleary it looks like all the opt functions have this issue, or at least most. They should be changed from
```java
Object object = this.get(key); 
```
to
```java
Object object = this.opt(key);
```
to prevent the missing key exception.

**Comment by stleary** [comment]
Agreed, another code change may fix it. But the unit tests did not catch it, so they will need to be tightened up too. If this simple bug is in the commit, others may have been included as well. There was no strong case for this pull request, it was supposed to be minor refactoring.  On the plus side, it looks like it can be reverted without affecting your latest commit.

**Comment by quidryan** [comment]
With the better tests proving that this is fixed, we can maybe fix forward.

**Comment by stleary** [comment]
Addressing this in #261, please post comments there going forward.

**Comment by johnjaylward** [comment]
I'm updating the test cases now to take this into account
