### ISSUE TITLE
JSON Arrays for all objects.

### ISSUE THREAD

**Issue by fhoda** [stleary/JSON-java#267]
This is more of a question...

I am trying to convert XML to Json and I need all nested objects to be inside of an Array. For instance:
```
<employee>
     <name>Joe</name>
     <name>Mike</name>
</employee>
```
&
```
<employee>
     <name>Joe</name>
</employee>
```

should both look like this....
```
employee: 
    {name: [
               Joe, 
               Mike
              ]
   }
```
and
```
employee:
    {name: [Joe]}
```
or even this output is ok...

```
employee: [
           {name: [
                       Joe,
                       Mike
                      ]
          }
    ]
```
and
```
employee: [
    {name: [Joe]}
    ]
```
The goal is to make sure that when I have a single item it is put in an array like it would if there were multiple items with the same key.

Any help or guidance on this would be greatly appreciated. Thanks!

**Comment by johnjaylward** [comment]
It is currently not possible, but I was thinking of the same option when I saw issue #235

**Comment by fhoda** [comment]
Ok, Thanks for the link.
