### ISSUE TITLE
Javadoc Warnings in XML.java

### ISSUE THREAD

**Issue by BGehrels** [stleary/JSON-java#268]
The following warnings occur when building the release artifact:

    [WARNING] Javadoc Warnings
    [WARNING] javadoc: warning - Error fetching URL: http://java.sun.com/javase/6/docs/api
    [WARNING] C:\Users\Benjamin\JSON-java\dist\src\main\java\org\json\XML.java:308: warning - Tag @link: missing '#': "JSONObject.stringToValue(String)"
    [WARNING] C:\Users\Benjamin\JSON-java\dist\src\main\java\org\json\XML.java:308: warning - Tag @link: can't find JSONObject.stringToValue(String) in org.json.XML

**Comment by stleary** [comment]
OK, lets see if I can fix that

**Comment by stleary** [comment]
Oops, thought you had halted the build for this. Anyway, should be fixed now, but please let me know if you see it again.
