### ISSUE TITLE
Disable trailing commas

### ISSUE THREAD

**Issue by erosb** [stleary/JSON-java#269]
Currently the parser permits trailing commas after the last key-value pair of an object. For example the following statement: `new JSONObject("{\"a\":1,}");` doesn't throw any exceptions. As far as I know trailing commas are not permitted in json.

**Comment by johnjaylward** [comment]
As far as I've seen, most JavaScript implementations do allow the trailing comma. I think this is similar to #240 where a request was made to be more strict.

Maybe a better option would be to create a "strict" parser option that validated the input matched actual JSON spec. If we had a flag for this, it would fix this request, as well as #240.

By default the parser would use the existing lose matching I'd think.

**Comment by stleary** [comment]
@erosb thanks for the suggestion. Technically, I think you are correct. But in this case it may be better for the implementation to be more forgiving than the spec.
