### ISSUE TITLE
XML.toJSONObject interprets certain strings as infinite numbers

### ISSUE THREAD

**Issue by bachp** [stleary/JSON-java#27]
Take the following XML snippet as an example.

```
<?xml version="1.0" encoding="UTF-8"?>
<subsonic-response xmlns="http://subsonic.org/restapi" status="ok" version="1.6.0">
  <playlists>
    <playlist id="476c65652e6d3375" name="Mood"/>
    <playlist id="50617274792e78737066" name="Party"/>
  </playlists>
</subsonic-response>
```

the `playlist` elements have id's that are hexadecimal strings.

in `<playlist id="50617274792e78737066" name="Party"/>` the id can also be interpreted as an exponential number. This makes the conversion of this snippet fail with the message: `org.json.JSONException: JSON does not allow non-finite numbers`

I don't know if there is a way to tell the difference between a number and a string from XML but I think the problem could be avoided if instead of throwing an exception the implementation interprets the infinite number as a string in any case.

**Comment by sivaramansv** [comment]
I have the following section in my XML document:
<dataId dt:dt="string">a98b174b86b54d7bb007d665382821d3</dataId>
and I am using the jar file json-20171018 for converting the XML document to JSON. 

I am getting the exact same error. How did you fix this?
org.json.JSONException: JSON does not allow non-finite numbers.
        at org.json.JSONObject.testValidity(JSONObject.java:1261)

**Comment by johnjaylward** [comment]
Please open a new issue with a fresh example. Preferably include the actual XML that is causing the problem, or at a minimum, a subsection of the XML that exhibits the problem.
