### ISSUE TITLE
JSONObject.putOnce(String, Object) Should not be throwing JSONException

### ISSUE THREAD

**Issue by Blossomforth** [stleary/JSON-java#276]
The `putOnce(String, Object)` method in `JSONObject` throws an exception if there is already a key of the same value already. This is an exception being thrown during a legal state. Per the java docs, it says it will ONLY put the k,v pair in IF the key does not exist. As a developer, this tells me that failure is a valid state, and should not have an exception thrown for it. Additionally, the fact that the method signature returns `this` indicates further that failure to put is an acceptable state.

Example:
Lets say i am using a `JSONObject` for a configuration object. I want to set a couple of default variables in the configuration when the application boots up. Based off of the method signature and the javadocs supporting this method, i would write:

`json.putOnce("key1", value1).putOnce("key2", value2).putOnce("key3", value3);`

This will work fine for the first launch, when there are no existing keys. However, on the next launch, since the first key exists, an exception is thrown. If I patch my application later, adding another default variable, it will never be initialized into the config, because the entire chain of putOnce calls has been broken by the first exception.

This would cause that line to look like this:

`try { json.putOnce("key1", value1); } catch (JSONException e) {}`
`try { json.putOnce("key2", value2); } catch (JSONException e) {}`
`try { json.putOnce("key3", value3); } catch (JSONException e) {}`

I'm pretty sure that isn't the goal of this library, am I wrong?

**Comment by johnjaylward** [comment]
The `@throws` notation in the javadoc for putOnce indicates that an exception is thrown on duplicate keys. I'd say that the intent is clear there.

Maybe what you'd like instead is something like a `putOnceOpt` that silently fails on duplicate keys?

**Comment by Blossomforth** [comment]
Exactly, that's what I'm looking for, essentially. And I did notice the `@throws`, but it just felt like there was a lot of conflicting information there. The bit that really threw me off was the return type being `JSONObject`, and the exception breaking chains of method calls.

**Comment by johnjaylward** [comment]
Also, if you have default values, I'd insert them into the configuration first, then let the customizations override the defaults:

```java
private void SomeConstructor() {
  json.put("key1", default);
  json.put("key2", default);
  // etc
}

public void config(Properties config) {
  for ( String key : config.stringPropertyNames() ) {
    json.put(key, config.getProperty(key));
  }
}

myObject.config(someconfig);

**Comment by stleary** [comment]
No objection to a pull request. Recommend a single new public API method that does not throw an exception or perform the put operation on duplicate keys, has non-null key and value checking, returns 'this' unconditionally, and includes unit tests: https://github.com/stleary/JSON-Java-unit-test
````
public JSONObject putOnceOpt(String, Object);
````

**Comment by johnjaylward** [comment]
would it be better to use a name like putIfAbsent like in ConcurrentHashMap:

https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#putIfAbsent-K-V-

**Comment by stleary** [comment]
No preference on the method name.

**Comment by stleary** [comment]
Thanks for the suggestion. As noted, please open a pull request if you want this change.
