### ISSUE TITLE
Proper handling of attributes when converting from JSON to XML

### ISSUE THREAD

**Issue by wheineman** [stleary/JSON-java#278]
The convention used to convert from XML to JSON places attributes as keys within a key. For example:

{
    "structure": {
        "content": "BLAHBLAHBLAH",
        "entityFormat": "MOL",
        "entityType": "Small Molecule"
    }
}

where  content is the data between the tags <structure></structure> and the the attributes (in this case "entityFormat" and "entityType") become additional keys to the structure. When round trip converting back to XML you end up with this:

<structure>
  BLAHBLAHBLAH
  <entityFormat>MOL</entityFormat>
  <entityType>Small Molecule</entityType>
</structure>

what is desired is 

<structure entityFormat="MOL" entityType="Small Molecule>
  BLAHBLAHBLAH
</structure>

I modified XML.java to do just this and have attached it.

[XML.zip](https://github.com/stleary/JSON-java/files/426950/XML.zip)

**Comment by stleary** [comment]
Agreed that XML-JSON mapping is imperfect. Check out JSONML.java in this project for an alternative implementation. You can submit a pull request if you have something in mind that does not change the behavior for existing users. You might have a look at recent accepted and denied pull requests, to get an idea of what might be acceptable.
