### ISSUE TITLE
when put long or Long into a JSONObject, the toString() result is totally different

### ISSUE THREAD

**Issue by guogl** [stleary/JSON-java#280]
if you put a "long" NOT "Long" into jsonObject, then the toString() method will be "9.2337203685478815e17" which is treated as double. And when you want to parse back to long object or Long object, then exception will be thrown out. i.e.. java.lang.NumberFormatException: For input string: "2.4285025E7".

If you put a "Long" object into jsonObject, then the toString() method will be "92337203685478815" which is a real long value. Then you can parse it back to Long object or long object.

The expected behaviour should be:
Put long or Long into a JSONObject, the toString() result should be identical and keep the format it is instead of formatting it to a double number.

**Comment by guogl** [comment]
seems that this issue had been fixed in the latest version.

**Comment by stleary** [comment]
@guogl Thanks for investigating, glad to hear it has been fixed.
