### ISSUE TITLE
Pretty-printing complex JSON objects, such as JOSE/JWS

### ISSUE THREAD

**Issue by mouse07410** [stleary/JSON-java#281]
I am trying to display JSON objects that contain other JSON objects - such as [JOSE/JWS](http://jose.readthedocs.io/en/latest/), also defined in [RFC 7515](https://tools.ietf.org/html/rfc7515), and [wiki](https://en.wikipedia.org/wiki/JSON_Web_Signature) 

This is the code:
```
. . . . .
               JWSObject jwsObject = new JWSObject(new JWSHeader(JWSAlgorithm.RS256), new Payload("In RSA we trust!"));
. . . . .
		// Compute the RSA signature
		jwsObject.sign(signer);
                // Attempts to pretty-print the content of this JWS object
		// using org.json library
		JSONObject job = new JSONObject(jwsObject);
		System.out.println("\norg.json jwsObject:\n" + job.toString(4));
. . . . .
```
Here's what I'm getting:
```
org.json jwsObject:
{
    "parsedString": "eyJhbGciOiJSUzI1NiJ9.SW4gUlNBIHdlIHRydXN0IQ.HJFxB2audTp1f4vb2IjB921g8YhwmjO-U-tK6RFypnRrGO4du7Mlbcl1jIO4BeKaP_CRaTGAMZMV92gwDVyzlAeLsnQ9JgRTrBsOCqhM7JcDa2XYwdbcxH-T5AkptpS155uDbBUWr2G1yOVHsqs5l9hnfn_O91Trhsj0503IJic",
    "signature": {},
    "payload": {"origin": {}},
    "signingInput": [
        101,
        121,
        74,
        104,
        98,
        71,
        99,
        105,
        79,
        105,
        74,
        83,
        85,
        122,
        73,
        49,
        78,
        105,
        74,
        57,
        46,
        83,
        87,
        52,
        103,
        85,
        108,
        78,
        66,
        73,
        72,
        100,
        108,
        73,
        72,
        82,
        121,
        100,
        88,
        78,
        48,
        73,
        81
    ],
    "header": {
        "customParams": {},
        "includedParams": ["alg"],
        "registeredParameterNames": [
            "x5t#S256",
            "crit",
            "jku",
            "x5t",
            "x5c",
            "kid",
            "x5u",
            "cty",
            "typ",
            "alg",
            "jwk"
        ],
        "parsedBase64URL": {},
        "algorithm": {
            "name": "RS256",
            "requirement": {}
        }
    },
    "state": {},
    "parsedParts": [
        {},
        {},
        {}
    ]
}
```

Here's another attempt:
```
. . . . .
		// Pretty-print using org.json.JSONStringer
		String jw = new JSONStringer()
				.object()
					.key("JWS")
					.value(new JSONObject(jwsObject))
				.endObject()
				.toString();
		
		System.out.println("signed JWS: " + jw);
```
with the result:
```
signed JWS: {"JWS":{"signature":{},"payload":{"origin":{}},"signingInput":[101,121,74,104,98,71,99,105,79,105,74,83,85,122,73,49,78,105,74,57,46,83,87,52,103,85,108,78,66,73,72,100,108,73,72,82,121,100,88,78,48,73,81],"header":{"customParams":{},"includedParams":["alg"],"registeredParameterNames":["x5t#S256","crit","jku","x5t","x5c","kid","x5u","cty","typ","alg","jwk"],"algorithm":{"name":"RS256","requirement":{}}},"state":{}}}

```

What's the right way to pretty-print such objects?

Thanks!

**Comment by johnjaylward** [comment]
That class is not part of this library. Are you developing it and
requesting assistance, or looking for support?

**Comment by johnjaylward** [comment]
Oh, nevermind, my email formatted your code weird. I see you are trying to
use JSONObject and JSONStringer to format a bean of type JWSObject.

**Comment by mouse07410** [comment]
I am requesting assistance, if possible - as it doesn't look like I'm using JSONStringer correctly or appropriately.

**Comment by johnjaylward** [comment]
It does not appear that JSONStringer can pretty print anything. It builds the object string on the fly as you add items to it. 

As soon as you call `.value(new JSONObject(jwsObject))` your jsonObject is converted to a string with no extra white space such as new lines and indentation.

If you want to pretty print, I'd do something like your first example. The following is equivalent to your JSONStringer code:
```java
JSONObject jo = new JSONObject();
jo.put("JWS", new JSONObject(jwsObject));

System.out.println("signed JWS: " + jo.toString(4);
```

It's not quite as in-line to get the string result, but it will be pretty printed.

**Comment by johnjaylward** [comment]
If you are intent on using the JSONStringer, another option would be something like this:

```java
String jw = new JSONStringer()
                .object()
                    .key("JWS")
                    .value(new JSONObject(jwsObject).toString(4))
                .endObject()
                .toString();

        System.out.println("signed JWS: " + jw);
```

**Comment by mouse07410** [comment]
Yes... And to complicate things further, I expect the JSON objects to be hierarchical - including other objects as values, like
```
{  
   {"key1" : [{"key11" : "string11"}, {"key 12" : "string12"}]},
   {"key2" : { "key21" : { <another object, etc...} } }
}
```

It seems that the majority of "pretty-printers" would stop at the first "indirection", and won't go recursively parsing the object...

My problem is complicated further by the fact that JOSE JWS objects have their components Url64-encoded, so to present them in a really nice (understandable) way I'd need to "unwrap" ("deserialize") those. Think of MIME or better yet S/MIME email - if it's MIME-encoded and signed, you can only read it if your email client "unwrapped" the parcel for you. But if it is clear-signed - then you can view/read the content with any email application including WireShark :), even though only S/MIME-aware email clients would be able to verify the digital signature for you. I'm trying to implement an analog of such "clear-signed" object - make the object generally usable and viewable, even though only JWS-aware apps can actually verify its signature and attest whether this JWS object is good or bad...

**Comment by stleary** [comment]
No plans at this time to enhance pretty-printing, but feel free to propose a pull request if there is some improvement you want to make.

**Comment by CjStaal** [comment]
HOW DO I UNSUBSCRIBE

**Comment by johnjaylward** [comment]
log into github and either un-star the project, or go to the specific tickets and click "unsubscribe"
