### ISSUE TITLE
XMLtoJson parser parse string 3E896756757 as scientific notation on number and report error

### ISSUE THREAD

**Issue by Yingmin-Li** [stleary/JSON-java#284]
Only under Linux, it parse xml below and throw error: JSON does not allow non-finite numbers.

<q>3E896756757</q>

**Comment by stleary** [comment]
This should be addressed in #253. Maybe comments need to be added to the JavaDoc or README...

**Comment by stleary** [comment]
Please open a new issue if you think there is still a problem.
