### ISSUE TITLE
XML.toString - Escape nightmare

### ISSUE THREAD

**Issue by eduveks** [stleary/JSON-java#285]
The XML.escape is very basic and when working with latin accents I can not reach a good result!

Will no escape latin accents and if I escape before then the result will be &amp;atilde; (madness)

I suggest to use: org.apache.commons.lang3.StringEscapeUtils.escapeHtml4

Is the better escape solution, works like a charm with all characters in my experience.

Or adds these methods to avoid the default escape:

- XML.toString(Object object, String tagName, **boolean escape**)

- XML.toString(Object object, **boolean escape**)

Thank you!

**Comment by stleary** [comment]
Can you provide a code and JSON text fragment that demonstrates the problem, and what you would prefer to see in the XML.toString() output?

There are no plans now, nor are any expected in the future, where 3rd party libs will be included in the project. See https://github.com/stleary/JSON-java/wiki/FAQ

**Comment by eduveks** [comment]
Ok! I understand your position to don't use external libs. Then please make a solution to do not escape the &.

A little sample:
```
try {
	JSONObject json = new JSONObject("{ \"amount\": \"10,00 €\", \"description\": \"Ação Válida\" }");
	System.out.println(XML.toString(json));
} catch (JSONException e) {
	e.printStackTrace();
}
```

Output:
```
<amount>10,00 €</amount><description>Ação Válida</description>
```

But... sending this XML output to another service will be converted to:
```
<amount>10,00 􀀁</amount><description>A􀀁􀀁o V􀀁lida</description>
```

Because the special characters need be escape!

But has a lot of special characters in so many languages like portuguese, french, spanish, arabic, chinese, german... and the special characters with accents need be escaped correctly to ensure that do not miss the encoding. 

If pre escape the JSON:
```
try {
	JSONObject json = new JSONObject("{ \"amount\": \"10,00 &euro;\", \"description\": \"A&ccedil;&atilde;o V&aacute;lida\" }");
	System.out.println(XML.toString(json));
} catch (JSONException e) {
	e.printStackTrace();
}
```

The output is:
```
<amount>10,00 &amp;euro;</amount><description>A&amp;ccedil;&amp;atilde;o V&amp;aacute;lida</description>
```

And the correctly is:
```
<amount>10,00 &euro;</amount><description>A&ccedil;&atilde;o V&aacute;lida</description>
```
No way to make a workaround because the **&** is always converted to **&amp;** in XML.toString

**Comment by johnjaylward** [comment]
I think XML and json are both supposed to support Unicode properly. Maybe
check that the encoding is properly set in your XML header as utf8 instead
of ASCII or some other encoding.

**Comment by eduveks** [comment]
johnjaylward, is not true! When you sends your bytes throgh web services and reverse proxies, and information passing in 3 or 4 web servers and where in each one converts to string, many things can happen...

I just need to control the escape because the default escape is very basic. Just it! A flag to not escape.

**Comment by johnjaylward** [comment]
I think the right solution would probably be to place the correct Unicode
in the JSONObject, but then have the XML toString escape Unicode chars as
hex escapes similar to what happens in JSONObject.toString

**Comment by eduveks** [comment]
Like this?
```
try {
	JSONObject json = new JSONObject("{\"amount\": \"10,00 \\u20AC\", \"description\": \"A\\u00E7\\u00E3o V\\u00E1lida\"}");
	System.out.println(XML.toString(json));
} catch (JSONException e) {
	e.printStackTrace();
}
```
Sounds perfect! But I think will be hard to accomplish.
```
<amount>10,00 &#x20AC;</amount><description>A&#xE7;&#xE3;o V&#xE1;lida</description>

**Comment by johnjaylward** [comment]
Yes, that was what I was picturing.

**Comment by eduveks** [comment]
What means closed, will not be done?

Just to I know to looking for another solution...

**Comment by stleary** [comment]
No objection if you want to create a pull request that solves your problem without causing problems to existing applications.

**Comment by eduveks** [comment]
Ok! ;)

**Comment by johnjaylward** [comment]
I believe I have a PR that will fix this. Just writing up the documentation on it now.
