### ISSUE TITLE
toJSONObject(String xml) crashes if xml == html

### ISSUE THREAD

**Issue by AppWerft** [stleary/JSON-java#289]
Hi Sean,

in some cases the server give us a HTML instead of XML  or a captive portal (man in the middle) delivers me HTML. How can I catch this error?

Code strong!

Rainer

**Comment by johnjaylward** [comment]
```java
try {
 XML.toJSONObject(xmlString);
} catch (JSONException ex) {
  // not a valid XML doc. handle error here.
}
```

**Comment by stleary** [comment]
Assuming your question was answered by @johnjaylward
