### ISSUE TITLE
Improvement for JSONObject class

### ISSUE THREAD

**Issue by kpopovic** [stleary/JSON-java#295]
Hello,
please add new methods to JSONObject class. I think the can be very useful.

byte[]	getBinary(String key) / byte[] getBinary(String key, byte[] def)
------------------------------------------
JSON itself has no notion of a binary, this extension complies to the RFC-7493, so this method assumes there is a String value with the key and it contains a Base64 encoded binary, which it decodes if found and returns.

public JsonObject put(String key, byte[] value)
-------------------------------------------------------------
Put a byte[] into the JSON object with the specified key.
JSON extension RFC7493, binary will first be Base64 encoded before being put as a String.

public java.time.Instant getInstant(String key)
------------------------------------------------------------
Get the instant value with the specified key.
JSON itself has no notion of a date, this extension complies to the RFC-7493, so this method assumes there is a String value with the key and it contains a ISODATE encoded date, which it decodes if found and returns.

example:
 public Instant getInstant(String key) {
    Objects.requireNonNull(key);
    String encoded = (String) map.get(key);
    return encoded == null ? null : Instant.from(ISO_INSTANT.parse(encoded));
  }

java.time.Instant	getInstant(String key, java.time.Instant def)
Like getInstant(String) but specifying a default value to return if there is no entry.
-------------------------------------------------------------------------------------------------------------
example:
public Instant getInstant(String key, Instant def) {
    Objects.requireNonNull(key);
    Object val = map.get(key);
    return val != null || map.containsKey(key) ?
        (val == null ? null : Instant.from(ISO_INSTANT.parse((String) val))) : def;
  }
public JsonObject put(String key, java.time.Instant value)
-------------------------------------------------------------------------------------------------------------
Put a Instant into the JSON object with the specified key.
JSON extension RFC7493, instant will first be encoded to ISODATE String.

example:
import static java.time.format.DateTimeFormatter.ISO_INSTANT;
.....
public JsonObject put(String key, Instant value) {
    Objects.requireNonNull(key);
    map.put(key, value == null ? null : ISO_INSTANT.format(value));
    return this;
  }

public JsonObject copy()
........................................
Copy the JSON object

**Comment by johnjaylward** [comment]
We don't currently support java8, so I don't see the Instant items being
implemented.

**Comment by kpopovic** [comment]
Java 8 was released on 18 March 2014, more then 2 years ago...
Do you plan to support Java 8 at all ?

**Comment by johnjaylward** [comment]
We are currently supporting java6 and up, but that means no java8 specific
features

**Comment by kpopovic** [comment]
Ok, I understand.

**Comment by stleary** [comment]
Not adding support for date or time transforms at this time. No objection if someone sees a need for Base64 and wants to try implementing it in a way that does not impact existing applications.
