### ISSUE TITLE
Debug info in the released binaries

### ISSUE THREAD

**Issue by OndraZizka** [stleary/JSON-java#298]
Could the released binaries contain debug information? It has no impact on the performance (after classes are loaded) and lack of them makes it hard to figure out what the errors like "value out of sequence" mean. Thanks.

**Comment by johnjaylward** [comment]
http://stackoverflow.com/questions/1872491/why-are-some-java-libraries-compiled-without-debugging-information

I know some users use this library in mobile code. I'm not sure how many people would want this enabled.

**Comment by stleary** [comment]
Thanks for the suggestion. Per comment by @johnjaylward, we will continue to release the library without debugging enabled. You should be able to easily build the library from source with debugging if you need it. Did you really get a "value out of sequence" exception? I would not expect that to occur outside of test code.
