### ISSUE TITLE
Element order 

### ISSUE THREAD

**Issue by JoeBengalen** [stleary/JSON-java#300]
Hello all,

 When using this library I noticed that the order of the JSON elements change when loading a JSON string into a `JSONObject` and casting it back to a string. This is because the elements are stored in a `HashMap` which does not maintain the order. Changing this to a `LinkedHashMap` solved the problem. I noticed this behavior in java 7.

To make the tests pass I also updated the test suite. Tests will now pass both Java 7 and 8 (except that Java 7 does not have `Long.sum()` symbol.

Changes I made:
https://github.com/JoeBengalen/JSON-java/commit/e88394a6aaff15c89a346e9729330bc51468dce2
https://github.com/JoeBengalen/JSON-Java-unit-test/commit/941525a1737d017a1da6a2b3693d14de52792443

Please let me know if you would like a pull request with these changes.

**Comment by erosb** [comment]
Hello,
this definitely won't be merged. This has been requested in at least [6 issues](https://github.com/stleary/JSON-java/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20order) and [3 pull requests](https://github.com/stleary/JSON-java/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20order) . The most detailed reasoning about this topic is probably [this comment](https://github.com/stleary/JSON-java/issues/228#issuecomment-219150368)

**Comment by JoeBengalen** [comment]
ah sorry, should have looked at previous issues.

I know it's not part of the JSON spec, but for our use case the order is important.
