### ISSUE TITLE
order changes for json to xml conversion

### ISSUE THREAD

**Issue by rajeshrai248** [stleary/JSON-java#303]
everytime we use json to xml conversion property. it changes the order. I looked in the implementation of java-json and found out that it is occurring because of JsonObject defined as HashMap.
cant we change it to LinkedHashMap or is there any dependency on it?

**Comment by MinnDevelopment** [comment]
JSONObject by definition do not have ordered keys.

**Comment by stleary** [comment]
This is covered in the FAQ: https://github.com/stleary/JSON-java/wiki/FAQ
