### ISSUE TITLE
XMLTokener's method nextContent is trimming trailing spaces

### ISSUE THREAD

**Issue by pankaj11111990** [stleary/JSON-java#305]
Hi,

I am using this API in one my project for converting XML to JSON. while working on one aspect i came across a situation a user has to send spaces and want to get same content with spaces intact.
in current version of XMLTokener class, method nextContent is opening is trimming spaces of content which is kind modifying data.
Please help me to understand why designer of this API consider trimming on content.

Thanks in Advance
Pankaj

**Comment by pankaj11111990** [comment]
Hi,
Thanks for reply.
CDATA section is a nice suggestion. Although i found some limitations with this in tutorialspoint
1)CDATA cannot contain the string "]]>" anywhere in the XML document.
2)Nesting is not allowed in CDATA section.
A user can pass any value including "]]>" as part of data. 
How can this situation be avoided?
Regards

**Comment by johnjaylward** [comment]
CDATA sections should be used within an element.

```xml
<exampleOfACDATA>
<![CDATA[
    Since this is a CDATA section
    I can use all sorts of reserved characters
    like > < " and &
    or write things like
    <foo></bar>
    but my document is still well formed!
]]>
</exampleOfACDATA>
```

using it like this, you should not have any nesting. As far as I know, there is no way to escape the end tag of the CDATA ]]>. If you have any of these in your data that you wish to place in a CDATA section, you would need to clean it or escape it yourself before placing it in the XML.

**Comment by johnjaylward** [comment]
Well, one thing you can do is this:
```xml
<exampleOfACDATA>
<![CDATA[
    Since this is a CDATA section
    I can use all sorts of reserved characters
    like > < " and &
]]>]]><![CDATA[
    or write things like
    <foo></bar>
    but my document is still well formed!
]]>
</exampleOfACDATA>

I'm not sure how this will turn out with the JSON parser, but since an XML Doc is ordered, this should work in theory.

**Comment by stleary** [comment]
There is a workaround, and at this time I don't see anything that needs to be fixed in the lib.

**Comment by pankaj11111990** [comment]
Thanks John and Stleary for you quick reply
will see if CDATA can help in all my use cases.
