### ISSUE TITLE
javadocs do not build on java 1.8 in netbeans

### ISSUE THREAD

**Issue by shatteredsword** [stleary/JSON-java#307]
not sure if I'm doing something wrong, but I'm getting a ton of warnings and errors when trying to generate javadocs  
[log.txt](https://github.com/stleary/JSON-java/files/688191/log.txt)

**Comment by johnjaylward** [comment]
This project has very loose javadoc usage. In NetBeans you would have to configure the javadoc generation to ignore errors and warnings. I've not used netbeans myself so I'm not sure where those settings are.

**Comment by stleary** [comment]
@shatteredsword No objections if you want to submit a pull request with cleaned up JavaDoc.

**Comment by stleary** [comment]
Post if you want to reopen to continue the discussion. Pull request still OK if someone wants to take that on.
