### ISSUE TITLE
XML.toString() returns invalid xml

### ISSUE THREAD

**Issue by MrFaridMam** [stleary/JSON-java#308]
I created JsonObject from String, then used XML.toString(JsonObject o) to create XML String to send response in my Servlet. But browser says it's invalid.

**Comment by johnjaylward** [comment]
Can you give an example to reproduce this?

**Comment by MrFaridMam** [comment]
try this json:

```
{  
   "someObject":{  

   },
   "someObject2":{  

   },
   "someArray":{  
      "1234":[  
         {  
            "object":"data"
         }
      ]
   }
}
```

there is 2 error: 1st - there is no global <root> tag after conversion. 2nd - <1234> tag is incorrect, so I added to XML.java this code(416th line):

 ```
if (key.matches("\\d+")) {
                    key = "id_" + key;
                }
```

**Comment by stleary** [comment]
Given the JSON text input, the transformed XML looks reasonable to me. Please post what you think it should have been.

<someObject2></someObject2>
<someObject></someObject>
<someArray>
 <1234>
  <object>data</object>
 </1234>
</someArray>

**Comment by johnjaylward** [comment]
this is a known issue. Our policy to date has been that the XML output does not guarantee valid XML. This is especially true with numeric element IDs. <1234> is not valid XML. Our suggestion to other posters has been to pre-process the JSONObject before calling `XML.toString(JSONObject o)`

See #294 for the most recent discussion on it.

**Comment by stleary** [comment]
Post if you want to reopen this issue for further discussion.
