### ISSUE TITLE
multi-line string values

### ISSUE THREAD

**Issue by arikast** [stleary/JSON-java#309]
Perhaps this is more of a feature request than issue, since I gather json doesn't officially support multi-line string values, but I'd really like multi-line string support!

Currently this breaks:

```
String problem = "{ \"problem\": \"This \r\n is a problem\" }";
JSONObject json = new JSONObject(problem);
```

I'd love to see something like Jackson's JsonParser.Feature.ALLOW_UNQUOTED_CONTROL_CHARS option supported. JSON-java already generously exhibits JsonParser.Feature.ALLOW_UNQUOTED_FIELD_NAMES behavior by default, so since the floodgate of allowing non-compliant json has already been opened, I'd very much appreciate this addition. 

Such behavior would be helpful when parsing external json whose generation is outside our control.  I could look into it and submit a pull request if it's helpful.

**Comment by johnjaylward** [comment]
@stleary I don't have a problem with this if someone provides a pull request. Per the JSON spec, the parser is allowed to be more flexible then the generator. As long as we continue to properly escape the output, this shouldn't effect existing applications in a negative way.

@arikast do you have time to make a pull request? I know I don't at the moment.

**Comment by johnjaylward** [comment]
@erosb would allowing the parser to accept new line chars like the above cause an issue with your tool-chain?

**Comment by erosb** [comment]
Definitely not.

Thanks for keeping it in mind :+1:

**Comment by stleary** [comment]
No objection here, provided we stay within the spec.

**Comment by arikast** [comment]
Great!  I'll look into it and submit a PR.

**Comment by stleary** [comment]
Still consider this a valid enhancement, if anyone wants to propose a pull request.
