### ISSUE TITLE
Performance Degrade: StringBuilder.newCapacity() being called a number of times

### ISSUE THREAD

**Issue by ghost** [stleary/JSON-java#314]
toString() in JSONObject which inturn uses a StringBuilder is initiated with the default size of 16. This is not enough if the number of keys are huge. The below mentioned loop is executed large number of times and this inturn results in high number of StringBuilder.newCapacity() calls which are unnecessary and degrade performance. This can be easily avoided if there is a toString method where user can set the value of initial capacity of StringBuilder.

while (keys.hasNext()) {
                if (sb.length() > 1) {
                    sb.append(',');
                }
                Object o = keys.next();
                sb.append(quote(o.toString()));
                sb.append(':');
                sb.append(valueToString(this.map.get(o)));
            }

**Comment by stleary** [comment]
Not sure which use of StringBuilder is being referenced. While optimizations are not usually accepted, you are welcome to make a case by quantifying the performance improvement.

**Comment by stleary** [comment]
Closed due to lack of activity. Feel free to request a reopen if you are working on a solution.
