### ISSUE TITLE
Construct a JSONObject from an Object using bean getters is inconsistent across locales

### ISSUE THREAD

**Issue by jakope0003** [stleary/JSON-java#315]
Construct a JSONObject from an Object using bean getters produce unexpected result when locale is set to Turkey.

Having following two classes `Bean.java` and `JSONIssue.java`.

```java
public class Bean {

    private final String id;

    public Bean(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

}
```

```java
import java.util.Locale;
import org.json.JSONObject;

public class JSONIssue {

    public static void main(String[] args) {
        Locale.setDefault(new Locale("en"));
        JSONObject jsonen = new JSONObject(new Bean("beanId"));
        System.out.println("jsonen " + jsonen);

        Locale.setDefault(new Locale("tr"));
        JSONObject jsontr = new JSONObject(new Bean("beanId"));
        System.out.println("jsontr " + jsontr);
    }

}
```

Output differs for different locales.

```
jsonen {"id":"beanId"}
jsontr {"?d":"beanId"}
```

I'm expecting to have consistent id key no matter what locale is set.

**Comment by johnjaylward** [comment]
Can you print both JSON after the local change? 

Save the first JSON string to a var, change the local,  then print both?

**Comment by jakope0003** [comment]
Please find proposed patch:

```java
diff --git a/JSONObject.java b/JSONObject.java
index 4df256a..14a86d5 100644
--- a/JSONObject.java
+++ b/JSONObject.java
@@ -1159,7 +1159,7 @@ public class JSONObject {
                         if (key.length() == 1) {
                             key = key.toLowerCase();
                         } else if (!Character.isUpperCase(key.charAt(1))) {
-                            key = key.substring(0, 1).toLowerCase()
+                            key = key.substring(0, 1).toLowerCase(Locale.ROOT)
                                     + key.substring(1);
                         } 
```

**Comment by jakope0003** [comment]
This is the case described in `String#toLowerCase` javadoc:

> Note: This method is locale sensitive, and may produce unexpected results if used for strings that are intended to be interpreted locale independently. Examples are programming language identifiers, protocol keys, and HTML tags. For instance, "TITLE".toLowerCase() in a Turkish locale returns "t\u0131tle", where '\u0131' is the LATIN SMALL LETTER DOTLESS I character. To obtain correct results for locale insensitive strings, use toLowerCase(Locale.ROOT).

**Comment by johnjaylward** [comment]
Thanks!

**Comment by stleary** [comment]
Please continue discussion as needed in #317
