### ISSUE TITLE
-0 parsed as string!!!

### ISSUE THREAD

**Issue by metwp** [stleary/JSON-java#318]
If I parse the following JSON string, the value of key "a" will be interpreted as an integer. So far, so good.
But unfortunately the value of key "b" will be interpreted as a string and NOT as a number (integer).

`
{
  "a": 0,
  "b": -0
}
`

Is there a possibility to avoid this behaviour, or do I'm something wrong?

**Comment by erosb** [comment]
What version of the library are you using? AFAIR it has been fixed already.

**Comment by johnjaylward** [comment]
this was fixed over a year ago unless there is a regression:
https://github.com/stleary/JSON-java/pull/188

**Comment by johnjaylward** [comment]
@metwp the -0 should return as a Double, not an Integer since java Integer does not maintain -0, it would flip to +0.

**Comment by metwp** [comment]
Thanks for your immediate answers.

**@erosb** 
Version of JSONObject.java is from 2014-05-03.

**@johnjaylward** 
It seams, I have to update the version.
Conversion to Double is also fine.
