### ISSUE TITLE
XML.toString outputs null strings rather than empty tags

### ISSUE THREAD

**Issue by mhubbard** [stleary/JSON-java#319]
This is a reopening of issue #129 

As described in issue #129 when converting JSON to XML using XML.toString() null values withing the JSON results in the string "null" since XML has no concept of null. Instead, empty tags should be utilised as per the spec https://www.w3.org/TR/xml11/#sec-starttags.

XML.toString looks like it even accounts for this on lines 576-579 when it appends and empty tag

https://github.com/stleary/JSON-java/blob/5ff8b4cb0891db3b234e76b912e81ca27b0502ad/XML.java#L576-L579

```java
} else if ("".equals(value)) {
    sb.append('<');
    sb.append(key);
    sb.append("/>");
} else {
```

My proposed solution is to change line 536 as shown below 

https://github.com/stleary/JSON-java/blob/5ff8b4cb0891db3b234e76b912e81ca27b0502ad/XML.java#L536

```java
while (keys.hasNext()) {
    key = keys.next().toString();
    value = jo.opt(key);
    if (value == null || JSONObject.NULL.equals(value)) { // line 536
        value = "";
    }
...
```

This way we account for JSONObject.opt(key) returning null when the key is null, and also for when value is the JSONObject.NULL object (when the value is null in the json).

I tested the outlined fix and get empty xml tags for json null values. With approval, I'd be happy to submit the fix.

**Comment by stleary** [comment]
@mhubbard, you can submit a pull request. The code change breaks 2 unit test now, in XMLTest.shouldHandleNullNodeValue() and JSONObjectTest.jsonObjectNullOperations(). The PR should make a case for why these tests should be modified or removed, and also why this won't break existing applications that might have been written to expect the "null" text value. No argument that the current transformation rules are arbitrary, and may have been better implemented, but the potential for breaking existing code needs to be considered before proceeding.
