### ISSUE TITLE
String parameter type receive a string without the double quotation marks

### ISSUE THREAD

**Issue by xalexslx** [stleary/JSON-java#325]
According to the official spec, a String should be between quotation marks (""). However, when I test against a string parameter without the quotation marks (eg: "key": MyValue instead of "key": "MyValue") it doesn't fail.

As a JSON parse it should follow the spec or allow me to configure if I want to be more or less strict about these things. There are any configuration that I'm missing to disable validation of non quoted strings?

![Json String spec](http://www.json.org/string.gif)

**Comment by johnjaylward** [comment]
This implementation is not a validator. According to the RFC mentioned in the README, the parser is allowed to be less strict. I don't see us changing the implementation to enforce quoted strings on input. 

Output from this library will always be valid JSON.

**Comment by stleary** [comment]
Good point, acknowledged that the lib allows text that is not strictly conforming to the spec. In this case, the behavior is called out in the application design. See the JavaDoc at the beginning of JSONObject.java. I have added a unit test to JSONObjectTest that documents the behavior. Will also update the wiki. The code won't be changed for the reasons cited in this thread.
