### ISSUE TITLE
org.json.XML.toJSONObject convertes .08 to a string (should be number)

### ISSUE THREAD

**Issue by tdnhome** [stleary/JSON-java#328]
I am using org.json.XML.toJSONObject to convert XML string to JSON string.  One of the XML input element with value of .08 was converted to ".08" which is a string but I am expecting 0.08 (a float).

Input:
  `<degree>.08</degree>`
Expected:
  `{"degree":0.08}`
Result:
  `{"degree":"0.08"}`

Thanks.

**Comment by MinnDevelopment** [comment]
As far as I know `.08` is not a valid json number according the definition. It might be possible to make an exception but if it isn't a valid json number it might as well be considered a String.

**Comment by tdnhome** [comment]
Hi,
Actually it is a valid JSON fraction data type according to the following references:
https://tools.ietf.org/html/rfc7159.html#section-6
  `frac = decimal-point 1*DIGIT`
https://www.tutorialspoint.com/json/json_data_types.htm
  `Fractions like .3, .9`
Thanks

**Comment by johnjaylward** [comment]
The RFC you specified actually indicates that it is not a valid JSON nubmer.
```
number = [ minus ] int [ frac ] [ exp ]
```

The `int` portion of the fraction is required. So, `.3` is invalid, while `0.3` is the correct way to represent the number.

**Comment by tdnhome** [comment]
I agreed that according to the RFC, .08 is not a valid float number but in reality it is.  The tutorialspoint even gives .03 as an example of a number and it is a valid XML float number.  Do you have any suggestion on how to handle this situation on our side?  I can't scan all values on the input XML as it is too expensive as we have millions of records to process in a small time window.  
Thanks.

**Comment by johnjaylward** [comment]
The "reality" for this project is the RFC. Anything that doesn't conform to that is not guaranteed to work.

XML processing poses many, many challenges for this project, the least of which is that everything in XML is a string. Trying to munge data that shows in XML into non-string JSON objects has caused many people to file bugs with this project. The reality is that no 1 solution will work for everyone.

A suggestion I would offer is that if you know your XML is well formedand large, would be to use [stax processor](https://softwarecave.org/2014/02/18/parse-xml-document-using-streaming-api-for-xml-stax/). When using that you would have a json object that you manually insert into as the XML is read.

For large XML documents the stax events would give you the most flexibility to processing your XML and placing the values into the correct objects with the correct types.

**Comment by johnjaylward** [comment]
In addition to the STAX solution I offered, would be to try and use that with the https://github.com/stleary/JSON-java/blob/master/JSONWriter.java class. The two used together should work reasonably well assuming you actually want JSON as your final output.

**Comment by tdnhome** [comment]
Thanks for the suggestion but that is a major change and our code is already in production.  I am looking for a hot/quick fix.  So, I am planning to clone the source and add || initial == '.'' on line 1543 of https://github.com/stleary/JSON-java/blob/master/JSONObject.java

`if ((initial >= '0' && initial <= '9') || initial == '-') || initial == '.')`

Thanks.

**Comment by johnjaylward** [comment]
that should work just fine

**Comment by tdnhome** [comment]
Thank you for looking into the issue.  I really appreciate it.

**Comment by stleary** [comment]
Closed since a workaround was identified (clone the source code and make a local change).
