### ISSUE TITLE
Parsing large numbers

### ISSUE THREAD

**Issue by neerup** [stleary/JSON-java#333]
Any chance **JSONObject.stringToValue(String string)**
Could parse strings with length > 14 as BigDecimal ?
When parsing to Double the value looses precision

Something like:
**if (string.length() > 14) {
  return new BigDecimal(string);
}**
before the line containing
**if (string.indexOf('.') > -1 || string.indexOf('e') > -1**
.....

**Comment by johnjaylward** [comment]
It was determined a while ago (2 years ago? #157 is a good example) that we did not want to change the parser to read in BigDecimals or BigIntegers.

I'm not sure if we want to re-investigate this. I do still agree that optimally we would want to parse larges values using BigDecimal or BigInteger.

**Comment by stleary** [comment]
Agreed that in a new implementation, full support for BigDecimal/BigInteger would be a reasonable design choice. But for now, in this implementation, prefer to stick with the 'put reasonable limits on things' guidance provided by the author in #157.
