### ISSUE TITLE
Opt performance enhancement

### ISSUE THREAD

**Issue by TheMatthew** [stleary/JSON-java#334]
Hi, I am currently using your lib to parse json logs that can be very large. I was wondering if it would be possible to make opts have an early failure. The reason I am asking is while 
<code>
try{
return getThing(string);
}catch(exception e){
return defaultValue;
}
</code>

is super readable, the throw catch exception is very slow. It would speed things up a lot having a simple check in front of the field to return if there is no field defined from the get go.

Thanks for such a great and easy to use lib.
:)

**Comment by johnjaylward** [comment]
the try/catch would need to stay in case of exceptions we don't actually plan on. But a pull request to enhance the opt* functions to be more performant would be welcome. Test cases should also be updated if needed in the separate test case project.

**Comment by stleary** [comment]
Sure, you can propose a pull request if you have a code change in mind. Please see the FAQ more guidance on submitting code changes (https://github.com/stleary/JSON-java/wiki/FAQ).  For performance enhancements, it will be helpful if you can provide some timing results to quantify the change.

**Comment by TheMatthew** [comment]
I am checking if I can contribute to the project. Until then, here is an example of code that can do it. It is published in open source under EPL so what you do with it is up to you. ;)

**Comment by guidomedina** [comment]
Hi all, that's a good catch, generally speaking relaying on exceptions for normal code flow is most likely to be slower than doing some checks like in this case if the value is absent.

Throwing exceptions will render stack traces and other things involved which will usually make the code slower by a factor, this can be easily proven, though might be unnecessary as it is a well known fact.

**Comment by guidomedina** [comment]
There are many articles about this but this is one example:

http://stackoverflow.com/questions/1546514/java-exceptions-as-control-flow

**Comment by johnjaylward** [comment]
@guidomedina please don't spam

**Comment by stleary** [comment]
This issue has been superseded by pull request #337, please post future comments there.
