### ISSUE TITLE
Upload to Maven Repository

### ISSUE THREAD

**Issue by Finomosec** [stleary/JSON-java#335]
The latest version in the Maven Repository (https://mvnrepository.com/artifact/org.json/json) is: 20160810
5 Days later some fixes were committed to the master that we need.
Could you please upload your latest version to the maven repository?

Or is there a way we can do this ourselves? I do not understand the deployment process of these maven repositories for "public" libraries.

**Comment by stleary** [comment]
A release can be put together later today. @bgehrels will you be available to update maven?

**Comment by stleary** [comment]
20170516 is released, pending Maven update.

**Comment by BGehrels** [comment]
Can't promise I can do it today,  but definitly in one of the next days

**Comment by stleary** [comment]
Whenever time permits, thanks!

**Comment by BGehrels** [comment]
@stleary could you please add a release tag to the unit test repo as well (with the same tag name)?

**Comment by stleary** [comment]
@BGehrels  should be available now

**Comment by BGehrels** [comment]
Release is deployed, should become publicly available soon.

**Comment by stleary** [comment]
Thanks sir!

**Comment by erosb** [comment]
@BGehrels are you sure you deployed it properly? It usually takes 3-4 hours for the crawler to pick up new releases, now 13 hours passed and the new version is still not available on maven central.

**Comment by BGehrels** [comment]
Sorry,  you were right,  forgot to press the final release button.  It is online now.

**Comment by Finomosec** [comment]
Thanks for your efforts. But i can still not see it here:
https://mvnrepository.com/artifact/org.json/json
Is this the wrong place or does it still need some time to arrive there?

**Comment by erosb** [comment]
@Finomosec mvnrepository.com is an external service and it always lags a bit behind maven central.

You can look up versions at [search.maven.org](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.json%22%20a%3A%22json%22)

Thank you @BGehrels for the deployment, I already upgraded in everit-org/json-schema

**Comment by johnjaylward** [comment]
the README specifies this location:
https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.json%22%20AND%20a%3A%22json%22

That is the master repository for maven artifacts.

**Comment by Finomosec** [comment]
Thanks a lot. I found it now and was able to download it via our build tool.
