### ISSUE TITLE
Reading large arrays progressively (iteration?)

### ISSUE THREAD

**Issue by TheMatthew** [stleary/JSON-java#339]
Hi,
If there is a json array larger than the available ram, is it possible to read it thought iteration instead of copying the whole array to RAM? I know it violates the "JSON is not meant to be ordered" principle, but it would be interesting to do in order to handle larger files.

**Comment by johnjaylward** [comment]
I believe you may be able to use the JSONTonkener with a reader while using the `nextValue` method. I've never had a usecase for it myself though.

**Comment by TheMatthew** [comment]
Thanks, I'll try that tonight.

**Comment by TheMatthew** [comment]
Non issue, it works as designed. ;)
