### ISSUE TITLE
Converting JSONObject to String and then back to JSONObject results in different object type

### ISSUE THREAD

**Issue by aosti** [stleary/JSON-java#342]
Hello
We are using your library for communicating between microservices, and the following behavior appeared:
At the sender side
JSONObject originalJSONObject = new JSONObject();
originalJSONObject.put("doubleValue", 5.0D);
System.out.println(originalJSONObject.get("doubleValue").getClass());
// Prints Double

However, when this string is received, the JSONObject generated has an Integer object, not a Double.
JSONObject receivedJSONObject = new JSONObject(JSONObject.valueToString(originalJSONObject));
System.out.println(receivedJSONObject.get("doubleValue").getClass());
// Prints Integer

Shouldn't it be also Double?

Thanks!

**Comment by johnjaylward** [comment]
The JSON Specification does not make distinctions between Integer and Double. When the JSON is written out 5.0 is written as 5

Original:
```json
{
"key" : 5.0
}
```

Written after parsing:
```json
{
"key" : 5
}
```

According to the JSON spec, these are the same JSON object.

If you need to guarantee a double for your code, then using the getDouble or optDouble method would be the proper way to do it.

**Comment by aosti** [comment]
I used the getDouble method and it worked. Thank you, John!
