### ISSUE TITLE
Having NullPointerException with JSONObject.getNames()

### ISSUE THREAD

**Issue by AoNoOokami** [stleary/JSON-java#343]
Hello,

I'm working on an academic project about WebServices. I have to import json data from an API and modify it before pushing it in an other web service that I created.

I need to remove English, German and Italian translations for nutrients elements. They are differents for each product in my db.

Here is a simplified "tree"of the json data I'm dealing with:

data [
    some other elements{}
    nutrients{
        nutrient 1{
            name_translations {de,en,fr,it}}
        nutrient 2{
            name_translations {de,en,fr,it}}
        nutrient 3{
            name_translations {de,en,fr,it}}
}
etc.]

And the code I'm using to remove de, en and it translations from nutrients elements in a JSONArray for each product:

`JSONObject nutrient = array.getJSONObject(i).getJSONObject("nutrients");
String[] names = JSONObject.getNames(nutrient);
printStringArray(names, i);

			//Remove translations for each grand-child (name_translations) of nutrients
			for(int j = 0; j < names.length; j++)
			{			
				JSONObject name_translations = nutrient.getJSONObject(names[j]).getJSONObject("name_translations");					
				name_translations.remove(de);
				name_translations.remove(en);
				name_translations.remove(it);
			}`

The point is that there is some empty nutrients in the data (nutrients{}). And because of that, I'v this NullPointerException when I'm printing and searching in the array called "names". I tried to check with a isNull() method, but there is no difference with no check.

Any advice?

Thanks!

**Comment by johnjaylward** [comment]
the getNames javadoc states that it returns an array, or null if there are no names and the code matches that. I personally don't like it, but that's the way it was made.

The correct way to call the function would be like this:
```java
if(names!=null){
		//Remove translations for each grand-child (name_translations) of nutrients
		for(int j = 0; j < names.length; j++)
		{			
			JSONObject name_translations = nutrient.getJSONObject(names[j]).getJSONObject("name_translations");					
			name_translations.remove(de);
			name_translations.remove(en);
			name_translations.remove(it);
		}
}
```

**Comment by AoNoOokami** [comment]
Yes, it works now.

Many thanks :-)
