### ISSUE TITLE
Garbage at the end of a file ignored?

### ISSUE THREAD

**Issue by pgeadas** [stleary/JSON-java#349]
Hi there!

So while using a library that depends on this one for parsing, I found out that if a file has a valid JSON string at the beginning, no matter how much garbage the file might have after, it will be ignored.

Is this how it is supposed to work? I opened a issue at that project, but the owner said that it must be a problem with the parser (or not, since it might be done on purpose).

Just wanted to clarify this, since I could not find an answer by my own.

Thank you in advance!

**Comment by stleary** [comment]
I think this issue was addressed in https://github.com/stleary/JSON-java/pull/102. There is a pretty good explanation of the reasoning in the comments. Let me know if you have any questions or concerns about it.

**Comment by pgeadas** [comment]
Yes, I see now! Thank you very much for pointing that to me.
