### ISSUE TITLE
Remove "The Software shall be used for Good, not Evil" from license

### ISSUE THREAD

**Issue by xtreye** [stleary/JSON-java#353]
This statement is evil itself because eventually prevents from using the library in Spring Boot, a mainstream Java framework: https://github.com/spring-projects/spring-boot/issues/9248

Here is the answer from the author of rapidjson used: https://github.com/miloyip/rapidjson/issues/1000#issuecomment-311892586

You do not need the line as long you do not bundle the tests.

**Comment by xtreye** [comment]
Yes I read the FAQ but I do not think this is how open source should work. Collaboration is everything.

**Comment by johnjaylward** [comment]
Just stop being evil...

**Comment by stleary** [comment]
@xtreye Your commitment to open source and collaboration is appreciated and shared. The terms of the JSON-Java library license were set by the original author. My agreement to manage this project does not include making changes to the license text.
