### ISSUE TITLE
Management of duplicate keys / Overloading of your code is difficult

### ISSUE THREAD

**Issue by liar666** [stleary/JSON-java#363]
Hi,

I was trying to parse JSON code from the following page with your code:
https://academic.microsoft.com/api/browse/GetEntityDetails?entityId=2145790759
It raises a JSONException due to the presence of duplicate keys.

**First**, let me suggest that it would have been cool if the JSONException would **not** have been a **generic** Exception, but rather split into specialized Exceptions so that we (developers using your code) would be able capture&treat a, e.g., JSONDuplicateKeysException in a different manner than a, e.g., JSONInvalidFormatException, etc. 

**Second**, it would have been great if we (your lib users) would have been able to control the behaviour of the code in case of duplicate keys. I know the JSON specifications do not allow that, but the problem is that such cases **do** exist in the nature (sse M$ example above). Following examples given at https://stackoverflow.com/questions/19001238/remove-duplicates-from-a-json-string-in-java I would have loved to have 3 possibilities : 
1 - reject any duplicate
2 - reject duplicates with different values
3 - accept all duplicates (eventually with variants: a) keep only the first value b) only last value)  

**Third**, I tried to implement that behaviour using the overloading proposal found in the SO solution cited above. Unfortunately, it seems a few best practices are not respected in your code (sorry for the direct critics - put it on the English language not been my native one - I thank you a lot for having the written above all) and that makes my work very difficult. 
The problem lies in the fact that your constructors, instead of beeing very short and simply calling 'external' methods, are doing all the job themselves.
As a consequence, when I want to add a parameter to the constructor, I would have written: 
```
    private boolean ignoreAll;
    public JSONObjectIgnoreDuplicates(String json, boolean argIgnoreAll) throws JSONException {
        ignoreAll = argIgnoreAll;
        // do same job as same constructor in JSONObject(String)
    }
```
Unfortunately, `"do same job as same constructor in JSONObject(String)"` would be `super(json)` which must be first line in the `JSONObjectIgnoreDuplicates`. As a consequence, a solution would be to replicate the code in the constructor, i.e. 
`this(new JSONDupTokener(json))`
which has exactly the same problem. Apart from continuing to replicate each of your methods, this is a dead-end solution.

Another solution would be to do something like:
```
JSONObjectIgnoreDuplicates jdup = new JSONObjectIgnoreDuplicates();
jdup.setIgnoreAll(true);
jdup.parse(json);   // i.e. do same job as same constructor in JSONObject(String);
```
Unfortunately, the code for parse() is only present in the constructor `JSONObject(JSONTokener x)`, so cannot be called from outside :{ and I can't call the constructor sdince I've already built the `JSONObjectObjectIgnoreDuplicates`... So again, a dead-end solution :{

So apart from copy-pasting your whole `JSONObject(JSONTokener x)` (whichi would be very unmaintainable...) (or maybe using anonymous classes as suggested by a friend), I don't see any solution.

PS: if I can find time this week, I'll try to make a pull request to solve my remarks 2) and 3), as it would be better/easier if everything was directly in the original code or at least a fork...

**Comment by johnjaylward** [comment]
If you could take look at the [wiki](https://github.com/stleary/JSON-java/wiki) and more specifically the [FAQ](https://github.com/stleary/JSON-java/wiki/FAQ), that's a good place to start for contributions.

However, the following points should be noted:
- This is a reference library meant to show one way to parse and generate JSON texts
- This is not a library meant to show best development practices (although Sean and I do try to take that into consideration on our maintenance requests now that he is the primary maintainer)
- In general, this library is not meant to be extended by inheritance. Most classes in this library do not support that nicely at all (see the Tokeners).
- The usual response to "I want to be able to do something that isn't in the spec" is "Fork the project"

Overall I can't disagree with any of your criticisms on the design, but I'm pretty sure that the last two are out of scope for this project.

The one item I could see us using in the project is your first point, using subclasses of JSONException instead of JSONException directly. We could do this and not change the public API.

**Comment by johnjaylward** [comment]
Also, looking at your initial link with the JSON source you are trying to parse, it doesn't look like a valid JSON text. The first token is a `{` but then the text ends with no closing tag.

Even if you override or fork the project to support duplicates, parsing this text will fail.

**Comment by johnjaylward** [comment]
the last option for your second point on handling duplicate:
> 3 - accept all duplicates (eventually with variants: a) keep only the first value b) only last value)

I would add a third option to that which would use `JSONObject.accumulate` to merge the values into an array.

in your source text you have a structure that looks something like this:
```json
{
  "key": [1,2,3],
  "key": [5,6,7]
}
```

parsing with `accumulate` would generate a final object that looks like:
```json
{
  "key": [1,2,3,[5,6,7]]
}
```

**Comment by liar666** [comment]
Hi,

Thanks a lot for all your feedback.

Indeed, the best thing would be for me to clone the project. I'll do that and try to take into account all your very interesting comments.

Thanks again

**Comment by liar666** [comment]
Hi again,

Another thing that could be improved is the code refactoring: you do twice the same job in JSONObject(Tokener) and in putOnce(): extracting value, checking if it is a dup key and storing it in `this`.

**Comment by johnjaylward** [comment]
Yes, we decided not to use putOnce because that lead to flow control by exception and also caused problems for the syntax error message when propagating up the stack. 

That could be mitigated if we used an explicit duplicate key exception and an explicit syntax exception.
