### ISSUE TITLE
Preserving insertion order of keys on JSONObject

### ISSUE THREAD

**Issue by mombiela** [stleary/JSON-java#37]
Hello,

I know that JSON keys are unordered, but this make the transformation from JSON to XML unreliable, especially if you use xsd validation on the result. I suppose that some other formats are affected too.

I think that preserve the insertion order is a good improvement, with little impact on performance.

It should be as easy as replace java.util.HashMap with java.util.LinkedHashMap on JSONObject.

Thank you very much.
Joan

**Comment by ygopala** [comment]
Is the order of JSON Array [] maintained when we convert from JSON to XML?
