### ISSUE TITLE
StackOverflowError when creating a new JSONArray

### ISSUE THREAD

**Issue by agouz** [stleary/JSON-java#372]
Hello Sean,
Thanks for this great library.
I have one issue when trying to initialise a JSONArray object and the input is simply "[". The jvm crashes with StackOverflowError.

simply try to run this: new JSONArray("[");

version used: 20171018

Thanks again :)

**Comment by johnjaylward** [comment]
I can confirm this behavior

**Comment by stleary** [comment]
Continued discussion in #373
