### ISSUE TITLE
API changes report for JSON In Java

### ISSUE THREAD

**Issue by lvc** [stleary/JSON-java#374]
Hi,

I'd like to share report on API changes and backward compatibility for the JSON-Java library: https://abi-laboratory.pro/java/tracker/timeline/json-java/

BC — binary compatibility
SC — source compatibility

The report is generated by the https://github.com/lvc/japi-tracker tool for jars at http://central.maven.org/maven2/org/json/json/. The tool checks for API changes according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library.

Thank you.

![json-java-1](https://user-images.githubusercontent.com/1517837/32264428-af8e36e4-beef-11e7-9e40-33be7aff03b5.png)

![json-java-2](https://user-images.githubusercontent.com/1517837/32264427-af72a186-beef-11e7-879c-dbb621a176cd.png)

**Comment by johnjaylward** [comment]
Is there a way we can trigger reports upon merge, or run them on pull requests before merge?

**Comment by lvc** [comment]
> Is there a way we can trigger reports upon merge, or run them on pull requests before merge?

It can be run daily on a snapshot jar for the library. Is it created somewhere (e.g. https://oss.sonatype.org/content/repositories/snapshots/)?

I'll setup the tracker quickly if you'll add the snapshot jar.

Thank you.

**Comment by stleary** [comment]
@lvc Thanks for the report, it looks good and visibility into changes in the API is welcome. External jars cannot be added to the project at this time, so if you can think of another way to proceed, let us know.

**Comment by stleary** [comment]
Looks like there is no path forward at this time. Sorry, this looks like a valuable enhancement.
