### ISSUE TITLE
False positives in JSONObject.similar() and JSONArray.similar()?

### ISSUE THREAD

**Issue by enoes** [stleary/JSON-java#379]
I'm afraid the for-loops in the above mentioned methods are breaking to soon if only one similarity was detected, see line 1487 in JSONObject.java and 1292 in JSONArray.java. Or did I overlook something?

**Comment by johnjaylward** [comment]
Yes, you did. Those lines are determining if the 2 references in memory are the same. If they are, there is no way their child objects could differ.

* https://github.com/stleary/JSON-java/blob/master/JSONObject.java#L1847
* https://github.com/stleary/JSON-java/blob/master/JSONArray.java#L1292

**Comment by johnjaylward** [comment]
wait, you may be correct. @stleary , let me make a test case just to confirm. it's possible that those `return`s should be `break`s instead

**Comment by stleary** [comment]
Issue resolved.
