### ISSUE TITLE
JSONObject.put(String, Object) doesn't store null value

### ISSUE THREAD

**Issue by RemonSinnema** [stleary/JSON-java#382]
According to the [JSON specification](https://www.json.org/), a JSON value may be `null`. However, `JSONObject.put(String, Object)` doesn't store this.

It is therefore not possible to make a distinction between the object not having a given key and the object having `null` for the value of that key.

This decision looks deliberate in the code, but it is wrong nonetheless, IMHO.

**Comment by johnjaylward** [comment]
This library has a distinct JSONObject.NULL constant that is used to store JSON `null` values. It is deliberate. The Java `null` value is treated in this library like JavaScript `undefined`. 

While not part of the specification, I can't see us undoing this as it would break backwards compatibility.

**Comment by RemonSinnema** [comment]
Thanks, I can work around my issues by using `JSONObject.NULL`.

**Comment by leonardofel** [comment]
I fixed this "feature" and created this project https://github.com/leonardofel/JSON-java-put-null-fix


making the following code bellow possible:
```
    String v = null;
    JSONObject j = new JSONObject().put("myPreciousNull", v);
    System.out.println(j.toString());
```

prints:
```
    {"myPreciousNull":null}
```
just works !!!
