### ISSUE TITLE
Error when parsing json from database

### ISSUE THREAD

**Issue by xeu100** [stleary/JSON-java#384]
So I have a json in a string from an online database. I have already come up with why it does this, I just can't fix it. It does it because there is no \ before the quotations to my knowledge. Since the web database gets an automated input from a user submission form, I am wondering if there is a way I can add the \'s with Java.

Exception in thread "main" java.lang.NullPointerException
	at java.io.StringReader.<init>(Unknown Source)
	at org.json.JSONTokener.<init>(JSONTokener.java:94)
	at org.json.JSONObject.<init>(JSONObject.java:357)
	at API.main(API.java:6)

**Comment by johnjaylward** [comment]
do you have a sample input that we can see as a reference?

**Comment by xeu100** [comment]
https://hastebin.com/afolisipiz.java

**Comment by xeu100** [comment]
The whole thing so far.

**Comment by johnjaylward** [comment]
So your example input is this? :
```json
{
  "id":"1",
  "uuid":"c4f5e170e4584158b758df6559a9511a",
  "settings":"{\"kiloName\":\"DevMazing\",\"kiloTheme\":0}",
  "addons":"{}"
}
```

**Comment by xeu100** [comment]
Yes

**Comment by johnjaylward** [comment]
I don't see any errors using this test case:

```java
    @Test
    public void jsonAsString() {
        final String input = "{\n" + 
                "  \"id\":\"1\",\n" + 
                "  \"uuid\":\"c4f5e170e4584158b758df6559a9511a\",\n" + 
                "  \"settings\":\"{\\\"kiloName\\\":\\\"DevMazing\\\",\\\"kiloTheme\\\":0}\",\n" + 
                "  \"addons\":\"{}\"\n" + 
                "}";
        JSONObject obj = new JSONObject(input);
        assertNotNull(obj);
        assertEquals("{\"kiloName\":\"DevMazing\",\"kiloTheme\":0}",obj.optString("settings"));
    }
```

**Comment by xeu100** [comment]
The problem is I am getting the data from a database

**Comment by johnjaylward** [comment]
that shouldn't matter... can you post an actual string that is causing the issue?

**Comment by xeu100** [comment]
"{"id":"1","uuid":"c4f5e170e4584158b758df6559a9511a","settings":"{\"kiloName\":\"DevMazing\",\"kiloTheme\":0}","addons":"{}"}"

**Comment by johnjaylward** [comment]
It looks like you just have bad data in your database. I doubt there is any good way to fix that in an automated fashion unless every record is wrong in the same way.

If you can you should have your db admin try to fix it, and correct whatever process is putting those in the database so it doesn't happen again

**Comment by xeu100** [comment]
Its using Php to encrypt it.

**Comment by johnjaylward** [comment]
My point is that the original data is bad. You need to correct whatever process is putting that bad data in so it doesn't happen anymore.

How you fix the existing data is up to you. You may be able to use a database stored procedure, or you can use php, or you can use java.

Whatever you use to correct the existing data has to treat it as plain strings and not json. A regex with replacement groups would be my first option, but if the data is irregular, then that won't work well.

**Comment by stleary** [comment]
Is not the bad data pretty consistent? Every {  is preceded by an extra double quote, and every } is followed by an extra double quote. Otherwise the data seems OK.  Can't you take out those extra quotes before parsing?  

From the way the examples are given I can't quite tell whether each string also has an extra double quote at start and end.

**Comment by xeu100** [comment]
None of you are getting it, the problem is I have data, I use json_encode in PHP to encode it. Then I enter it into a database. Using a GET request and an API, it gets the JSON. The problem is Java doesn't like the quotations.

**Comment by stleary** [comment]
This is not the best forum to debug your code. Recommend you post to StackOverflow or similar. Feel free to post a link to the discussion here.

**Comment by johnjaylward** [comment]
I'm afraid we do get it. Your php or database code is buggy and either encoding or decoding bad JSON documents. It has nothing to do with this library.
