### ISSUE TITLE
org.json.JSONException: JSON does not allow non-finite numbers

### ISSUE THREAD

**Issue by sivaramansv** [stleary/JSON-java#385]
I have the following section in my XML document:
`<dataId dt:dt="string">a98b174b86b54d7bb007d665382821d3</dataId>`
and I am using the jar file json-20171018 for converting the XML document to JSON.

I am getting the following error:
org.json.JSONException: JSON does not allow non-finite numbers.
at org.json.JSONObject.testValidity(JSONObject.java:1261)

It has been told that it has been fixed, but I am getting the same error. Is there any workaround for this?
https://github.com/stleary/JSON-java/issues/27

**Comment by johnjaylward** [comment]
this test passes:
```java
    /**
     * see https://github.com/stleary/JSON-java/issues/385
     */
    @Test
    public void testNumberConversion() {
        String xmlStr = "<dataId dt:dt=\"string\">a98b174b86b54d7bb007d665382821d3</dataId>";
        JSONObject jsonObject = XML.toJSONObject(xmlStr);
        assertTrue("jsonObject should not be empty", jsonObject.length() != 0);
        assertNotNull(jsonObject.optJSONObject("dataId"));
        assertEquals("string",jsonObject.getJSONObject("dataId").optString("dt:dt"));
        assertEquals("a98b174b86b54d7bb007d665382821d3",jsonObject.getJSONObject("dataId")
                .optString("content"));
    }
```

Are you sure that is the section of your document that is causing the problem?

**Comment by sivaramansv** [comment]
Yes, you are right. It works with this string. Do you know what kind of input might possibly throw this exception? I have about 1 million XML files that have these kinds of strings.

**Comment by johnjaylward** [comment]
It would be something that causes under or overflow of a `double`. so some string that looks like:
`98623497634589798e134987345983697862354987`

To parse all values as strings and post-process them, you should install call the XML parser like this:
```java
    /**
     * see https://github.com/stleary/JSON-java/issues/385
     */
    @Test
    public void testNumberConversion2() {
        String xmlStr = "<dataId dt:dt=\"string\">a98b174b86b54d7bb007d665382821d3</dataId>";
        JSONObject jsonObject = XML.toJSONObject(xmlStr, true);
        assertTrue("jsonObject should not be empty", jsonObject.length() != 0);
        assertNotNull(jsonObject.optJSONObject("dataId"));
        assertEquals("string",jsonObject.getJSONObject("dataId").optString("dt:dt"));
        assertEquals("a98b174b86b54d7bb007d665382821d3",jsonObject.getJSONObject("dataId")
                .optString("content"));
    }
```


note the second parameter is `true`. this indicates to the parse to not try to convert values fond in the XML files into booleans or numbers. it will instead keep the raw strings. so if you have an XML like this:

```xml
<root>
   <data>5</data>
   <data>true</data>
</root>
```

your processed JSON would look like:
```json
{
 "root" : {
    "data" : [{
      "content" : "5"
      }, {
      "content" : "true"
    }]
  }
}
```

**Comment by sivaramansv** [comment]
public String convert(Text input) {
		if (input != null) {
			return input != null ? XML.toJSONObject(input.toString(), true).toString() : null;
		}
		return input;
	}

Following is my stack trace:
 java.lang.NoSuchMethodError: org.json.XML.toJSONObject(Ljava/lang/String;Z)Lorg/json/JSONObject;
        at com.intel.mfg.oasys.OasysTextJsonConverter.convert(OasysTextJsonConverter.java:21)
        at com.intel.mfg.oasys.OasysTextJsonConverter.convert(OasysTextJsonConverter.java:1


Do you know which library or version of jar file I need to use?

**Comment by johnjaylward** [comment]
This has been in the library since the [20160807 release](https://github.com/stleary/JSON-java/releases/tag/20160807). Did you compile your own version, or did you download from Maven?

The maven builds are located here: https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.json%22%20AND%20a%3A%22json%22

Also make sure that no other dependencies in your project have an older copy of the JSON library.

**Comment by sivaramansv** [comment]
Yes, it looks like I had an older copy of the JSON present in the project. So, I updated it to the latest version of jar file : json-20171018.jar and it worked!! Thank you.

**Comment by johnjaylward** [comment]
you are welcome.
