### ISSUE TITLE
Make possible an ordered/sorted map

### ISSUE THREAD

**Issue by gabrielstelmach** [stleary/JSON-java#387]
Hello there,

first of all, this API is really great! Congratulations on your great work here.

I would like to ask a way to get the JSON string ordered/sorted as the Map used in the constructor. I realize the use of HashMap instead of LinkedHashMap on pieces of code, so I guess that all effort needed is to change the implementation of Map.

Kind regards,
Gabriel

**Comment by erosb** [comment]
You are about the 100th requesting it, but I'm afraid still [nope](https://github.com/stleary/JSON-java/wiki/FAQ#why-isnt-ordering-allowed-in-jsonobjects).

**Comment by gabrielstelmach** [comment]
Thank you for this explanation. I see now why. Anyway, good job!

**Comment by stleary** [comment]
@gabrielstelmach Thanks for your kind words. 
Users who need ordered JSON objects should consider forking the project and making the necessary changes.
