### ISSUE TITLE
conflict with android-19's org.json

### ISSUE THREAD

**Issue by dfghj44444** [stleary/JSON-java#391]
as the title,android-19 has a org.json without org.json.xml,So adter I import this org.json and the xml,it has a conflict that cause jsonObject.StringtoValue() crash

**Comment by johnjaylward** [comment]
This is known. See the FAQ

**Comment by dfghj44444** [comment]
where is the FAQ,cant find it in readme

**Comment by johnjaylward** [comment]
https://github.com/stleary/JSON-java/wiki/JSON-Java-for-Android-developers
