### ISSUE TITLE
How to report a potential security issue?

### ISSUE THREAD

**Issue by datallah** [stleary/JSON-java#396]
I have discovered something that I think would be best to disclose privately.
Please let me know how you would prefer me to do that.
Thanks.

**Comment by stleary** [comment]
Feel free to post it right here, no secrets are kept in this project.

**Comment by datallah** [comment]
It seems that my issue has already been reported and fixed - #388.

I'll keep the policy in mind if I have anything else.

Sorry that I missed the other issue in my initial search.

**Comment by johnjaylward** [comment]
@stleary it may be a good idea to roll up another release soon. There have been some bigger changes since the last release and it's been over 3 months.

https://github.com/stleary/JSON-java/compare/20171018...master
