### ISSUE TITLE
Improvement: XML toJSONObject(Reader reader)

### ISSUE THREAD

**Issue by foldvari** [stleary/JSON-java#399]
Currently converting XML to JSON can be done using toJSONObject(String string) method. In case of huge XML-s the need to convert them to string is a big limitation. As JSONTokener is working with a Reader anyway, introducing a new method in the XML class which accepts a Reader is a very simple, risk free change which boosts the usability of the library.
I already made the necessary changes, I just need right to create a pull request.

**Comment by stleary** [comment]
Everyone is allowed to create pull requests, you don't need permissions. For more information see https://github.com/stleary/JSON-java/wiki/FAQ

**Comment by foldvari** [comment]
Pull request has been created.
