### ISSUE TITLE
JSON is not correctly parsed to XML when a key is "content"

### ISSUE THREAD

**Issue by LukeButtersFunnelback** [stleary/JSON-java#407]
It seems when trying to parse json with key of "content" e.g.
```
"content":{foo: "bar"}
```
means something special, where it just encodes the entire value of `"content"` into one XML element.
this is done at:
https://github.com/stleary/JSON-java/blob/master/XML.java#L601

A comment exists saying:
```
// Emit content in body
```
Which doesn't explain why.

Why is it doing this? Can it be disabled or at least can we have option to disable it?

**Comment by stleary** [comment]
This is an open issue tracked by #394. A fix has been proposed and accepted in principle. Please continue the discussion in that issue.
