### ISSUE TITLE
XML.toJSONObject

### ISSUE THREAD

**Issue by lucgotthard** [stleary/JSON-java#408]
The conversion with XML.toJSONObject(XmlString) convert attribute with the hex value from E0 to E9 to 0.0
eg :   <LongUnsigned Value="00E8" />
become
"LongUnsigned": [
   {"Value": 0.0}
  ]
The full XML file and converted JSON are in the linked text file.

To note that when using XML.toJSONObject(XmlString, true), the conversion work fine.
 
[XmlToJsonExample.txt](https://github.com/stleary/JSON-java/files/1797008/XmlToJsonExample.txt)

**Comment by johnjaylward** [comment]
Yes. That is why we have the "keep strings" option. This is working as designed.

**Comment by lucgotthard** [comment]
Sure thing, that's my bad. I just made the connection that 00E8 will be understood as an number with exposant.
