### ISSUE TITLE
BigDecimal invalid support

### ISSUE THREAD

**Issue by dybuk87** [stleary/JSON-java#413]
Hi,
I think BigDecimal support is misleading in current version, currently  json :
new JSONObject(" { \"value\" : 34300000000000000000000000.14 }").getBigDecimal("value").toPlainString()
will return 34300000000000000000000000 instead of correct value 34300000000000000000000000.14

I found in code 

// if we want full Big Number support this block can be replaced with:
//  return stringToNumber(string);
  if (isDecimalNotation(string)) {

After uncommenting this line  support is valid and I believe this should be default instead of current one because there is a lot of situation where you need full precision like money amount, or at least there should be some configuration for json parser.

**Comment by johnjaylward** [comment]
I'll take a look at this

**Comment by johnjaylward** [comment]
@stleary , while this is "working as designed", I do agree with @dybuk87 that we should consider changing the default handling of numbers. What's happening in this example is that the `stringToValue` parser is always using a `Double` for the representation. That is causing the value to be truncated here.

Let me know your thoughts.

**Comment by stleary** [comment]
@johnjaylward Haven't looked at the code yet, but this sounds reasonable given that BigNumber is a recent enhancement.

**Comment by urfuchs** [comment]
There is a difference between getBigDecimal and optBigDecimal.

    JSONObject json = new JSONObject("{ \"key\" : 72.35 }");
    BigDecimal bd1 = json.getBigDecimal(„key“);
    BigDecimal bd2 = json.optBigDecimal(„key“, null);
    System.out.println(bd1);
    System.out.println(bd2);

prints:

    72.35
    72.349999999999994315658113919198513031005859375

Why is there a difference? 

getBigDecimal converts the double to a String and than to a BigDecimal: 
    `new BigDecimal(Double.valueOf(72.35).toString())`
optBigDecimal converts the double directly to BigDecimal: `new BigDecimal(Double.valueOf(72.35))`

**Comment by johnjaylward** [comment]
@urfuchs can you open a new issue for this? it's a different problem than the original request

**Comment by urfuchs** [comment]
> 
> 
> There is a difference between getBigDecimal and optBigDecimal.
> 
> ```
> JSONObject json = new JSONObject("{ \"key\" : 72.35 }");
> BigDecimal bd1 = json.getBigDecimal(„key“);
> BigDecimal bd2 = json.optBigDecimal(„key“, null);
> System.out.println(bd1);
> System.out.println(bd2);
> ```
> 
> prints:
> 
> ```
> 72.35
> 72.349999999999994315658113919198513031005859375
> ```
> 
> Why is there a difference?
> 
> getBigDecimal converts the double to a String and than to a BigDecimal:
> `new BigDecimal(Double.valueOf(72.35).toString())`
> optBigDecimal converts the double directly to BigDecimal: `new BigDecimal(Double.valueOf(72.35))`

moved to #438

**Comment by stleary** [comment]
Working as designed.

**Comment by borgogelli** [comment]
Same code, but the output for me is:
```
72.349999999999994315658113919198513031005859375
72.349999999999994315658113919198513031005859375
```
I use the 20200518 version

**Comment by johnjaylward** [comment]
@borgogelli , I'm not sure I understand what action you are expecting from your comment. Are you confirming the fix worked, or do you expect the behaviour to be different?

**Comment by borgogelli** [comment]
Hi @johnjaylward , both the things. First the output of my code is different from the code posted by @urfuchs . And then I have expected the result to be 72.35

**Comment by johnjaylward** [comment]
The recommendation when using the `*BigDecimal` functions is to specify your scale. We purposefully expose the full `double` with  rounding errors due to use cases like this:

```java
double myDouble = someComplexCalculation();
JSONObject jo = new JSONObject();
jo.put("myDouble", myDouble);
// ... some other code
someFunction(jo.getBigDecimal("myDouble"));
```
The old method of using the string value of the underlying double did preserve the value when parsed from a string, but it lost some complexities if the double was originally stored from a calculation.

PR #453 basically solves the issue for both use cases by preserving the textual representation when parsing (by using a `BigDecimal` for storage), but allowing complex calculations to be stored as a double or float.

Until #453 is accepted, the expected use would be to do something like (use `setScale`):
```java
double myDouble = someComplexCalculation();
JSONObject jo = new JSONObject();
jo.put("myDouble", myDouble);
// ... some other code
someFunction(jo.getBigDecimal("myDouble").setScale(5, RoundingMode.ROUND_HALF_EVEN));
```
