### ISSUE TITLE
Escape character not parsed

### ISSUE THREAD

**Issue by pbcornelius** [stleary/JSON-java#415]
Even though \\\\ are specified as escape characters in the tokener, the String `{"key":"\\""}` (`{\"key\":\"\\\\\"\"}` with Java escapes) can't be parsed. Why not?

**Comment by MinnDevelopment** [comment]
The proper json would be `{"key":"\""}` (`"{\"key\":\"\\"\"}"`)

**Comment by johnjaylward** [comment]
If you actually want the JSON string to contain both a \ and a ", then the proper JSON String would look like this:
```json
{
"key":"\\\""
}
```

or in java:
```java
final String jsonString = "{\"key\":\"\\\\\\\"\"}"
```

**Comment by philippbc** [comment]
Fantastic support, thanks guys!
