### ISSUE TITLE
Bug in JSONArray?

### ISSUE THREAD

**Issue by thamizh0** [stleary/JSON-java#420]
```
             String xmlRawString = "[{},";
            JSONArray object = new JSONArray(xmlRawString);
```

Constructing JSONArray with Malformed Strings (The ones without ']') seem to stuck in an infinite loop and throw OutOfMemory Exception.

**Comment by johnjaylward** [comment]
Are you using the latest version?

**Comment by thamizh0** [comment]
It seems I am in a old version. Works fine in the current version. Can you point me towards the bugfix commit of this issue?

**Comment by johnjaylward** [comment]
https://github.com/stleary/JSON-java/pull/373

**Comment by thamizh0** [comment]
Thanks!
