### ISSUE TITLE
Can a set of unit tests be written that ensure android compatibility?

### ISSUE THREAD

**Issue by stleary** [stleary/JSON-java#422]

**Comment by johnjaylward** [comment]
It would be difficult for sure... The basics of it is to not use new API methods in the non-shared classes. When I first did this, I basically did the following steps manually:
* pulled down the Android source code
* made sure the JSON-Java source code was up to date
* copied the Android source over the JSON-Java source
* Looked for any compilation errors.
* Fixed any compilation errors
* Reverted the changes to the classes with the same names (i.e. JSONObject, JSONArray, etc)
* Recompiled to make sure there were no errors

To do this in some automated fashion, we would need to rework the project structure into a "core" and "extension" packages and JAR them up separately. Then for the android tests, use our extensions jar and one of the android.json jar clones.

**Comment by stleary** [comment]
For now, this can be a manual process. From where do you recommend to get the Android source?

**Comment by johnjaylward** [comment]
you can use the "SDK" which comes with an editor and lets you download the android SDKs pretty easy. I can't remember if source is included or not. That is located here: https://developer.android.com/studio/

The actual way I did it was to download the source (which is very large) by following the directions here: https://source.android.com/

Once downloaded, the Android JSON code is located under `android-root/libcore/json`

**Comment by stleary** [comment]
Thanks sir!

**Comment by stleary** [comment]
Not a priority at this time.
