### ISSUE TITLE
Unequal or confusing conversion from XML.toJSONObject

### ISSUE THREAD

**Issue by adamski52** [stleary/JSON-java#423]
I've just started using this library and I came across a strange behavior.  Maybe I'm just doing it wrong or have an invalid expectation, but I was not able to find any information about this specific issue.

**Problem:**
When using `XML.toJSONObject(some xml string)`, where the XML string has a set of items inside of a single element, the item which gets made in to an array is different than the item containing those items in the XML.  This seems to happen infinitely deep.

Specifically, an xml file turned to a string via `readAllBytes` => `toString` (inclusive of line breaks -- unix type if that matters) of this pattern:

**/path/to/file.xml**:
```
<?xml version="1.0" encoding="UTF-8"?>
<things>
    <thing>
        <id>1</id>
        <name>thing one</name>
    </thing>
    <thing>
        <id>2</id>
        <name>thing two</name>
    </thing>
</things>
```

Will be turned into JSON of this pattern:

```
{
    "things": {
        "thing": [{ // why did 'thing' become the array?  things (plural) should be the array, containing multiple representations of thing (singular).
            "id": 1,
            "name": "thing one"
        }, {
            "id": 2,
            "name": "thing two"
        }]
}
```

**Note that they are not the same:**  The XML node named `things` went from an XML node containing multiple XML nodes named `thing` to a JSON object named `things` contains a single JSON object named `thing`, which contains multiple anonymous JSON objects of similar shape to the XML node named `thing`.

The expected JSON, at least for me, would be:
```
  {
    "things": [{
            "id": 1,
            "name": "thing one"
        }, {
            "id": 2,
            "name": "thing two"
        }]
}
```

Other relevant bits:
* Java 1.8 (1.8.0_152)
* macOS High Sierra
* IntelliJ (CE) (2018.1.4)

The below should recreate the above issue.  Pass it a filename via CLI or through IDE e.g. `java -jar target/wellthatsstrange-1.0-SNAPSHOT.jar /path/to/some/file.xml`.

Please note, I've removed some error checking and such to keep it more concise.  It will blow up if, for example, you don't provide a file.

**/src/main/java/somepackage/WellThatsStrange.java**:
```
package somepackage;

import org.json.JSONObject;
import org.json.XML;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class WellThatsStrange {

    public static void main(String[] args) {

        String xmlFilename = args[0];

        String xmlContent;
        JSONObject jsonObject;

        try {
            xmlContent = new String(Files.readAllBytes(Paths.get(xmlFilename)));
            System.out.println(xmlContent); // correct

            jsonObject = XML.toJSONObject(xmlContent);
            System.out.println(jsonObject.toString(4)); // wrong?
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

```

**pom.xml:**
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.somepackage</groupId>
    <artifactId>wellthatsstrange</artifactId>
    <version>1.0-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.2.RELEASE</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20180130</version>
        </dependency>
    </dependencies>

    <properties>
        <java.version>1.8</java.version>
        <start-class>somepackage.WellThatsStrange</start-class>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

```

I admit that i do see how the array moving to where it does can make sense, but it seems unintuitive to me.

**Comment by johnjaylward** [comment]
XML is a document structure markup that is bastardized to send data. JSON is a data exchange format that is mostly used how it's supposed to be, but will sometimes be bastardized to try and represent ordered documents.

The 2 generally don't mix as they do not have true overlapping problem domains that they are trying to solve.

In this case, you are trying to pull a document into a data exchange format. This means they will not look identical. The implementation of the XML conversion functions will not be changing.

For your actual "problem" that you are seeing, It's do to XML not having an array type itself (and it shouldn't). Again XML is a document structure. For example, this is a valid XML document:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<things>
    <thing>
        <id>1</id>
        <name>thing one</name>
    </thing>
    <bob>Hi, I am bob</bob>
    <thing>
        <id>2</id>
        <name>thing two</name>
    </thing>
</things>
```

If I were to use your "expected" format for the array, where would the `bob` element be placed? Instead, with the JSON structure that we use, this can now be represented like this:
```json
{
    "things": {
        "thing": [
            {
                "id": 1,
                "name": "thing one"
            }, {
                "id": 2,
                "name": "thing two"
            }
        ],
        "bob": "Hi, I am bob"
    }
}
```

**Comment by adamski52** [comment]
I see what you mean.

 It's bad practice to mix types, but JS's typeless-ness is an intentional feature no matter how hard we try to change it, so a valid JSON of the XML you provided would be:

```
{
    "things": [{
            "id": 1,
            "name": "thing one"
        }, {
            "bob": "Hi, I am bob"
        }, {
            "id": 2,
            "name": "thing two"
        }]
}
```

It kind of falls apart once you get in to attributes, I guess.  So I guess it doesn't matter since there's no way _not_ to deviate between the two once you get there.

```
<things>
    <thing>
        <id>1</id>
        <name>thing 1</name>
    </thing>
    <bob now-what="uh oh!">Hi, I am bob</bob>
    <thing>
        <id>1</id>
        <name>thing 1</name>
    </thing>
</things>
```


```
{
    "things": [{
        "id": 1,
        "name": "thing 1"
    }, {
        "bob": "Hi, I am bob",
        "@now-what": "uh oh!"
    {
        "id": 2,
        "name": "thing 2"
    }]
}
```

**Comment by johnjaylward** [comment]
Yes, but once you try to reverse your JSON back to XML you will get a mess. 
i.e.
```xml
<root>
    <thing><id>1</id><name>thing 1</name></thing>
    <thing now-what:"un oh!"><bob>Hi, I am bob</bob></thing>
    <thing><id>2</id><name>thing 2</name></thing>
</root>
```
I doubt that that would be your expected output.

Keeping the "non-things" out of the "thing" array helps with that, but as you may have noticed, you then lose document order.

The answer is that there is no real good way to do it since the 2 formats are solving different problems. The way this library decided to handle it is to assume that someone converting from ordered XML to unordered JSON would rather keep the type (element names like "think" or "bob" in our examples) and would then forgo any order information.

JSON is not meant to represent a document while XML is. XML is not meant to hold semi random pieces of data, but it often does.

making these two things mesh will never be perfect.

**Comment by johnjaylward** [comment]
If I was designing this from scratch one option I would have considered is that each XML element is always an object. The text value of the element (i.e. "Hi, I am bob") would be on the empty key of that JSON object. for example:

```json
{
    "things": [{
        "id": {"":1},
        "name": {"":"thing 1"}
    }, {
        "bob": {
            "":"Hi, I am bob",
            "@now-what": "uh oh!"
        }
    {
        "id": {"":2},
        "name": {"":"thing 2"}
    }]
}
```

or something similar to that. that was made with all of 30 seconds of thought... It makes it harder to work with, but could possibly better describes the XML content

**Comment by stleary** [comment]
Looks like this issue is closed. XML / JSON mapping is imperfect, but fixing it would probably break a lot of currently working software.
