### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by Blackcorns** [stleary/JSON-java#426]
不能编译JSONArray.java

**Comment by MinnDevelopment** [comment]
Use the jar provided by maven rather than compiling it yourself.

**Comment by Blackcorns** [comment]
Sorry,I made a mistake.I used an old release and javac said some functions are out of date.

在 2018-07-01 23:25:14，"Sean Leary" <notifications@github.com> 写道：


What are the compiler errors?
