### ISSUE TITLE
single result arrays are parsed as non-arrays

### ISSUE THREAD

**Issue by tanel3203** [stleary/JSON-java#427]
This:
```
<items>
  <item>
     <name>cheese</name>
 </item>
 <item>
     <name>bratwurst</name>
  </item>
</items>
```

Produces:
```
{"items":{"item":[{"name":"cheese"},{"name":"bratwurst"}]}}
```

But
```
<items>
  <item>
     <name>cheese</name>
  </item>
</items>
```

Produces:
```
{"items":{"item":{"name":"cheese"}}}
```

 A third provider returns in nested XML arrays of 0..n which we parse into JSON for further procesing. Although the parsing probably works as expected, is there a way to force a parsed field to be treated as an array? So for the last one we'd expect to see:
```
{"items":{"item":[{"name":"cheese"}]}}
```

Thanks!

**Comment by tanel3203** [comment]
Closing this. Created a quick fix solution in scala:
It takes the parsed to JValue JSON and the field name and transforms to array is it's not.

`
def transformSingleItemToList(jv: org.json4s.JValue, nameOfFieldThatIsItemButShouldBeList: String): org.json4s.JValue = {
  jv transformField {
    case (s, x) if s.equals(nameOfFieldThatIsItemButShouldBeList) &&  x.isInstanceOf[JObject] =>
      (nameOfFieldThatIsItemButShouldBeList, JArray(List(x)))
    case (s, x) if s.equals(nameOfFieldThatIsItemButShouldBeList) && x.isInstanceOf[JArray]  =>
      (nameOfFieldThatIsItemButShouldBeList, x)
  }
}`

**Comment by tanel3203** [comment]
In case someone runs into the same issue, here's the full version :
```
import org.json4s.JsonAST.{JArray, JObject}

  def transformSingleItemToList(jv: org.json4s.JValue): org.json4s.JValue = {

    // supported fields' names that should instead of [T] be Seq[T]
    val names = Seq(
      "item",
      "test")
    jv transformField {
      case (s, x) if names.contains(s) &&  x.isInstanceOf[JObject] => (s, JArray(List(x)))
    }
  }
```

**Comment by johnjaylward** [comment]
@tanel3203 that code is not for the same project as this.

**Comment by tanel3203** [comment]
Thanks for the reply

I know the solution is through the use of a separate library. Since I couldn't quickly figure out a way to handle the issue at the moment of transforming XML to JSON using the current library, I solved it during transforming JSON to POJO. As it worked for my needs I thought it might benefit someone else ending up here also

The best
Tanel

**Comment by ToasterKTN** [comment]
Added a way that works for me. 
https://github.com/ToasterKTN/JSON-java
I simply made a prefix to a node, so when it matched the prefix, it created an Array.
Because i generate the XML File myself, i can simply force Array generation like that for single nodes too.
