### ISSUE TITLE
can invalid json be ignored?

### ISSUE THREAD

**Issue by progger2** [stleary/JSON-java#428]
Thanks for this lightweight and easy to use parser!
I ran in the message "Expected value" with a json like "ding":, "next": "whatever".
Of course this is not well build json. Nevertheless it would be great, if the parser continues and omits the value.

**Comment by VinQin** [comment]
I thought it is very stupid to throw a Exception instead of return null when there is no such key in JSONObject.

**Comment by MinnDevelopment** [comment]
@VinQin try using `opt(key)` instead

**Comment by stleary** [comment]
@progger2 thanks for the feedback. Please see the [FAQ](https://github.com/stleary/JSON-java/wiki/FAQ) for more information about what kinds of changes may be accepted for the lib.
