### ISSUE TITLE
Java 11 Compatibility check

### ISSUE THREAD

**Issue by abernatptc** [stleary/JSON-java#433]
Hi,
We are reaching out to you to check Java 11 compatibility of the library: JSON-java.

Could you help us by answering the following questions:
1.    Is the library compatible with Java 11 ? (Y/N)
2.    Is the library supported with Java 11? (Y/N)
3.    (If “N” in compatibility or support) What is the versions that would be compatible and Supported?
4.    Date of support availability?

Thanks,
Albert Bernat
PTC

**Comment by stleary** [comment]
We maintain compatibility with Java 1.6, and don't anticipate problems with current or future Java versions.
