### ISSUE TITLE
Remove namespace when parsing to json

### ISSUE THREAD

**Issue by huehnerlady** [stleary/JSON-java#434]
Hi,

`XML.toJsonObject()` currently just translates everything into Json. But when you have name spacing, you cannot remove these.

EG.
```
<ns2:someObject xmlns:ns2="http://someLink">
      <someOtherObject>
            <something>SOME_THING</something>
      </someOtherObject>
    </ns2:someObject>
```
will end up in
```
{
  "ns2:someObject": {
    "xmlns:ns2": "http://someLink",
    "someOtherObject": {
      "something": "SOME_THING"
    }
  }
}
```

But it should end up (eg. after configuring the parser) like this:
```
{
  "someObject": {
    "someOtherObject": {
      "something": "SOME_THING"
    }
  }
}
```
where the `ns2` infront of `someObject` is removed as well as the property `xmlns:ns2`
Is there already a hidden feature - or is this feature planned?

Many thanks

**Comment by stleary** [comment]
I think @johnjaylward addressed this issue in #321. This lib does not support XML namespaces; another lib might work better if you require this functionality. There are currently no plans to support it going forward.
