### ISSUE TITLE
Ability to convert XML to JSON without root element

### ISSUE THREAD

**Issue by msmigiel** [stleary/JSON-java#435]
Hi all,

I'm relatively new to JSON and am working on converting some XML based API automation to JSON REST APIs. I'm facing an issue when using this library to convert from XML to JSON.

More specifically, here is a sample input XML to the XAPI:

`<Price Currency="USD" EnterpriseCode="EnterpriseCode"><LineItems><LineItem Quantity="2" ItemID="ItemID" UnitOfMeasure="EACH"/></LineItems></Price>`

When I use the following Java code to convert it to JSON:

`String InputJSON = XML.toJSONObject(InputXML).toString(4)`

I get the following JSON:

`{"Price": {
    "LineItems": {"LineItem": {
        "UnitOfMeasure": "EACH",
        "Quantity": 2,
        "ItemID": "ItemID"
    }},
    "Currency": "USD",
    "EnterpriseCode": "EnterpriseCode"
}}`

However, our REST APIs are not expecting the root element but rather something like this:

`{
   "Currency": "USD",
   "EnterpriseCode": "EnterpriseCode",
   "LineItems": {
      "LineItem": {
         "Quantity": "1",
         "ItemID": "ItemID",
         "UnitOfMeasure": "EACH"
      }
   }
}`

Would it be possible to add the ability to remove the root element from a JSON either during or after conversion?

**Comment by johnjaylward** [comment]
If your JSON looks like this:
```json
{"Price": {
    "LineItems": {
        "LineItem": {
            "UnitOfMeasure": "EACH", "Quantity": 2, "ItemID": "ItemID"
        }
    },
    "Currency": "USD",
    "EnterpriseCode": "EnterpriseCode"
}}
```

couldn't you just `return jsonObject.getJsonObject("Price")` ?

or if this is just an example and you want to blindly remove the root item in general due to different start tags:
```java
public JSONObject removeRoot(JSONObject jo) {
    if(jo == null || jo.keySet().isEmpty()) return null;
    // possibly do more validation to ensure only 1 key, etc...
    final String rootKey = jo.keys().next();
    return jo.getJSONObject(rootKey);
}
```

**Comment by msmigiel** [comment]
Thank you for the reply. I was wondering if this was implemented already but I can do something like what you say too. 

When I try your first example and get Price, I get the error "org.json.JSONException: Null key". My overall code is something like this. Any idea why the key is null? The JSON looks valid and Price is there at the top.

`
String jsonString = XML.toJSONObject(InputXML).toString(4)
JSONObject jsonObject = new JSONObject(jsonString)
JSONObject jsonObject2 = jsonObject.getJSONObject("Price")
`

**Comment by javadev** [comment]
@msmigiel We have a new solution for json to xml. https://www.jdoodle.com/embed/v0/Ecb
