### ISSUE TITLE
Dual licensing

### ISSUE THREAD

**Issue by thecrazzymouse** [stleary/JSON-java#436]
Would it be possible to license this software under Apache 2.0. Some open-source projects prevent the usage of non-apache license as dependencies. My understanding is that the existing license is the same as Apache 2.0 with the exception of "use it for good".

**Comment by johnjaylward** [comment]
I'm pretty sure it's closer to the MIT license. Also, you don't have to use it for good. You just can't use it for evil.

As for dual licensing, Most projects I see that used on has some kind of paid support which activates the other license. I don't see that working here.

Are you suggesting the licensing terms would be chosen by the end user?

**Comment by thecrazzymouse** [comment]
MIT license is also completely good. There are many projects that support dual licensing for example https://mvnrepository.com/artifact/org.checkerframework/checker-compat-qual/2.5.5 

In case of dual licenses the end user can choose from the available multiple licenses. I had a longer chat with the Linux Foundation, and in their opinion it is completely normal to have multiple licenses.

The problem with the "use it for good", is that it is too wage from legal perspective. We are not using this for anything bad, but the legal department insists to replace this library, because they can not solve the legal issues.

**Comment by johnjaylward** [comment]
#331 has a longer discussion on the issue. Take a look there first. However, I don't see myself or @stleary taking the time to go through and contact everyone in the list to change the license at all. Maybe if someone else takes over the effort it could be done, but we are both pretty busy. I know I personally don't have time to notify that many people and manage the project to get consensus on a license change,

**Comment by stleary** [comment]
Please see https://github.com/stleary/JSON-java/wiki/FAQ#can-you-change-the-license-to-remove-the-the-software-shall-be-used-for-good-not-evil-line

Requests to change the license need to be directed to the author.

**Comment by thecrazzymouse** [comment]
do you know who is the author of this library? I thought it was you.

**Comment by MinnDevelopment** [comment]
As far as I can tell the original author of this library is Douglas Crockford himself and he has been reluctant to change license ever since JSON was created.

**Comment by stleary** [comment]
A quick check of the [Wiki](https://github.com/stleary/JSON-java/wiki) will confirm that Douglas Crockford is the author:
"_This GitHub repository was created in 2010 by Douglas Crockford, who wrote the original JSON specification._"

**Comment by thecrazzymouse** [comment]
I have read several articles about this. It look like that he does not want to change the license. So we will be migrating away from this. I think it is vert sad, but it is up to him.
https://en.wikipedia.org/wiki/Douglas_Crockford#.22Good.2C_not_Evil.22
https://wiki.debian.org/qa.debian.org/jsonevil
https://lwn.net/Articles/707510/
