### ISSUE TITLE
Feature request: allow the XML class to generate a JSONArray objects for named elements

### ISSUE THREAD

**Issue by hktegner** [stleary/JSON-java#437]
Certain services (outside our control) are very particular about the JSON they receive and it would really helpful if we were able to have tighter control as to when the XML class creates a JSONArray and not, so that we can satisfy these services.

*Examples*

Two person elements currently get put into a JSONArray object:
`<root><person>Bob</person><person>Bill</person></root>`
Ideal JSON:
`{ root: { 
      person: [ 'Bob', 'Bill' ] 
}}`

A single person element currently does not get put into a JSONArray object:
`<root><person>Bob</person></root>`
Ideal JSON:
`{ root: {
    person: [ 'Bob' ]
}}
`

I know the common answer is that the receiving end should cope with a single person and multiple person objects in an array, but this is not helpful when it's a third party service you are using.

**Comment by johnjaylward** [comment]
If your xml/json isn't too complex, you can just post-process the JSON before sending it to the 3rd party.

i.e. (may not compile, doing this from memory, but you get the idea)
```java
JSONObject jo = XML.toJSONObject(myXml);
JSONObject root = jo.getJSONObject("root");
Object person = jo.opt("person");
if(person != null && !(person instanceof JSONArray)) {
    root.remove("person");
    // re-add as a single element array
    root.append("person",person");
}
```

I can see how this may be annoying for more complex XML, but you should be able to just stick something like this in a function and call it all over. If you look into the JSONPointer options as well, you may be able to make this into a more configurable function that takes a list/array of JSONPointers and performs this check for each one.

**Comment by johnjaylward** [comment]
For the JSONPointer option, I'm thinking something like this:

```java
function forceArray(JSONObject jo, JSONPointer... refs){
    if(jo == null || refs == null || refs.length == 0) return;
    for (JSONPointer jp : refs) {
        Object o = jo.Query(jp);
        // if the items isn't there or is already an array, skip
        if( o == null || (o instanceof JSONArray) continue;

        // replace the existing item with an array
        String ref = jp.toString();
        int lastIds = ref.lastIndexOf("/");
        String forcedArrayMember = ref.subString(lastIdx+1);
        String parentRef = ref.subString(0, lastIdx);
        Object parent = jo.query(parentRef);
        if(parent instanceof JSONObject) {
            parent.append(forcedArrayMember, o)
        } else if (parent instanceof JSONArray) {
            int arrayIdx = Integer.parseInt(forcedArrayMember);
            JSONArray newArray = new JSONArray();
            newArray.put(o);
            parent.put(arrayIdx, newArray);
        } else {
           // this really shouldn't happen... since this is a parent item, it should always be an array or object
           // throw an exception maybe?
        }
    }
}

**Comment by hktegner** [comment]
Thanks for your reply. I know the above will work, but was hoping for a feature you could configure so the converter would do it for you. I have seen various half-baked solutions out there, but not in established libraries like this one.

**Comment by johnjaylward** [comment]
This is a reference library meant for managing JSON. The support for XML transforms is well documented as being minimal.

Also, pre/post processing input/output data is not "half baked". It is standard procedure for ensuring your data looks the way it should when moving it between systems. The above solutions are probably very close to what would be done if it were to be added to the library itself.

If you feel you can do better, please feel free to send over a pull request. I always enjoy seeing other's solutions and learning new things.

**Comment by javadev** [comment]
Hi,

It may be a new attribute `array="true"` in xml.

```xml
<root><person array="true">Bob</person></root>
```

**Comment by stleary** [comment]
Outside the scope of this application.
