### ISSUE TITLE
Link to download a jar file for this project at the top of the readme would be helpful

### ISSUE THREAD

**Issue by davidglavas** [stleary/JSON-java#442]
worked for me: http://www.java2s.com/Code/Jar/j/Downloadjavajsonjar.htm

**Comment by johnjaylward** [comment]
I would rather people use the official maven repos already linked. You can download the jar through there easy enough

**Comment by davidglavas** [comment]
The link at the end of the readme is just what I was looking for, my bad.

Adding the following to the top of the readme would simplify things, as it's what most people are probably looking for:

> Download this repo's JAR [here](https://search.maven.org/search?q=g:org.json%20AND%20a:json&core=gav).

**Comment by stleary** [comment]
See also #378. At the time, there were no big objections to including a download link. This could be helpful for developers who just want a Grab and Go jar file.

**Comment by johnjaylward** [comment]
@stleary we already have 2 links to the the JAR in the readme, one direct link at the end, the other indirect through the Maven tag at the top.

I'd propose just moving the direct link at the bottom to the top

**Comment by stleary** [comment]
Fixed

**Comment by javadev** [comment]
It may be releases tab with jar files.

**Comment by stleary** [comment]
@javadev please clarify, do you want an additional link, or change one of the existing links, or...?

**Comment by javadev** [comment]
I see releases tab. It may be jar file inside release.
