### ISSUE TITLE
User-defined getJSON() method results in infinite recursion.

### ISSUE THREAD

**Issue by chenhongbao** [stleary/JSON-java#444]
I have a bean where there is a getJSON() method like the below:

> public JSONObject getJSON() {
> 	return new JSONObject(this);
> }

In the constructor of JSONObject, it will call populateMap(bean) where it iterates over all methods and finally call getJSON() again. And it will call the constructor of JSONObject again and again.

> public JSONObject(Object bean) {
>     this();
>     this.populateMap(bean);
> }

In populateMap() function, it will call getJSON() again.

>  for (final Method method : methods) {
>       final int modifiers = method.getModifiers();
>       if (Modifier.isPublic(modifiers)
>             && !Modifier.isStatic(modifiers)
>             && method.getParameterTypes().length == 0
>             && !method.isBridge()
>              && method.getReturnType() != Void.TYPE
>              && isValidMethodName(method.getName())) {
>          final String key = getKeyNameFromMethod(method);
>          if (key != null && !key.isEmpty()) {
>             try {
>                 final Object result = method.invoke(bean);  //HERE CALLS getJSON()

How can I avoid this problem?  Or there is future fix for it.

**Comment by johnjaylward** [comment]
Make sure you are using the latest version of this library. Once you do that, add the JSONPropertyIgnore annotation to your getJSON method like so:

```java
@JSONPropertyIgnore
public JSONObject getJSON() {
    return new JSONObject(this);
}
```

**Comment by chenhongbao** [comment]
@johnjaylward 
Thank you very much.
