### ISSUE TITLE
Suggestion to remove JSONException from JSONObject.put methods

### ISSUE THREAD

**Issue by ChristianLutz** [stleary/JSON-java#446]
Hello,

I know there is some history about JSONObject.put and the corresponding Exception (#402, #405, #385, and probably more).

What I want to suggest is to remove the JSONException from the put(..) methods and use the default `IllegalArgumentException`.
This would reduce some boilerplate code to write. 

Currently I need to write
```
 JSONObject json = new JSONObject();
  try {
    json.put("some-key", "some-value"); 
  } catch (JSONException e) {
    // Not happening
  }
```
or with java8 Stream, I need some wrapper to handle the checked exception. 

```
  x.stream()
    .filter(Objects::nonNull)
    .map(value -> new JSONObject().put("some-key", value)) // doesn't work without wrapper
    ....
```

I know it is a breaking change. So maybe this is something to consider for a major update.

Sincerely
Christian

**Comment by johnjaylward** [comment]
JSONException has been a runtime exception for quite a long time. Looking at the history it was update to be a RuntimeException back in 2013. Please check that you are using at least a somewhat recent version of the library

**Comment by ChristianLutz** [comment]
Hello,

thanks for the hint. You are right. I am using a very old version. 

Issue closed
