### ISSUE TITLE
There is a double type in the map. After a certain length, it will be converted to scientific notation

### ISSUE THREAD

**Issue by shinehertheway** [stleary/JSON-java#449]
- [ ] There is a double type in the map. After a certain length, it will be converted to scientific notation

. The raw data map I got could not be changed, but I don't want scientific notation.How can I avoid this?
code show as below：
`import org.json.JSONObject;
import org.json.XML;
public class Test {
	public static void main(String[] args) {
        c();
	}
	public static void c(){
		String jsonStr = "{\"TotAvlBal\":59999997.00,\"SvcPsRlt\":\"0000\"}";
        JSONObject jsonObj = new JSONObject(jsonStr);
        System.out.println(jsonObj.toString());
        String xml=XML.toString(jsonObj);
        System.out.println(xml);
	}
}
`
output：
{"TotAvlBal":5.9999997E7,"SvcPsRlt":"0000"}
<TotAvlBal>5.9999997E7</TotAvlBal><SvcPsRlt>0000</SvcPsRlt>

**Comment by johnjaylward** [comment]
Scientific notation is valid JSON output. There is no reason to change it unless you are losing precision, which it appears you are not.

**Comment by shinehertheway** [comment]
> 科学记数法是有效的JSON输出。没有理由改变它，除非你失去精确度，看起来你不是。

**Comment by shinehertheway** [comment]
> 科学记数法是有效的JSON输出。没有理由改变它，除非你失去精确度，看起来你不是。

What I need is the form that exists in the map.

**Comment by shinehertheway** [comment]
> Scientific notation is valid JSON output. There is no reason to change it unless you are losing precision, which it appears you are not.

What I need is the form that exists in the map.

**Comment by johnjaylward** [comment]
Then you need to replace the Double value BigDecimal.

```java
import org.json.JSONObject;
import org.json.XML;
public class Test {
   public static void main(String[] args) {
   c();
 }
   public static void c(){
     String jsonStr = "{\"TotAvlBal\":59999997.00,\"SvcPsRlt\":\"0000\"}";
     JSONObject jsonObj = new JSONObject(jsonStr);
     jsonObj.put("TotAvlBal", jsonObj.getBigDecimal("TotAvlBal"));
     System.out.println(jsonObj.toString());
     String xml=XML.toString(jsonObj);
     System.out.println(xml);
   }
}
```

**Comment by shinehertheway** [comment]
Maybe I don’t know how to do it. I’m going to do something like this in an unknown size and the key is not fixed.

**Comment by johnjaylward** [comment]
There really is no technical reason to do it. I'm not sure why you'd want to. Is it due to the XML?

If you really don't know which keys will contain Double values, you can do something like this:
```java
for (final String key  : jsonObj.keySet()) {
  if (jsonObj.opt(key) instanceof Double) {
     jsonObj.put(key, jsonObj.getBigDecimal(key));
  }
}
```

**Comment by shinehertheway** [comment]
> There really is no technical reason to do it. I'm not sure why you'd want to. Is it due to the XML?
> 
> If you really don't know which keys will contain Double values, you can do something like this:
> 
> ```java
> for (final String key  : jsonObj.keySet()) {
>   if (jsonObj.opt(key) instanceof Double) {
>      jsonObj.put(key, jsonObj.getBigDecimal(key));
>   }
> }
> ```

According to what you said, when double encounters a decimal place of 0, it will round off the decimal place. If it is non-zero, it will get an inaccurate number. I just want it to retain the original look

**Comment by stleary** [comment]
The JSON RFC allows the implementation to set limits on numeric range and precision. If you want to change the way this app handles numbers in XML transforms, please make a case to justify the change.
