### ISSUE TITLE
[Documentation] Please add simple json string parsing example to Readme.md

### ISSUE THREAD

**Issue by jleaders** [stleary/JSON-java#450]
One of the most common use-cases of JSON libraries is taking a string and parsing it to a JSON array object of some sort, but I notice dsl-json's Readme.md has plenty of information about the library but no "common case" string serialization example at the top level. Please add.
Something equivalent to javascripts
`var obj = JSON.parse('{ "name":"John", "age":30, "city":"New York"}');`
Thank you.

**Comment by stleary** [comment]
Sounds reasonable. Feel free to propose some text for the readme.

**Comment by stleary** [comment]
Adding basic startup information to a Wiki page. When it is more or less complete, will add a link from the readme.
