### ISSUE TITLE
JSONObject and JSONArray should impliment Serializable

### ISSUE THREAD

**Issue by Tacodude7729** [stleary/JSON-java#454]
Currently, if you try to serialize an object with a `JSONObject` or `JSONArray` you will get a `java.io.NotSerializableException`. Having these class implement `Serializable` would allow for objects with `JSONObjects` or `JSONArrays` as members to be serialize.

**Advantages**

- You can serialize objects that have JSON members.
- Consistency. Every data structure class (`Map`, `List` etc) in the `java.*` packets implements `Serializable` as to be flexible (most other classes in `java.*` also implement `Serializable`). As the JSON classes are also data structures it would make sense for them to be `Serializable` as well.
- Easy to implement (see what I did there. ;).  `Serializable` has no methods.
- It won't break any code that already uses the `JSONObject` or `JSONArray` classes.

**Disadvantages**

- Serialized object would potentially break between releases (if the JSON classes where changed in a significant way) which could result in data loss. However this is normally accepted as a consequence of serialization.
- It's likely a one time decision - once these classes are `Serializable` they shouldn't be changed back.

**Comment by johnjaylward** [comment]
That what the `toString` method is for. A JSONObject or JSONArray by definition is meant to be serialized as a string for data transfer or storage. Using Java Binary serialization is the wrong way to handle these objects.

See also https://dzone.com/articles/object-serialization-evil

**Comment by Tacodude7729** [comment]
@johnjaylward, I agree - serialization has incorrect uses but is also has very good and handy uses. For example I am programming a server in java - each client can have up to 10 JSON objects associated with it and I want to keep these clients around for a day so people only have to login once a day even if the server restarts. So I save them to a file using serialization.
Having these classes be `Serializable` has no drawbacks if you use them correctly.

**Comment by johnjaylward** [comment]
Binary serialization is really not how this library is meant to work. I'd rather not implement it at all and have people opening bugs due to serializing or deserializing incorrectly instead of using JSON how it's supposed to be used.

In your case, if you really want to serialize JSON as part of another object, I'd recommend something like mentioned here: https://stackoverflow.com/a/7292035

```java
public class MyWeirdBean implements Serializable {
private static final int serializableId = 1L; // use a real serial ID here

private transient JSONObject myJO;

// some other non-transient fields

private void writeObject(ObjectOutputStream oos) throws IOException {
    // default serialization 
    oos.defaultWriteObject();
    // write the object
    oos.writeString(myJO.toString())
}

private void readObject(ObjectInputStream ois) throws ClassNotFoundException, IOException {
    // default deserialization
    ois.defaultReadObject();
    myJO= new JSONObject(ois.readString());
    // ... more code

}
}
```

I have no idea if that code compiles.

**Comment by stleary** [comment]
@Tacodude7729 Thanks for investigating the issue and making the suggestion. In this case I think the library already provides the required core functionality for the reasons cited above.
