### ISSUE TITLE
ParseException unreachable compilation error

### ISSUE THREAD

**Issue by jmetertea** [stleary/JSON-java#455]
I have the following (working code) with old `JSONObject` jar

```
    try {
		JSONObject gameDetailsJson = new JSONObject(string);					
	} catch(ParseException e) {
		logger.error("Could not parse", e);
	}

```
When using latest jar I get a compile error 

`    Unreachable catch block for ParseException. This exception is never thrown from the try statement body
`
I see that it throws now JSONException, but isn't it a regression bug or am I missing something?
What's the best way to handle it ?

**Comment by johnjaylward** [comment]
In the close to 10 years I've used this library it has never thrown a ParseException. It's possible you were using a fork
