### ISSUE TITLE
Expected Behaviour of CDATA parsing to JSON

### ISSUE THREAD

**Issue by clementdevos** [stleary/JSON-java#457]
Hi, 

We're using your library to parse XML to JSON using ` XML.toJSONObject(input)`

This is a mock of the XML we parse which usually an RSS feed : 

```
<?xml version="1.0" encoding="UTF-8" ?>
<channel>
    <item>
        <title>
            <![CDATA[some ]]>useful
            <![CDATA[ stuff]]>
        </title>
    </item>
    <item>
        <title>b</title>
    </item>
</channel>
```

The result of the parsing is a 3 string array instead of a single string. Is this the expected behaviour? 

![image](https://user-images.githubusercontent.com/5870982/50904309-432c5a80-1420-11e9-84ba-5c6db702f017.png)

Cheers !!

Clément

**Comment by johnjaylward** [comment]
Yes, the cdata tags are elements within the Title and are tokenized separately.

**Comment by clementdevos** [comment]
Damn ! OK thanks for your quick reply !

**Comment by GedMarc** [comment]
The only way is through xslt :)

cdata can contain everything and is a 'raw string literal', your example is pretty simple but what happens when you get 
```
<![CDATA[
Within this Character Data block I can
use double dashes as much as I want (along with <, &, ', and ")
*and* %MyParamEntity; will be expanded to the text
"Has been expanded" ... however, I can't use
the CEND sequence. If I need to use CEND I must escape one of the
brackets or the greater-than sign using concatenated CDATA sections.
**]]>**
```

Because of this, there is no cdata -> java direct conversion, in any library. 
What you need to do is XSLT the xml into what you want, I imagine from your example you want <x:string> instead of cdata?

**Comment by clementdevos** [comment]
Yeah seems pretty logic !

We're experiencing this with parsing of instagram's rss feed and our code should not implement any specific behaviour so... i don't know what we're going to do just yet ! :)


Thanks again!
