### ISSUE TITLE
Preservation of Empty Fields When Converting XML to JSON

### ISSUE THREAD

**Issue by lachlanjwatson** [stleary/JSON-java#462]
Hi all,
I had an issue with taking a String representing a JSON response and converting it to XML doing something like
``` java
JSONObject json = new JSONObject(jsonString);
return XML.toString(json);
```
where the XML output would strip all fields that didn't contain data. Due to the nature of my work, from a data conversion and consistency perspective this outcome was not ideal. As a fix, I wrote the following code:

``` java
public static String convertJsonToXml(String jsonStr) {
    String stringToBeChanged = jsonStr;
    String nullString = "[null]";

    //this regex detects empty square brackets or ones containing just a space
    String sPattern1 = "\\[[^\\[]\\]";
    String sPattern2 = "\\[[^\\[ ]\\]";
    
    //replace all instances of "[]" with "[null]" and place in a temp string
    Pattern pattern1 = Pattern.compile(sPattern1);
    Matcher matcher1 = pattern1.matcher(stringToBeChanged);
    String tempString = matcher1.replaceAll(nullString);
    
    //replace all instances of "[ ]" with "[null]" and create final string
    Pattern pattern2 = Pattern.compile(sPattern2);
    Matcher matcher2 = pattern2.matcher(tempString);
    String finalString = matcher2.replaceAll(nullString);
    
    //a weird conversion issue requires this right square/curly bracket to be 
    //appended to the end of the string
    finalString += "]}";
    
    //the 2 lines below were the original version of this method
    JSONObject json = new JSONObject(finalString);
    return XML.toString(json);
}
```
I don't necessarily believe this is an issue with the codebase itself but I believe having this option/code available here will help some people that run into the same issue where they *do* wish to preserve empty fields for the sake of data consistency.

**Comment by johnjaylward** [comment]
`[]` and `[null]` are totally different data... Without seeing a sample of
the source object, I just can't see why anyone would want to corrupt their
data like this.

The first is an empty array, the second is an array with a single `null`
element

**Comment by lachlanjwatson** [comment]
You're correct. Unfortunately that was the easiest way I could think of to ensure the field carried over as it seems that the current conversion process completely ignores `[]` and `[ ]`. After that, I can process as I need. Only other way would be filling it with some other dummy value that gets stripped out after the fact.

**Comment by stleary** [comment]
Closed for inactivity.
