### ISSUE TITLE
JSONTokener throws JSONException on json with hexa string

### ISSUE THREAD

**Issue by saart91** [stleary/JSON-java#468]
After version 20090211, when I'm trying to parse this json (for example) using JSONTokener:
[{
    "key": "\x03\x56\x35"
}]

I get this error:
org.json.JSONException: Illegal escape. at 407 [character 52 line 13]
        at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
        at org.json.JSONTokener.nextString(JSONTokener.java:353)
        at org.json.JSONTokener.nextValue(JSONTokener.java:428)
        at org.json.JSONObject.<init>(JSONObject.java:245)
        at org.json.JSONTokener.nextValue(JSONTokener.java:431)
        at org.json.JSONArray.<init>(JSONArray.java:125)
        at org.json.JSONTokener.nextValue(JSONTokener.java:434)
        at org.json.JSONObject.<init>(JSONObject.java:245)
        at org.json.JSONTokener.nextValue(JSONTokener.java:431)
        at org.json.JSONArray.<init>(JSONArray.java:125)
        ....
My question is, why is it never happened on version "20090211", but happens on later versions? (I tried all the versions since, it happens in all of them) Is there any way to fix this, so I can use the most updated library?

**Comment by johnjaylward** [comment]
2009 is a very old version. `\x` however, is not a valid JSON escape. Most likely it was removed as a bug-fix. You can see the list of valid escapes in the [README](https://github.com/stleary/JSON-java). The relevant code that is handling the escapes is here:

[JSONTokener.java](https://github.com/stleary/JSON-java/blob/master/JSONTokener.java#L300): 
```java
    /**
     * Return the characters up to the next close quote character.
     * Backslash processing is done. The formal JSON format does not
     * allow strings in single quotes, but an implementation is allowed to
     * accept them.
     * @param quote The quoting character, either
     *      <code>"</code>&nbsp;<small>(double quote)</small> or
     *      <code>'</code>&nbsp;<small>(single quote)</small>.
     * @return      A String.
     * @throws JSONException Unterminated string.
     */
    public String nextString(char quote) throws JSONException {
        char c;
        StringBuilder sb = new StringBuilder();
        for (;;) {
            c = this.next();
            switch (c) {
            case 0:
            case '\n':
            case '\r':
                throw this.syntaxError("Unterminated string");
            case '\\':
                c = this.next();
                switch (c) {
                case 'b':
                    sb.append('\b');
                    break;
                case 't':
                    sb.append('\t');
                    break;
                case 'n':
                    sb.append('\n');
                    break;
                case 'f':
                    sb.append('\f');
                    break;
                case 'r':
                    sb.append('\r');
                    break;
                case 'u':
                    try {
                        sb.append((char)Integer.parseInt(this.next(4), 16));
                    } catch (NumberFormatException e) {
                        throw this.syntaxError("Illegal escape.", e);
                    }
                    break;
                case '"':
                case '\'':
                case '\\':
                case '/':
                    sb.append(c);
                    break;
                default:
                    throw this.syntaxError("Illegal escape.");
                }
                break;
            default:
                if (c == quote) {
                    return sb.toString();
                }
                sb.append(c);
            }
        }
    }
```

**Comment by stleary** [comment]
Closing due to answer provided and no additional activity.
