### ISSUE TITLE
.optString() vs .getString() behavior differs when integer value

### ISSUE THREAD

**Issue by naknomum** [stleary/JSON-java#472]
is this a bug?  is it desirable behavior?  or maybe i am just going crazy here.  i have this code:
`if (args.optString("foo", null) != null) doSomething(args.getString("foo"));`

`args` is getting passed with **foo** having a value of **589785** (note: _not_ a string, but an integer; no quotes).  the _conditional_ is evaluating as true (in fact you can see `args.optString("foo", null)` does indeed return a "589785")... but there is an **exception thrown** during the `.getString()`.

note:  i am _guessing_ that this may be related to how i am *creating args*.  it is made from the constructor `new JSONObject(inputString)` where `inputString` would be something like **{ "foo": 589785 }**

for now, my workaround is going to be to use `args.optString("foo", null)` as the argument to `doSomething()`.... but this behavior seemed weird and unexpected to me.

**Comment by johnjaylward** [comment]
The `get*` methods are meant to throw exceptions when they types are wrong. The `opt*` methods perform some data conversions and return possible values. Since you are creating the JSONObject with a Number value, the `getString` fails since the data type is wrong. This was done to let callers know if the JSON they are parsing is invalid.

**Comment by naknomum** [comment]
good to know!  i have been assuming the evaluation was the same for some time now.  guess i can wait til some other cases break and fix those, heh.  i suppose my "workaround" then is actually just a more flexible variation.  since it works, i will just use that pattern.  thanks.

**Comment by johnjaylward** [comment]
A cleaner pattern would be closer to this:
```java
if ( args.has("foo")) {
    doSomething(args.optString("foo"));
}
````

The `has` method should be a faster check then a full get/opt call, and the single parameter `optString` defaults the value to empty string. but it should never hit the empty string case if you are already checking that it is in the object.

**Comment by johnjaylward** [comment]
It should be noted that the has/opt pattern does function slightly different than the opt/opt pattern that you are using as a JSON string that looks like this `{"foo":null}` would show that the object has a `foo`, but when returned from the `optString` method(s), you would get the default value.

The opt/opt check though, you would never get the default value passed to your `doSomething` method.

**Comment by naknomum** [comment]
thanks for the detailed explanation.  we have run into some of the subtleties regarding `null` before (who hasnt?).  i think what happened here is that _some_ of our client js code would encode `.foo` on the json as a string, but then also force it to a number when the string's value was an integer.  ideally on the back end we would want the numbers turned into strings.  so i think the our best option is to handle both cases (string and int) and convert the int to string.  it was just sort of dumb luck that `optString()` converted the int to string.
