### ISSUE TITLE
XML.toJSONObject is Error

### ISSUE THREAD

**Issue by pencilso** [stleary/JSON-java#477]
java 1.8 
org.json version is 20180813
xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<business comment="登记应用" id="DJAPP" version="2.0">
    <head>
        <appname>哈哈</appname>
        <devkey>c90f65a14f284ecfb6f2458d14a73344</devkey>
        <qy_name>asdassafdsfgsdf</qy_name>
    </head>
</business>
```

toJSONObject Error: java.lang.NoSuchMethodError: org.json.JSONTokener.<init>(Ljava/io/Reader;)V

but org.json version replace 20180130 is success

**Comment by johnjaylward** [comment]
I don't see any reason for the error. It's possible you have a classpath issue.
