### ISSUE TITLE
No modules support

### ISSUE THREAD

**Issue by denismakogon** [stleary/JSON-java#478]
So, it's been a while since Java 9 was published, but still no support for modules (project jigsaw). Seeing this while building a modular application:
```
automatic module cannot be used with jlink: org.json
```
So, can you please add module description file here?

**Comment by johnjaylward** [comment]
@stleary we should probably reopen #451.  I think we should look into making it work with the work @GedMarc  originally did. His changes were fairly straightforward and testing across multiple JVMs will probably be a bit of work to initially set up, but once configured should be maintainable.

**Comment by stleary** [comment]
451 reopened

**Comment by stleary** [comment]
Please use #451 for future comments.
