### ISSUE TITLE
optString not consistent with optXxx getters

### ISSUE THREAD

**Issue by guidomedina** [stleary/JSON-java#479]
Our team sometimes have made the mistake of doing the following:
```
String a = json.optString("a");
if (a != null) {
  doSomething();
}
```
but the above will not work as expected because when the String is not present it will not be null but an empty String, IMHO this is inconsistent with the following:
```
Number a = json.optNumber("a");
if (a != null) {
  doSomething();
}
```
This is kind of misleading, every other Json API I know (Vert.x Json, Jackson and Gson) will return null if the String is not present.

**Comment by johnjaylward** [comment]
The javadoc is very explicit about how a missing key is handled
```
Get an optional string associated with a key. It returns an empty string
if there is no such key. If the value is not a string and is not null,
then it is converted to a string.
```

I don't see an issue with this. If you would like a different default value, then you can use the 2 parameter `optString(key, default)` method

```java
String a = json.optString("a", null);
if (a != null) {
  doSomething();
}
```

**Comment by guidomedina** [comment]
I know, that's how we handle it which is unconventional, sometimes some developer has forgotten this and ended up introducing an unwanted behavior, the lack of a value shouldn't be an empty String, it should be null, sure; maybe it is too late to change this behavior.

Imagine if your String variables where initialized to `""` instead of `null` by the JVM, this feels the same way.

**Comment by guidomedina** [comment]
This behavior also violates the null convention, this test should return `true`, but it is actually `false`:
```
  @Test
  public void testJsonString()
  {
    System.out.println(new JSONObject("{\"a\":null}").optString("a") == null); // this should print true but it prints false instead.
  }
```

**Comment by johnjaylward** [comment]
I'm going to say it's probably too late. The code has been set to return empty string since day one. Changing the default at this point would introduce many more errors across many different peoples code than it would fix.

I can only encourage you to use unit testing and validate your users code.

**Comment by johnjaylward** [comment]
well, also to point out there is an "isNull" check which would do exactly what you want:
```java
if (!json.isNull("a")) {
  String a = json.optString("a", null);
  doSomething(a);
}
```

**Comment by guidomedina** [comment]
I agree, it is probably too late, though the null convention at the Json spec https://json.org/ is a strong case.
Yes I can check and get but that is less than ideal, you have to clutter the code with check if the value is there and then get it, the analogy using a `Map` would be:
```
final Map<String, String> map = populateMapAtSomePoint();

// Do you prefer this?
if (map.hasKey(key)) {
  String value = map.get(key);
  doSomething(value);
}

// or this?
String value = map.get(key);
if (value != null) {
  doSomething(value);
}
```
Not only the latter has less lines of code but also it doesn't perform an extra `Map.get(key)` operation

**Comment by guidomedina** [comment]
There are some pros and cons, but I would assume the following:
- Most projects usually check release notes for breaking changes to look for things like this.
- I would assume most people that use the library are aware of this issue or else have a subtle bug which they haven't found as empty String and null makes a huge difference for one not to notice.
- It would be more in par with the standard and more natural if it would return null.

**Comment by stleary** [comment]
@johnjaylward Agree with your evaluation that this valid assessment, but that changing it poses a risk to existing applications. 

@guidomedina, Thanks for bringing up this issue, it is appreciated. In this case I think it is probably better to document and live with the bug. One of the guiding principles of this project is not to introduce potentially breaking changes to the API unless we can show the bug is catastrophic.
