### ISSUE TITLE
java.lang.NoSuchMethodError: org.json.JSONObject.put(Ljava/lang/String;Ljava/util/Map;)Lorg/json/JSONObject;

### ISSUE THREAD

**Issue by seet61** [stleary/JSON-java#490]
I do some changes at my project after 2 month and one of my test cases finished with exception.

At logs I saw:
`java.lang.NoSuchMethodError: org.json.JSONObject.put(Ljava/lang/String;Ljava/util/Map;)Lorg/json/JSONObject;
	at ru.tele2.esb.service.FioriTools.sendHttp(FioriTools.java:353)
	at ru.tele2.esb.service.FioriTools.checkSession(FioriTools.java:123)
	at ru.tele2.esb.service.FioriToolsTest.checkSession(FioriToolsTest.java:54)`

At this line:
jsonResponse.put("headers", response.headers().toMultimap());

response is a Response object from com.squareup.okhttp3 lib.

After that I check my code and didn't saw any Error.(Intellij idea 2018.3).
And I see that method exist at library:
    public JSONObject put(String key, Map<?, ?> value) throws JSONException {
        return this.put(key, (Object)(new JSONObject(value)));
    }

What's wrong?

**Comment by seet61** [comment]
At runtime everything work correctly.

**Comment by johnjaylward** [comment]
sounds like a classpath issue in your test environment. check that all your transitive dependencies are correct

**Comment by seet61** [comment]
It is a spring app. I don't think that classpath incorrect for test, but correct for runtime.

**Comment by seet61** [comment]
All dependencies gets from pom, and classpath builds dyamicly by spring.

**Comment by GedMarc** [comment]
Delete the org.json packages directly from the maven repository, run a test in offline mode. See which library it's moaning about and make sure it's the right one. 
If it doesn't moan you aren't using this one, but rather, 
Spring also has their own version of this library and is referencing that.

**Comment by seet61** [comment]
Thanks.
When I changed  spring-boot-starter-test dependency, all tests finished successfully.
`<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.json</groupId>
                    <artifactId>json</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.vaadin.external.google</groupId>
                    <artifactId>android-json</artifactId>
                </exclusion>
            </exclusions>
        </dependency>`

It is a mystery situation, because the same functionality at another app work correctly for all tests, without exclusions for spring-boot-starter-test.

**Comment by stleary** [comment]
Closed due to inactivity.

**Comment by satish11111** [comment]
i am getting dont know what to do

**Comment by stleary** [comment]
Hi @satish11111 can you provide more context on what is going wrong?
