### ISSUE TITLE
[Feature Proposal] XML.toString support tag name uppercase or customization

### ISSUE THREAD

**Issue by oxnz** [stleary/JSON-java#498]
Currently, `XML.toString` will use the key as tagName by default.
but according to XML definition, tag names must be all uppercase.
So I wondering is there any plan to change current situation here?
either change current implementation (which is aggressive)
or add a tagName transform func or define some built-in tag name style?

**Comment by johnjaylward** [comment]
XML does not require tag names to be uppercase. I'm not sure where you heard that requirement. They are case-sensitive though.

**Comment by stleary** [comment]
Thanks for the suggestion, but no plans at the present time to support all uppercase XML tags.
