### ISSUE TITLE
Proposal for adding method getAsList(JSONObject o, final String key)

### ISSUE THREAD

**Issue by ogronome** [stleary/JSON-java#501]
Hello! Great lib, thank you very much!
But for me, one useful method is absent.

It is useful for situations, where nested JSON can be a either JSONObject or JSONArray, so you should add everywhere these boring checks. 

Should I add a pull request?

     public List<JSONObject> getAsList(JSONObject o, final String key) {

        List<JSONObject> result = new ArrayList<>();

        if (o.has(key)) {
            Object t = o.get(key);

            if (t instanceof JSONArray)
                for (int i = 0; i < ((JSONArray) t).length(); i++) {
                    result.add(((JSONArray) t).getJSONObject(i));
                }

            if (t instanceof JSONObject)
                result.add((JSONObject) t);

        }

        return result;
    }

**Comment by stleary** [comment]
@ogronome, thanks should go to Douglas Crockford, for this app, and for JSON itself :)
Regarding your question, please see JSONArray.toList(), which I think already provides the functionality you want.

**Comment by ogronome** [comment]
Thanks, but as I see, JSONArray.toList() just converts existing JSONArray to List.
My case is: often I get JSONs (by using XML.toJSONObject() ) where some key can be either JSONObject or JSONArray. And you need a lot of checks in code to parse this.

Example JSON:
If there is one coowner, I get JSONObject, if there are several, I get JSONArray.
{"Response":{"Coowners":{"Coowner":{"ID":266425}}}}

JSONArray.toList() is useless here.

json.getJSONObject("Response")
.getJSONObject("Coowners")
.getJSONArray("Coowner").toList().size());

throws an exception org.json.JSONException JSONObject["Coowner"] is not a JSONArray.

**Comment by stleary** [comment]
@ogronome a couple of questions...
* What should be returned if `Object t` is a String or some other simple type?
* What should be returned if the key does not exist in the JSONObject?
* How should the user handle the case where the JSON document contains a deeply nested structure of objects and arrays?
* Is this function only intended to be used when converting XML to JSON?

It might be helpful to include a complete JavaDoc description along with your proposed function.

**Comment by johnjaylward** [comment]
@stleary I think a case could be made to update the `optJSONArray` method more useful. Currently if the value is not an instance of JSONArray, it just returns `null`. However, I think it would be useful to have single value fields return as single element JSONArray.

Using the example above:
```java
JSONArray array = json.getJSONObject("Response")
    .getJSONObject("Coowners")
    .optJSONArray("Coowner");
```
would return a single element array in this case.

Basically, it would be similar to how the `accumulate` method is working for `put` operations, but on the `get` side instead.

If we are concerned about backwards compatability being an issue, perhaps a pair of new methods called `getAsJSONArray` and `optAsJSONArray` would be acceptable? The `get` version would only throw an exception if the key doesn't exist or is null. The `opt` would always return a JSONArray. On a missing key or `null` value, the JSONArray would be empty.

**Comment by johnjaylward** [comment]
Or if we wanted to note that these are matching methods to `accumulate`, we could call them `getAccumulated` and `optAccumulated`.

**Comment by stleary** [comment]
@johnjaylward Sounds good, no objections to proceeding with a PR. New method names are preferred lest we change the behavior of existing code.

**Comment by johnjaylward** [comment]
@ogronome , do you want to start a PR for this? I'm leaning more towards the `getAccumulated` and `optAccumulated` names, but the `*AsJSONArray` should be fine if you like those better.

**Comment by stleary** [comment]
Closed for lack of activity.
