### ISSUE TITLE
JSONObject should be a new type of orderJSONObject

### ISSUE THREAD

**Issue by yeliang99** [stleary/JSON-java#506]
when we use json to csv, the order need the same as what we put it 
see it .https://stackoverflow.com/questions/4515676/keep-the-order-of-the-json-keys-during-json-conversion-to-csv

**Comment by stleary** [comment]
@yeliang99 Please see the FAQ topic [Why isn't ordering allowed in JSONObjects?](https://github.com/stleary/JSON-java/wiki/FAQ#why-isnt-ordering-allowed-in-jsonobjects). If you need this behavior, you might want to fork the JSON-Java project and replace the JSONObject collection, as is mentioned in the stackoverflow link.

**Comment by johnjaylward** [comment]
@stleary it may make sense to have a params arg of key names that imdicates the order of output

**Comment by johnjaylward** [comment]
Ah, I didn't look at the code before posting my initial comment. It looks like this is already supported in the CDL class.
https://github.com/stleary/JSON-java/blob/master/CDL.java#L273

As mentioned in the SO Question, expecting the order of the keys to be consistent is a non-started for JSON. JSON Objects have no order to the keys. Once you order them it's "not-JSON" and should be considered a custom format.

**Comment by stleary** [comment]
Closing issue for the reasons cited.
