### ISSUE TITLE
strange exception"org.json.JSONException" when running my meven project

### ISSUE THREAD

**Issue by RussiaVk** [stleary/JSON-java#510]
The Exception only happen when run with tomcat,The module referenced by main meven project
`java.lang.ClassNotFoundException: org.json.JSONException
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)`

**Comment by johnjaylward** [comment]
You probably have conflicting dependencies. You should look at your full dependency tree and make sure no otger libraries are pulling in a conflicting json.org package

**Comment by RussiaVk** [comment]
> You probably have conflicting dependencies. You should look at your full dependency tree and make sure no otger libraries are pulling in a conflicting json.org package

The exception were disapear after i put the jar file into tomcat lib folder 
`https://blog.csdn.net/squeen_/article/details/46425331`
