### ISSUE TITLE
Why "</" need to escape?

### ISSUE THREAD

**Issue by looly** [stleary/JSON-java#512]
https://github.com/stleary/JSON-java/blob/6b6e8e85d842bdf397dd8928ed3a9bf747bc7513/JSONObject.java#L1971

```java
case '/':
        if (b == '<') {
            w.write('\\');
        }
```

Why this code need to escape? or append '\\'.

**Comment by johnjaylward** [comment]
It is to prevent script injection for JSON that is embedded directly into HTML without validation

**Comment by johnjaylward** [comment]
Here is a simple explanation: https://www.thorntech.com/2012/07/4-things-you-must-do-when-putting-html-in-json/

And https://stackoverflow.com/a/4180424

**Comment by looly** [comment]
OK，I know, thanks!
