### ISSUE TITLE
Visual Studio Code not recognizing json.org.simple as a dependency

### ISSUE THREAD

**Issue by Snehby** [stleary/JSON-java#514]
Hi, I'm working on a project with 3 other people and they have downloaded and successfully used this package. I am using Visual Studio Code and they are using Eclipse and jGrasp.

However, I keep getting compilation errors for this package:
![image](https://user-images.githubusercontent.com/12602831/80562449-caa33180-89b5-11ea-9c36-4e52ddabcac4.png)

With the Java Dependency Viewer extension I can see that it is recognized and in the right place: 
![image](https://user-images.githubusercontent.com/12602831/80562521-fd4d2a00-89b5-11ea-9a16-e12b9beb7a26.png)

I've also added it to my .classpath file:
![image](https://user-images.githubusercontent.com/12602831/80562655-587f1c80-89b6-11ea-84ad-dfcae85bc69b.png)

Is this the correct place to report this as an issue?
Thanks

**Comment by johnjaylward** [comment]
> Is this the correct place to report this as an issue?

No. This is not the org.json.simple project, and we also don't debug environment issues or do homework for other people.

You should ask your TA or Professor, or a help forum for java issues in Visual Studio Code.
