### ISSUE TITLE
JSONArray does not have constructor to allocate the specified initial capacity

### ISSUE THREAD

**Issue by viveksacademia4git** [stleary/JSON-java#516]
The collection class like ArrayList has the [constructor](https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html#ArrayList-int-) that accepts the number as an input to "Constructs an empty list with the specified initial capacity."  
The absence of this functionality in the JSONArray will not affect the performance of the smaller applications with a fairly limited number of iteration, but the huge applications that involve a large number of iterations will result in the performance trade-off because ArrayList grows or expands numerous times.

**Comment by johnjaylward** [comment]
You are right. If you have a collection you are converting to a JSONArray, this constructor does the trick: https://github.com/stleary/JSON-java/blob/master/JSONArray.java#L171

However, if you are building up from scratch using an input where you can guess the size but not know an exact size, we don't expose a way to do that.

We have a code reorganization going on in PR #515, but a PR to support this should be pretty straightforward.

**Comment by stleary** [comment]
No objection to a pull request for this issue.

**Comment by viveksacademia4git** [comment]
Should I make changes?

**Comment by stleary** [comment]
Yes, please go ahead.

**Comment by viveksacademia4git** [comment]
Thank you @stleary.

**Comment by viveksacademia4git** [comment]
@johnjaylward and @stleary If we implement this constructor then I suppose that we also have to create a method to trim the size of the private ArrayList, like [trimToSize()](https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html#trimToSize--). So the final code would have:
- [x] Constructor - JSONArray(int)
- [x] Method - Trims the size of private ArrayList

What do you think, is it feasible?

**Comment by viveksacademia4git** [comment]
I did not know that [JSON-Java-unit-test](https://github.com/stleary/JSON-Java-unit-test) existed for the purpose of unit testing, I will pull this branch.

**Comment by stleary** [comment]
@viveksacademia4git You have a reasonable use case for the constructor. What is your use case for the method?

**Comment by viveksacademia4git** [comment]
@stleary I do not have any practical use case as of now, but it occurred to me while working: what if someone has a use case which involves trimming the capacity of the underlying data structure.

But as I said before, "is it feasible" at this moment to create this method. Or we could introduce this kind of method if someone has a genuine and practical use case, and creates an issue requesting this functionality.

**Comment by stleary** [comment]
Recommend that you just add the constructor for now.

**Comment by viveksacademia4git** [comment]
Cool!

**Comment by viveksacademia4git** [comment]
@stleary I wasn't able to do the pull request that is why I preferred the fork option.
Please check these commits forked from [JSON-Java](https://github.com/stleary/JSON-java) and [JSON-Java-unit-test](https://github.com/stleary/JSON-Java-unit-test)

- [x] Constructor implementation, [Development for stleary#516 completed](https://github.com/viveksacademia4git/JSON-java/commit/ccb83095c13ebe74324a7763a6d86a8336d5b51f) commit, Fork [JSON-Java](https://github.com/stleary/JSON-java)
- [x] Test for Constructor implementation, [Test for new introduced JSONArray(int) constructor](https://github.com/viveksacademia4git/JSON-Java-unit-test/commit/21dc0477240791e5c88183e73e72d05f1c87bc90) commit, Fork [JSON-Java-unit-test](https://github.com/stleary/JSON-Java-unit-test)

**Comment by viveksacademia4git** [comment]
I wasn't able to run the `gradle test` command but I executed the JUnit Test in Eclipse for the created test

JUnit Test In Eclipse:
![image](https://user-images.githubusercontent.com/45398326/82129370-8213b280-97c2-11ea-94c3-1ee36cdd31dc.png)

Gradle Did not work for me:
![image](https://user-images.githubusercontent.com/45398326/82129390-ad969d00-97c2-11ea-8f6d-4e8489b60309.png)

**Comment by johnjaylward** [comment]
@viveksacademia4git you will need to rebase because of the changes in project structure (or may be easier to just create an new branch and cherry-pick)

once that's done you can use the compare options to create the PR:
![image](https://user-images.githubusercontent.com/383703/83443444-bec4e800-a417-11ea-81a0-7f569bdd4b3d.png)

**Comment by viveksacademia4git** [comment]
Hello @johnjaylward,

I have rebased the project as suggested by you and added the previously written code into it; you may find the changes in the commit [d088cf0](https://github.com/viveksacademia4git/JSON-java/commit/d088cf014e42b75b92d932adac1645840548c76d).

In addition to the above change, I have introduced the pipeline setting for this library in [maven.yml](https://github.com/viveksacademia4git/JSON-java/blob/master/.github/workflows/maven.yml) and executed the pipelines ([see actions](https://github.com/viveksacademia4git/JSON-java/actions)). The pipeline has these stages *maven: (1)compile, (2)test and (3)build* for this library, and they are running successfully. I feel that it could provide an added advantage in terms of CI. I know this is not a part of this issue and I do not know whether it is required from your perspective so please let know whether
 * I should proceed with the pull request for this issue that also includes CI,
 * create another issue for CI
 * or CI is irrelevant as of now and just proceed with the pull request that contains changes for this issue only excluding CI.

**Comment by johnjaylward** [comment]
@stleary I'm OK with the addition of the maven.yml, you?

**Comment by stleary** [comment]
@viveksacademia4git What is the use case for adding CI to this project? Also, please provide an overview of you would go about doing it. 

For the initial capacity PR, let's stick to the agreed-upon changes.

**Comment by viveksacademia4git** [comment]
Okay then, I will do the pull request with the agreed changes only.  
But, you may find the *maven: compile, test and build* report in the pipeline [123544252](https://github.com/viveksacademia4git/JSON-java/actions/runs/123544252)

**Comment by johnjaylward** [comment]
@viveksacademia4git can you create a separate PR that just has the maven.yml changes?

**Comment by viveksacademia4git** [comment]
Sure, I would be happy to do that.

**Comment by stleary** [comment]
Please include text about why this change is needed and a description of the workflow from the point of view of the submitter. FYI, PR merges are on hold until the unit tests are fixed and a few other build problems are addressed.

**Comment by viveksacademia4git** [comment]
Okay, @stleary and @johnjaylward,

I will create the issue once I find that the unit-test issue is resolved.

**Comment by viveksacademia4git** [comment]
Closing this issue, since the code from PR is available in master branch.
