### ISSUE TITLE
Update Wiki

### ISSUE THREAD

**Issue by johnjaylward** [stleary/JSON-java#520]
Wiki needs updates for test locations and contribution guidelines now that the test project has been merged.

**Comment by stleary** [comment]
Proposed organization. This should be completed before the next release.

TOC

**Title**
* quick links

**Overview**
* Description

**Build instructions**
* Java, Maven, Gradle build requirements and examples (move executing unit tests example here)

**Notes**
* (Move text at end of file section to here)

**Writing Unit tests**
* Conventions can be moved here

**Files**
* (move the files table here)

**Release history**
* Where to find releases (maven repo and GitHub release labels)

**Comment by stleary** [comment]
I think the README has been re-written pretty much as needed. There is no TOC or quicklinks, but I think the essentials have been updated. Closing this issue.
