### ISSUE TITLE
Insolvable error: "No value for ..."

### ISSUE THREAD

**Issue by McTom234** [stleary/JSON-java#530]
Hey guys,
I have a big problem with my code due to a JSONException.
I have a JSON message from my server, a custom object and a function that converts the JSON message to my object.

My message from the server looks like this:
`{ "array" : [ { "valueA":"A","valueB":"B" }, { "valueA":"C","valueB":"D" } ] }`

My object has two variables and a constructor to set these variables:
`String a;
String b;
public obj (String a, String b) {
    this.a = a;
    this.b = b;
}`

The function looks like this:
`public void convert(JSONObject a){`
`    for(JSONObject o:a.getJSONArray("array")){`
`        String A = o.getString("valueA");`
`        String B = o.getString("valueB");`
`        obj myObject = new obj(A,B);`
`    }`
`}`

When I execute this code, I get a JSONException: `org.json.JSONException: No value for valueB`.

I searched for the error three times and found nothing. The key string is the same and the value is the expected type.

Do you have a solution for me?
Thanks a lot, McTom

PS: the real code is more complex with 14 parameters, but it is the same way I work with them...

Edit: The code with the error is an Android project in Android Studio. I have tried the same code in Eclipse with normal Java and have no problems. Now I am even more confused.

**Comment by johnjaylward** [comment]
You use the opt funtions instead of get for optional parameters.
