### ISSUE TITLE
JSONObject.objectToBigDecimal precision errors when parsing doubles

### ISSUE THREAD

**Issue by Bohlski** [stleary/JSON-java#531]
When parsing doubles the method uses the BigDecimal(double) constructor, which can have unpredictable results as stated in the docs: https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html#BigDecimal(double)

It is instead preferred to use BigDecimal.valueOf(double)
https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html#valueOf(double)

This lead to a few precision errors on my end, when updating from an older version of this library.

**Comment by johnjaylward** [comment]
@Bohlski which version of the library is currently giving you the issue, the master branch or the latest release on Maven?

**Comment by Bohlski** [comment]
@johnjaylward The latest release on Maven

**Comment by johnjaylward** [comment]
Do you have a test case we can use to reproduce the issue?

**Comment by stleary** [comment]
@Bohlski We will look into these questions:
* Have recent commits resulted in changed behavior, causing problems for lib users?
* When was the change introduced?
* Should the change be reverted?
* Should some other mitigation be provided?

**Comment by johnjaylward** [comment]
I used the test case provided and confirmed that the changes in latest master branch correct the issue.
