### ISSUE TITLE
Bug in new JSON Object parsing through constructor

### ISSUE THREAD

**Issue by BraedonWooding** [stleary/JSON-java#533]
## Problem

When parsing a JSONObject through a constructor using either a JSONTokener or a string it will ignore any extraneous characters at the end of a completed object;

## Example

```java
new JSONObject(" { \"a\":1 }  4"); // will succeed
```

Which is a bit of a contradiction to the tests [here](https://github.com/stleary/JSON-java/blob/6ddaa13c1e2cd870de90d96dc139cf64ea3c583f/src/test/java/org/json/junit/JSONTokenerTest.java#L122) indicating that this should fail.

Cheers

**Comment by johnjaylward** [comment]
You can see here the test case is performing some extra validation that
only a single vale is represented in the input string.

https://github.com/stleary/JSON-java/blob/6ddaa13c1e2cd870de90d96dc139cf64ea3c583f/src/test/java/org/json/junit/JSONTokenerTest.java#L166

The JSONTokener allows multiple values to be separated by white space. It
does not currently have a strict mode

**Comment by BraedonWooding** [comment]
Sure I’m just thinking it’s a bit confusing since the JSON object here will only contain the first value and will ignore the rest.

It’s okay for the JsonTokener to be non strict of course but it does seem that in this specific case it’s much looser allowing invalid chars.

If you still believe it’s not a bug though I’ll be happy to close this.

**Comment by stleary** [comment]
Please see this [Wiki page](https://github.com/stleary/JSON-java/wiki/FAQ#some-invalid-json-text-is-allowed-by-the-parser-shouldnt-this-be-fixed)
