### ISSUE TITLE
Supported builds

### ISSUE THREAD

**Issue by stleary** [stleary/JSON-java#534]
Is there a reason why our Maven builds require Java 1.7, while Gradle requires 1.8? Would it be better if they require the same Java version?

**Comment by johnjaylward** [comment]
I believe it was because the current version of gradle being used only supports Java8+ while the Maven build we tried to ensure works with java6+. However, the Test cases support java7+. If we want the test cases to work on java 6, we will need to refactor some of them to remove java7 features.

**Comment by stleary** [comment]
Thanks, somehow I had thought that the Java 6 compatibility work had already been done.
