### ISSUE TITLE
Objects in collections needs to have override option from reflection-based variable detection

### ISSUE THREAD

**Issue by KimvdLinde** [stleary/JSON-java#544]
adding a collection needs to have an option to use custom made JSONObjects for the elements in the collection instead of the default method and variable reflection based construction of the JSONObject because not everybody wants to push out all variables in the object into JSON to see for everybody.

**Comment by KimvdLinde** [comment]
This is the code I use to override it:

`public JSONObject toJSON() {
		JSONObject collection = new JSONObject();
		this.keySet().forEach((key) -> {
			collection.put(key.toString(), ((AgObject) this.get(key)).toJSON());
		});
		return collection;
	}`

**Comment by johnjaylward** [comment]
This project supports an interface [JSONString](https://github.com/stleary/JSON-java/blob/master/src/main/java/org/json/JSONString.java) which I believe will do what you want assuming you have source control over the objects in the collection.

Were you looking for something different?

**Comment by KimvdLinde** [comment]
No, I am putting out an JSONObject, not a string (yet).

**Comment by johnjaylward** [comment]
An example implementation using the `JSONString` interface may look something like this:

```java
public class MyPoJo implements org.json.JSONString {
  private String someField; // pretend getters and setters
  private int someOtherField; // pretend getters and setters
  private ZonedDateTime aDate; // pretend getters and setters
  
  @Override
  public String toJSONString() {
    // notice the lack of "someOtherField"
    return "{" + "\"someField\":" + JSONObject.quote(this.someField) + ",\"aDate\":\"" + JSONObject.quote(formatMyDate()) + "\"}";
  }

  private String formatMyDate() { /* some implementation that formats your date a specific way */ }
}

// then somewhere else in code:
Collection<MyPoJo> cMP = getACollectionFromSomewhere();

JSONArray ja = new JSONArray(cMP); // at this point, the items in the JSONArray are still MyPoJo, not a string or JSONObject
// if you want you can still work with the POJO through the JSONArray

// the folowing will cause the `MyPoJo.toJSONString` to be called for each MyPoJo in the list
// the output will be as you expect with the POJO formatted as we customized.
return ja.ToString(); 
```

Does something like this accomplish what you are trying to do, or do you need to work with actual JSONObjects?

**Comment by johnjaylward** [comment]
@stleary can you add the above example to the Wiki somewhere? maybe make an examples page?

**Comment by KimvdLinde** [comment]
I need the actual objects because I add them to other objects and if I use string it does not render correctly

**Comment by johnjaylward** [comment]
Are you unable to add the original POJO? i.e. something like this:

```
// assume the same POJO implementation above

Collection<MyPoJo> cMP = getACollectionFromSomewhere();

JSONObject jo = getJSONObjectFromSomewhere();

MyPoJo mpj = cMP.stream.filter(p -> p.someOtherValue = 5).getFirstOrDefault();
if (mpj != null) {
    jo.put("pojo5",mpj);
}

mpj = cMP.stream.filter(p -> p.someOtherValue = 15).getFirstOrDefault();
if (mpj != null) {
    jo.put("pojo15",mpj); // add the POJO as the MyPoJo class, not a JSON Object
}

// this will output the `jo` with the 2 found POJO under keys `pojo5` and `pojo15`.
// Both pojo will be output using the `toJSONString` method. 
return jo.toString();
```

**Comment by KimvdLinde** [comment]
The above solution that I posted works brilliantly for me, so I just use that. Just was thinking that if the put(map) method would recognize a specific function to override the default, that would be an easy way to simplify the code for many.

**Comment by johnjaylward** [comment]
for full disclosure, I use a similar solution as @KimvdLinde  in my own copy of this library. Mine looks like
```java
public interface JSONSerializable {
    JSONObject toJson(final int recursionDepth) throws JSONException;
}
```

However, due to the presence of the `JSONString` interface in the main library I never felt comfortable bringing it over to here. For example, what if something like this were done:

```java
public class A implements JSONString {
   public String toJSONString(){
       // some implementation
   }
}

public class B extends A implements JSONSerializable {
   public String toJson(final int recursionDepth){
       // some implementation
   }
}


JSONObject jo = new JSONObject();
jo.put("myB", new B());
jo.toString();
```

Which output should be used? From the writer side we would need some kind of precedence ordering to decide if the writer calls `toJSONString` or `toJSON`. We could use reflection and try to figure out which it closest to the object being written, but that can be an expensive call which could significantly slow down the writer. Or we could always make it a convention that since we are outputing a JSON String, the `toJSONString` method would be called first, otherwise `toJSON().toString()` would be called. This could cause some odd "bugs" in code though if someone was expecting a field in Object `B` to be output, but only object `A` was.

I'm not against adding in a new interface, but I do feel like it could lead to some ambiguity.

**Comment by KimvdLinde** [comment]
I would say that toJSONstring is when it leaves the JSON package (print.out for example) and toJSON when adding to a JSONObject

**Comment by johnjaylward** [comment]
so something like this?:
```java
JSONObject jo = new JSONObject();
B myB = new B();
jo.put("someKey", myB); // calls `B.toJson()` internally so long as B implements the interface

jo.toString(); // `someKey` is already a JSONObject, so there would be no direct call to `toJSONString` on the B object.
```

In essence, the `toJson` method would take precedence.

**Comment by KimvdLinde** [comment]
Exactly.

**Comment by KimvdLinde** [comment]
The benefit is that this is actually a much faster implementation that the reflection based current implementation.

**Comment by johnjaylward** [comment]
@stleary any thoughts on the proposed interface? Is it something you feel is addable to the library?

I think the simpler method that @KimvdLinde suggested (`toJSON()`) would be a better candidate as it's easier to call internally. For my interface (`toJSON(int recursionDepth)`), I end up having methods on the JSONObject and JSONArray dedicated to the interface that looks like this (maybe... working from memory):

```java
// JSONObject.java

public JSONObject put(string key, JSONSerializable o, int recursionDepth) {
  if (key == null) throw JSONException("Key can not be null");
  if (value == null) {
    this.remove(key);
    return this;
  }
  return this.put(key, o.toJSON(recursionDepth));
}

// JSONArray.java

public JSONArray put(JSONSerializable o, int recursionDepth) {
  return this.put(o.toJSON(recursionDepth));
}
```

With the simpler method proposed by @KimvdLinde, we don't need any specialized functions and just add cases to the receivers that take Object as their value parameter.

**Comment by stleary** [comment]
@johnjaylward not sure yet.
OP reports he has a workaround, so why does this package need to solve the problem? 
On the other hand, I do recognize that the JSONObject bean API may not be a good solution for everyone.
Will the JSONPropertyName annotation not help here?

**Comment by KimvdLinde** [comment]
You can use those I guess. With those, I would have to address each possible public variable to have them names or ignored properly. I think my solution is easier and faster as it eliminates a lot of reflection.

**Comment by stleary** [comment]
Easier to use is a valid reason. 
What if the class already has a toJson() method, and the code starts behaving in an unexpected manner when the new API is introduced?

**Comment by KimvdLinde** [comment]
That is a concern definitely. I've not immediately a good solution to that.

**Comment by stleary** [comment]
To ensure we are on the same page:
Developers who can modify POJO definitions should have optional control over how Java object instances (beans) are parsed to JSON.
JSONString class and JSONPropertyName annotation are not good existing alternatives.
A special-purpose public method could be called to allow the instance to produce its own JSONObject.
The method could be accessed by the parser either through reflection or via an interface.
The method name toJSON() should not be used, to avoid the possibility of collision with existing methods.

**Comment by KimvdLinde** [comment]
I think that is a good summary and agreed. We just have to figure out a good method name that won't cause implementation issues, something like getOverrideJSONObject()....

**Comment by johnjaylward** [comment]
I don't think we need to worry about the method name as much as the interface name. I'd prefer if we didn't use the `get` prefix though, as that could cause issues with some reflection tools that may look for properties based on the prefix. I think the `to` prefix would be preferred.

Either `toJSON` or `toJSONObject` should be fine. There should be no naming conflicts as long as no one else has made an interface in the `org.json` namespace.

I'd expect whatever interface we decide on to have a single definition like this:
```java
package org.json
/**
 * Interface the indicates to the @{link JSONObject} and @{link JSONArray} put methods
 * that the object should be converted to JSON in a specific manner. An object that implements
 * this interface and is added to a JSONArray or JSONObject will be converted to a JSONObject
 * immediately.
 */
public interface ?SomeInterfaceName? {
    /** 
     * Generates a custom @{link JSONObject} representation of this object. The implementation
     * should ensure structure is acyclical.
     * 
     * @return A custom @{link JSONObject} representation of this object.
     */
    JSONObject toJSONObject();
}
```

Would something like this ever be needed? I'm leaning towards **NO** as I believe most people would implement the one of the collection interfaces (Collection<T>, List<T>, Set<T>) which would make this a bit redundant.
```java
/**
 * Interface the indicates to the @{link JSONObject} and @{link JSONArray} put methods
 * that the object should be converted to JSON in a specific manner. An object that implements
 * this interface and is added to a JSONArray or JSONObject will be converted to a JSONArray
 * immediately.
 */
public interface ?SomeInterfaceName? {
    /** 
     * Generates a custom @{link JSONArray} representation of this object. The implementation
     * should ensure structure is acyclical.
     *
     * @return A custom @{link JSONArray} representation of this object.
     */
    JSONArray toJSONArray();
}
```

**Comment by stleary** [comment]
@johnjaylward  Thanks for clarifying. Agree that toJSONArray() is not needed. No objection to proceeding with toJSONObject().

**Comment by KimvdLinde** [comment]
I concur.

What we need to add is code in the reflection component to pick up this function if present.

**Comment by stleary** [comment]
Wiki page added:
https://github.com/stleary/JSON-java/wiki/Tech:-How-to-complete-solve-specific-problems-in-your-JSON-Java-code#objects-in-collections-need-to-have-override-option-from-reflection-based-variable-detection
