### ISSUE TITLE
Readme or wiki update for XML parsing

### ISSUE THREAD

**Issue by stleary** [stleary/JSON-java#545]
Review the readme and wiki to ensure there is sufficient explanation for how to do XML / JSON conversions.

**Comment by Avimathu** [comment]
Hi, I would want to take up this issue, but may you please elaborate the issue? It's still unclear that do we need to update the existing parsing of XML or do we need to add a file for paring XML. Thanks in advance!

**Comment by stleary** [comment]
@Avimathu This is not a code issue, XML parsing is already supported. The idea here is to create a new file docs/XML.md that explains how to use the XML parsing objects, the tradeoffs made, and how to work around them. 
From your comment, it sounds like you want to write code. If that is the case, another issue might be a better match.

**Comment by stleary** [comment]
Wiki is updated, no code review needed.
