### ISSUE TITLE
Empty JSON array cannot be loaded in

### ISSUE THREAD

**Issue by MisterVector** [stleary/JSON-java#548]
With the following code:

```
    public static void loadCustomServerTypesFromJSON(JSONObject dataJson) {
        if (dataJson.has("custom_server_types")) {
            JSONArray customServerTypesJson = dataJson.getJSONArray("cusotm_server_types");
            
            for (int i = 0; i < customServerTypesJson.length(); i++) {
                JSONObject customServerTypeJson = customServerTypesJson.getJSONObject(i);
                customServerTypes.add(CustomServerType.fromJSON(customServerTypeJson));
            }
        }

```
And given a text representation of JSON thus:

```
{
    "custom_server_types": []
}
```

I receive the following error when attempting to load an empty array:

![image](https://user-images.githubusercontent.com/437096/88419701-7af8ba00-cd9a-11ea-933f-fd7242c99973.png)

I'm wondering if this is intentional that empty JSON arrays cannot be loaded. I have no problems checking for a JSONException and ignoring if that's the case if this issue cannot be resolved.

**Comment by MisterVector** [comment]
Whoops, I think there was a mistake on my part. Not sure what I did but it loads in an empty JSON array now. Disregard this!

**Comment by johnjaylward** [comment]
I think you have a different error. I'm not able to reproduce this with the following test case:

```java
    public void testIssue548ObjectWithEmptyJsonArray() {
        JSONObject jsonObject = new JSONObject("{\"empty_json_array\": []}");
        assertTrue("missing expected key 'empty_json_array'", jsonObject.has("empty_json_array"));
        assertNotNull("'empty_json_array' should be an array", jsonObject.getJSONArray("empty_json_array"));
        assertEquals("'empty_json_array' should have a length of 0", 0, jsonObject.getJSONArray("empty_json_array").length());
    }
```

Be sure to use debugging and set a breakpoint in your code, or add in log messages. The main reason I suspect this is that your code is using the `has` method before the `get`. It seems to me like you may have a multithreaded problem here where something is removing the key after the `has` method reports the key exists, but before the `get` fetches the value.

Another suggestion would be to use the `optJSONArray` method directly like this:
```java
public static void loadCustomServerTypesFromJSON(JSONObject dataJson) {
    JSONArray customServerTypesJson = dataJson.optJSONArray("cusotm_server_types");
    if (customServerTypesJson != null) {
        for (int i = 0; i < customServerTypesJson.length(); i++) {
            JSONObject customServerTypeJson = customServerTypesJson.getJSONObject(i);
            customServerTypes.add(CustomServerType.fromJSON(customServerTypeJson));
        }
    }
}
```
