### ISSUE TITLE
how to transfer xml to jsonArray rather than jsonObject

### ISSUE THREAD

**Issue by LibralCoder** [stleary/JSON-java#550]
`<Student><name>jack</name><subjects><item><class>english</class><grade>98</grade></item></subjects></Student>`
like this, I want to transfer the item  entry  to jsonArray ,but actually  the result is a jsonObject.
Can you help me ?

**Comment by LibralCoder** [comment]
`<Student><name>jack</name><subjects><item><class>english</class><grade>98</grade></item><item><class>english</class><grade>98</grade></item></subjects></Student>`
What should I do if I expect the List name of multiple items to refer directly to its parent tag instead of its own tag？
My English is very poor, can you understand what I said？
I expect case like this
`{"Student": {
    "subjects": [
        {
            "grade": 98,
            "class": "english"
        },
        {
            "grade": 98,
            "class": "english"
        }
    ],
    "name": "jack"
}}`

**Comment by johnjaylward** [comment]
XML to JSON is generally a messy topic. Often, it doesn't work perfectly or cleanly unless you plan both structures out in advance, or leave them very simple.

Our XML -> JSON parser/converter accumulates common XML elements, so your existing XML:
```xml
<Student>
  <name>jack</name>
  <subjects>
    <item><class>english</class><grade>98</grade></item>
    <item><class>english</class><grade>98</grade></item>
  </subjects>
</Student>
```
Would end up looking like this:
```json
{
  "Student": {
    "subjects": {
      "item": [ { "grade": 98, "class": "english" }, { "grade": 98, "class": "english" } ]
    },
    "name": "jack"
  }
}
```

If you have control over the XML generation, then you could do something like this to get the JSON you want:
```xml
<Student>
  <name>jack</name>
  <subjects>
    <class>english</class><grade>98</grade>
  </subjects>
  <subjects>
    <class>english</class><grade>98</grade>
  </subjects>
</Student>
```

Which should result in the JSON you showed above:
```json
{
  "Student": {
    "subjects": [
      { "grade": 98, "class": "english" },
      { "grade": 98, "class": "english" }
    ],
    "name": "jack"
  }
}
```

**Comment by johnjaylward** [comment]
another caveat to note, is that due to accumulating common elements, if you only have a single "subjects" element, then your json `subjects` will be an object, not an array:
```xml
<Student>
  <name>jack</name>
  <subjects>
    <class>english</class><grade>98</grade>
  </subjects>
</Student>
```
Results in JSON:
```json
{
  "Student": {
    "subjects": { "grade": 98, "class": "english" },
    "name": "jack"
  }
}
```

**Comment by LibralCoder** [comment]
haha , you repeat my requestion

**Comment by johnjaylward** [comment]
No, that's the answer. The parser doesn't have a way to tell if an element is an array as it is not schema-aware even if you provide one in the `<xml ... ` tag.

Some example code for handling a document similar to yours would be something like this:
```java
void someFunction() {
  JSONObject jo = XML.toJSONObject(someXmlSource);
  JSONObject student = jo.getJSONObject("Student");
  if ( student.optJSONArray("subjects") ==null ) {
      processSubject(student.optJSONObject("subjects"));
  } else {
      processSubjects(student.optJSONArray("subjects"));
  }
}

void processSubjects(JSONArray subjects) {
  if (subjects == null || subjects.length() == 0) return;
  for(int i=0; i<subjects.length; i++) {
    processSubject(subjects.getJSONObject(i));
  }
}

void processSubject(JSONObject subject) {
  // some implementation
}
```

**Comment by LibralCoder** [comment]
I know it's going to look something like this

> No, that's the answer. The parser doesn't have a way to tell if an element is an array as it is not schema-aware even if you provide one in the `<xml ... ` tag.
> 
> Some example code for handling a document similar to yours would be something like this:
> 
> ```java
> void someFunction() {
>   JSONObject jo = XML.toJSONObject(someXmlSource);
>   JSONObject student = jo.getJSONObject("Student");
>   if ( student.optJSONArray("subjects") ==null ) {
>       processSubject(student.optJSONObject("subjects"));
>   } else {
>       processSubjects(student.optJSONArray("subjects"));
>   }
> }
> 
> void processSubjects(JSONArray subjects) {
>   if (subjects == null || subjects.length() == 0) return;
>   for(int i=0; i<subjects.length; i++) {
>     processSubject(subjects.getJSONObject(i));
>   }
> }
> 
> void processSubject(JSONObject subject) {
>   // some implementation
> }
> ```

Can you add some filters to the conversion process?For example, set some specific tag to indicate that it is a collection rather than a singleton.

**Comment by johnjaylward** [comment]
I this having a getter on the JSONObject may be better. Something like this:
```java
// always returns a JSONArray, If the key doesn't exist, the array will be empty.
// If the key holds a non-array/non-collection value, then it is placed in a JSONArray
// before returning.
// If the value is a JSONArray, then it is directly returned,
// directly convertible to a JSONArray (i.e. a JAVA Array or Collection), then it is
// converted to a JSONArray.
jo.optAccumulated("someKey");

**Comment by LibralCoder** [comment]
Threre is a sample  lib in github  which named XmlToJson.it not suitabled to me because it's build in gradel.
I have tried using dom4j but it needs to redefine the parsing rules every time, which is not universal enough. So I want to find a maven library that converts xml to json

**Comment by LibralCoder** [comment]
public class Aim {
    private static final String xmlStr =
            "<Student><name>jack</name><subjects><profile><item><class>english</class><grade>98</grade></item></profile></subjects></Student>";

    public static void main(String[] args) {


        JSONObject jo = XML.toJSONObject(xmlStr);

        ParserConfig parserConfig = new ParserConfig("Student", CollUtil.newArrayList("subjects/profile/item"));


        JSONObject rooObject = jo.getJSONObject(parserConfig.getRoot());
        List<String> listTags = parserConfig.getListTag();
        for (String listTag : listTags) {
            String[] spans = listTag.split("/");
            JSONObject currentStash = rooObject;
            JSONObject lastStash = null;
            for (int i = 0; i < spans.length; i++) {
                if (i == spans.length - 1) {
                    Object obj = currentStash.opt(spans[i]);
                    if (null == obj) {
                        break;
                    }
                    if (obj instanceof JSONObject) {
                        lastStash.put(spans[i-1],new JSONArray().put(obj));
                    } else {
                        lastStash.put(spans[i-1],obj);
                    }
                }
                lastStash = currentStash;
                JSONObject opt = currentStash.optJSONObject(spans[i]);
                if (null == opt) {
                    break;
                }

                currentStash = opt;
            }
        }
        System.out.println(rooObject.toString());
    }

    static class ParserConfig {
        private String root;
        private List<String> listTag;

        public ParserConfig(String root, List<String> listTag) {
            this.root = root;
            this.listTag = listTag;
        }

        public String getRoot() {
            return root;
        }

        public void setRoot(String root) {
            this.root = root;
        }

        public List<String> getListTag() {
            return listTag;
        }

        public void setListTag(List<String> listTag) {
            this.listTag = listTag;
        }
    }
}

**Comment by LibralCoder** [comment]
I wrote a parser inspired by you. Thank you very much.

**Comment by LibralCoder** [comment]
good bye my senior，I'm going to bed.

**Comment by stleary** [comment]
Closed due to resolved by other means.
