### ISSUE TITLE
GitHub actions do not support Maven builds using Java 1.6?

### ISSUE THREAD

**Issue by stleary** [stleary/JSON-java#553]
Tried updating pipeline.yml to include 1.6 JUnit tests and report, but the new step fails. The error message suggests that the Maven version does not support 1.6. Please post here if you know of a way to get it working, or can confirm that it cannot be made to work.

**Comment by johnjaylward** [comment]
I definitely had problems getting compilation working in a java 6 environment. That was why I split it off to it's own task-set and just ran the java commands directly without Maven or Gradle.

One option may be to add a couple new steps which would manually compile the tests and run them manually, but you would probably need to reinstate these deleted files : https://github.com/stleary/JSON-java/commit/c11c006e880f1499a08abea78494d8f9ad613346#diff-188c4a4186ae6ee1c99789d0dd5248bf

The reason it was deleted was to prevent duplicate runs of tests in IDE environments.

Or it may just be time to drop Java 6 support if we can't effectively test it anymore.

**Comment by johnjaylward** [comment]
The documentation I used for the actions was here: https://github.com/marketplace/actions/setup-java-jdk

**Comment by johnjaylward** [comment]
looks like there is an open PR to allow specific Maven/Gradle versions in the actions: https://github.com/actions/setup-java/pull/42

If they accept that, we should be able to update the runner to use a supported Maven version for Java6

**Comment by johnjaylward** [comment]
@stleary one of the comments in the PR I linked mentions "Actions" for setting up both gradle and maven:
* https://github.com/marketplace/actions/setup-maven
* https://github.com/marketplace/actions/gradle-command

Check those out and see if you can get it to work as expected for Java6

**Comment by stleary** [comment]
@johnjaylward Thanks for the explanation and links, this is very helpful. 1.6 CI test support is not critical, will keep pipeline.yml unchanged for now.
