### ISSUE TITLE
Garbage at end of JSON data does not fail parsing

### ISSUE THREAD

**Issue by durpy-durpy** [stleary/JSON-java#556]
Hello,

I don't suspect this is the intended behavior but extra characters at the end of an enclosed JSON object string do not lead to a failure in parsing. Using the instructions in the README I built the library from the tip and tested with almost the same `Test.java` but with a minor change:

```
import org.json.JSONObject;
public class Test {
    public static void main(String args[]){
       JSONObject jo = new JSONObject("{ \"abc\" : \"def\" }junk");
       System.out.println(jo.toString());
    }
}
```
where `junk` is appended. The output is still the same:

`{"abc":"def"}`

and I would have expected the construction of `JSONObject` to throw a `JSONException`.

Thanks!

**Comment by johnjaylward** [comment]
That is as designed

**Comment by durpy-durpy** [comment]
Thanks for the quick reply! How do I validate the input, i.e., that a given blob of text is valid JSON? Is there a mechanism in the API I'm not seeing?

**Comment by johnjaylward** [comment]
No, at this time there is no Strict Mode for the parser. Per the json specifications, the parser is allowed to accept invalid json. As mentioned in the README.md, there are other cases that this parser allows which are not stictly allowed in json documents.

Output from this library will always strictly conform.

**Comment by durpy-durpy** [comment]
Alrighty. Thanks for confirming.
