### ISSUE TITLE
Jar is converting XML elements containing 'E' in the value to numbers

### ISSUE THREAD

**Issue by sultanahaziq** [stleary/JSON-java#557]
Jar is converting XML elements containing 'E' in the value to numbers. for example, if a XML is like:
XML Message : <testMsg xmlns="http://www.test.com/sample/xml"><StrWithEInIt>0E42</StrWithEInIt></testMsg>
XML to JSON : {"testMsg":{"xmlns":"http://www.test.com/sample/xml","StrWithEInIt":0}}

			JSONObject jsonObject = XML.toJSONObject(testMsg);

**Comment by johnjaylward** [comment]
That is the default behavior. You can change it by passing an https://github.com/stleary/JSON-java/blob/master/src/main/java/org/json/XMLParserConfiguration.java instance which is set to "keepStrings: true"

**Comment by stleary** [comment]
Closed due to answer provided.
