### ISSUE TITLE
A new method to retain the required keys and drop the remaining.

### ISSUE THREAD

**Issue by Mahesharvinds** [stleary/JSON-java#560]
I faced a use case during my development, where I use a third party Rest API to fetch a resource from my server and modify it to enable my client to consume the result without having to make many changes. 
For instance,
The Third Party API provides the JSON { "class-name" : "myclass" , "param1" : "long"  , "returns" : "int" }
My client needs only these {"class-name" : "myclass" , "param1" : "long"} in the result JSON. 
So I will have to parse the result from third party and construct a new json. Instead a method retainGiven(keys) will be helpful.

**Comment by johnjaylward** [comment]
We have a constructor at the moment that can do that:
```java
JSONObject jo = new JSONObject(new JSONObject(input), "class-name" , "param1");
```
It would require building 2 JSONObjects, but one would be thrown away once the required parameters are kept.

**Comment by Mahesharvinds** [comment]
Is it possible to achieve the negation ? I mean drop the given keys ? @johnjaylward

**Comment by johnjaylward** [comment]
I mean, you can just remove them after parsing. Removal can be done one of 2 ways:
1. Assign java `null` to the key(s). This library treats java null as javascript `undefined`, so the key will be removed
1. Call the `remove` method directly for each key

Option 1 example:
```java
public void removeInvalidKeys(JSONObject jo) {
  string[] keysToRemove = new String[] { "key1", "key2" }; // maybe make this a member variable, or an additional parameter
  for(String key : keysToRemove) {
    jo.put(key, null);
  }
}
```

Option 2:
```java
public void removeInvalidKeys(JSONObject jo) {
  string[] keysToRemove = new String[] { "key1", "key2" }; // maybe make this a member variable, or an additional parameter
  for(String key : keysToRemove) {
    jo.remove(key);
  }
}
```
