### ISSUE TITLE
How use the json library

### ISSUE THREAD

**Issue by MBENKI** [stleary/JSON-java#567]
Hello i am new to programming, i would like to ask how can i install properly the library, i prefer not using dependency managers like Maven or anything else (simply because i have no idea how it works and i got to use a piece of code on raspberry), is there a .jar file for the library?
Please if can anyone can help me.

**Comment by GedMarc** [comment]
Ok I'll entertain,

Your preference is wrong, any language you have to use a dependency manager. Pick one, maven grade ant custom private built, that's not something you're going to get away from no matter what you do.

If you want a jar, go into maven repository or site and download it.

**Comment by MBENKI** [comment]
Thank you @GedMarc, yes i just downloaded the jsr file, but you're right i''l learn Gradle and Maven or ant ... seems unavoidable indeed

**Comment by GedMarc** [comment]
sadly so, need to have the "don't need to understand it to use it" :)
keep in mind though
* C# it's nuget/npm
* JS it's bower and npm
* ruby its rubygems

Every language, maybe not C - when you start writing programs a little larger and a bit more real-world, it'll all make sense

**Comment by MBENKI** [comment]
That's very helpful @GedMarc thank you i will keep this in mind, i was suffering and getting lost very quickly because i refused to use things and don't have a grasp on, i find myself always trying to understand but with not much success. 

> "don't need to understand it to use it" mentality :)
this is so true
