### ISSUE TITLE
Support creation of root arrays

### ISSUE THREAD

**Issue by holgerbrandl** [stleary/JSON-java#572]
With the current API root arrays can not be created (or it's unclear how to do so).
```
[ {"foo1":"bar1"}, {"foo2":"bar2"} ]
```

Relates to https://github.com/holgerbrandl/jsonbuilder/issues/1

**Comment by johnjaylward** [comment]
```java
JsonArray my art = new JsonArray("[ {\"foo1\":\"bar1\"}, {\"foo2\":\"bar2\"} ]");
```

**Comment by holgerbrandl** [comment]
Thanks for your kind support and sorry for the tracker spam.
