### ISSUE TITLE
Length of key in JSONObject.java should be checked

### ISSUE THREAD

**Issue by ek08** [stleary/JSON-java#582]
I was doing a case study on JSON-java with the checker framework (https://checkerframework.org/) . I performed the index checker
(https://checkerframework.org/manual/#index-checker) .
### Steps to compile :
javacheck -cp $ADD -processor index $MYPATH/*.java 

javacheck is aliased as shown in the manual https://checkerframework.org/manual/#javac-wrapper

$ADD= path-to-JSON-java
$MYPATH=path-to-jOOU/src/main/java/org/json/*.java

For me the command is 
$ javacheck -cp Desktop/CODING/JSON-java-master -processor index  Desktop/CODING/JSON-java-master/src/main/java/org/json/*.java

#### The output for the particular line after compiling is :
[argument.type.incompatible] incompatible argument for parameter index of charAt.
        if (Character.isLowerCase(key.charAt(0))) {
                                             ^
  found   : @UpperBoundUnknown int
  required: @LTLengthOf("key") int
  
  If I change the line to  if (key.length() > 0 && Character.isLowerCase(key.charAt(0))) 
The compiler issues no error for the particular line.

**Comment by johnjaylward** [comment]
If you look at lines 1550 through 1557, you will see that the key can never be null or 0 length

**Comment by stleary** [comment]
@ek08 No objection if you want to change the code for the sake of a clean JavaCheck run, as long as there is no behavior change.

**Comment by ek08** [comment]
Alright so should I submit a PR by changing that line?

**Comment by stleary** [comment]
I think that change should be OK. You can submit the PR and see if anyone raises an objection.

**Comment by ek08** [comment]
Created a PR .
