### ISSUE TITLE
Length of String e in unescapeEntity(String e) method should be checked before parsing

### ISSUE THREAD

**Issue by ek08** [stleary/JSON-java#584]
The length of String e in the  unescapeEntity( String e) should be checked in line 170 in XMLTokenerClass , because if the value of e is  "#" then there may be an issue.
The line 
```
 if (e.charAt(1) == 'x' || e.charAt(1) == 'X') {
```
may be changed to 
```
            if ((e.length() >1) && (e.charAt(1) == 'x' || e.charAt(1) == 'X')) {
```

**Comment by johnjaylward** [comment]
Can you make a test case to demonstrate?

**Comment by ek08** [comment]
```
class Test {
	public static void main(String[] args) {
		String result = unescapeEntity("#");
		System.out.println(result);
	}
	static String unescapeEntity(String e) {
			// validate
			if (e == null || e.isEmpty()) {
					return "";
			}
			// if our entity is an encoded unicode point, parse it.
			if (e.charAt(0) == '#') {
					int cp; // change in the code in the next line
					if (e.charAt(1) == 'x' || e.charAt(1) == 'X') {
							// hex encoded unicode
							cp = Integer.parseInt(e.substring(2), 16);
					} else {
							// decimal encoded unicode
							cp = Integer.parseInt(e.substring(1));
					}
					return new String(new int[] {cp},0,1);
				}
				else {
					return "Test";
				}
			}
		}
```
Running javac Test.java gives no error , 
but running java Test the output is 
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at Test.unescapeEntity(Test.java:13)
	at Test.main(Test.java:3) 

Now changing the line if (e.charAt(1) == 'x' || e.charAt(1) == 'X') to  if ((e.length() >1) && (e.charAt(1) == 'x' || e.charAt(1) == 'X')) gives NumberFormatException. So I can conclude that this check may be redundant.

Please correct me if I misunderstood something.

**Comment by johnjaylward** [comment]
No, I meant a test case usuing the public apis. Not a direct call to the
internal method

**Comment by ek08** [comment]
I am having a problem in writing test case by using the public api . I would be grateful if someone helps me out .

**Comment by ek08** [comment]
Also in JSONWriter class in line 216 the array access can be negative.
```
 JSONObject topObject = this.stack[this.top - 1];
```
top is initialized to 0 initially.

**Comment by johnjaylward** [comment]
> I am having a problem in writing test case by using the public api . I would be grateful if someone helps me out .

My guess is that the values are protected against incorrect values from the calling methods. since the `unescapeEntity` is not public, it is expecting to work with a specific set of data. Specifically, it expects to work with strings that have the correct properties.


> Should I raise a new issue for this?

Yes please. If you can show a test case for it as well, that will help fix any issue. This this is a public method, I expect it will be easy to generate a test case.

**Comment by ek08** [comment]
> ```
>  if (e.charAt(1) == 'x' || e.charAt(1) == 'X') {
> ```
> 
> may be changed to
> 
> ```
>             if ((e.length() >1) && (e.charAt(1) == 'x' || e.charAt(1) == 'X')) {
> ```
If I change the code here will it bring any change in the functionality cuz changing me for java check using Checker Framework.
I don't think that this changes any functionality.
Please correct me if I am wrong.

**Comment by stleary** [comment]
>>>I am having a problem in writing test case by using the public api . I would be grateful if someone helps me out .
>>>I am not able to build the project

There are instructions in the readme on how to build the project and execute the unit tests. If this is not working for you, or if your setup is different, post the details here and we can try to work through them.

**Comment by ek08** [comment]
Yeah the build is successful now . I have tried with some examples I found.

**Comment by johnjaylward** [comment]
it will affect performance as adding code that does nothing always affects performance.

If you can, just use whatever "ignore" options are available in "Java Checker Framework" to note that it's not an issue.

**Comment by johnjaylward** [comment]
specifically from the checker framework manual section 2.4.5 https://checkerframework.org/manual/ :

> Do not add an if test that can never fail, just to suppress a warning. Adding a gratuitous if clutters the code and confuses readers. A reader should assume that every if condition can evaluate to true or false. It can be acceptable to add an if test that throws a descriptive error message.
