### ISSUE TITLE
JSONArray interpretes [$0$] as a correct JSON Array

### ISSUE THREAD

**Issue by arneboockmeyer** [stleary/JSON-java#591]
Hi guys,

when I'm running the code:
`JSONArray arr = new JSONArray("[$0$]");`
the constructor returns a valid JSON array with one object. (Println produces `["$0$"]`.)

Running the same example (`[$0$]`) in different validators and looking at the JSON standard (https://www.json.org/json-en.html) I think, the code above should produce an error.

What do you think?

**Comment by johnjaylward** [comment]
According to the JSON spec, parsers are allowed to be more lenient than generators. Our parser allows unquoted keys and values.

**Comment by arneboockmeyer** [comment]
Thanks for the quick response! I also just saw your hint in the FAQ, sorry for the inconvenience.
