### ISSUE TITLE
how to make a pretty-printed XML text from JSONObject?

### ISSUE THREAD

**Issue by xiejx618** [stleary/JSON-java#593]
org.json.JSONObject#toString(int) has an indentFactor parameter, but org.json.XML.toString does not have an indentFactor parameter

**Comment by stleary** [comment]
No objections if you want to submit a PR with support for formatted XML output. If you do so, recommend that you use JSONObject.toString(int) as a model, if possible.

**Comment by DeaneOC** [comment]
I am going to look into this.

**Comment by Avimathu** [comment]
Hi! I am going to look into this issue

**Comment by javadev** [comment]
https://github.com/stleary/JSON-java/pull/694 was merged. Issue may be closed.

**Comment by stleary** [comment]
Closed due to work being completed in #694
