### ISSUE TITLE
New logo for the project

### ISSUE THREAD

**Issue by IsmaelP19** [stleary/JSON-java#598]
As we have seen the project doesn't have any logo yet, we have created a sketch and suggested it as an improvement.
![image](https://user-images.githubusercontent.com/79575588/113017175-7b462200-917f-11eb-9ef3-4e4863600454.png)

**Comment by GedMarc** [comment]
i think getting JDK11 compatible has a much higher priority than an image on a finished project, #justsaying

**Comment by migromarj** [comment]
> i think getting JDK11 compatible has a much higher priority than an image on a finished project, #justsaying

I think you are right, but from my point of view having your own logo is very important because it gives users a first impression of your product, and obviously that impression should be good.

**Comment by GedMarc** [comment]
its the RI release for the json standard - it should have the same branding as everything else RI that follows the scripted standard,

Being none.

It's not a product

**Comment by GedMarc** [comment]
Try to better understand the term "Not for profit",
Thanks.

**Comment by stleary** [comment]
@IsmaelP19 The basic design looks good and I would like to use it for this project. Would you mind removing the JSON 'O' and Oracle coffee cup images, and just provide the text?  If you want to replace either with a different image of your own design, that would be fine too.

**Comment by Tacodude7729** [comment]
![image](https://user-images.githubusercontent.com/27910867/115227760-3e54c600-a154-11eb-98db-8aec996616af.png)
Thought I'd throw my hat into the ring with this design. Thoughts?

**Comment by stleary** [comment]
@IsmaelP19 Can you please update your design to remove the borrowed images?
@Tacodude7729 Thanks for submitting your design.

**Comment by IsmaelP19** [comment]
I'm sorry I couldn't answered you before, but I was really busy.
I made the logo again to improve the quality of the image, removing the JSON 'O' and the Oracle's coffee cup images.
![Logo-no-marks](https://user-images.githubusercontent.com/79575588/115858069-ca097380-a42e-11eb-84ee-df39793b1c69.png)

**Comment by stleary** [comment]
@IsmaelP19 Thanks!

**Comment by karldamus** [comment]
![json-java-1](https://user-images.githubusercontent.com/44273743/116834788-a8765d80-ab8d-11eb-9f53-5eb2b8267463.png)
Why not do something a lot simpler?

**Comment by karldamus** [comment]
![json-java-2](https://user-images.githubusercontent.com/44273743/116834865-0145f600-ab8e-11eb-9d11-c5cf3dcecd3f.png)
My take on a design

**Comment by stleary** [comment]
Looks like these are all of the proposed logos, thanks everyone for submitting your ideas!
If anyone has a preference for which logo to use please post below. If there is a clear favorite, that one will get picked. Otherwise, I will pick one in a few days.

**Comment by stleary** [comment]
Updated.
