### ISSUE TITLE
Suggestion type support

### ISSUE THREAD

**Issue by pabramber01** [stleary/JSON-java#599]
I've seen the possible API changes within the FAQ, and it occurred to me if a possible improvement is to add support for the Fraction type. I've been using it quite a bit and find it quite useful. Before starting the implementation to support it, I would like to know if it would be an accepted change or not.

The fraction type I've been using: https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/math/Fraction.html

**Comment by johnjaylward** [comment]
This project has no external dependencies at the moment. If you can make a way for this project to support the fraction class without actually referencing it, I think that would be acceptable.

**Comment by pabramber01** [comment]
Okay, I'll see what I can do. I will put the progress here or even in a pull request if it is very advanced :)

**Comment by stleary** [comment]
Closing this issue due to no input in the past 3 months.
