### ISSUE TITLE
Little error in JSONStringer doc

### ISSUE THREAD

**Issue by pabramber01** [stleary/JSON-java#600]
I have found a small bug in the API documentation. As I have seen in the JSONStringer class objects and arrays can be nested up to 200 levels deep and in the documentation it says 20.

The JSONStringer document: http://stleary.github.io/JSON-java/index.html

**Comment by stleary** [comment]
I believe this was fixed in the JavaDocs in the code in #594, but the API docs only get updated when there is a new release. Usually, that is every 4-6 months.

**Comment by pabramber01** [comment]
Oh I had not seen that issue. So, since the problem is already solved, I close this
