### ISSUE TITLE
Not parsing a xml with html content as value to json

### ISSUE THREAD

**Issue by nagarajan4** [stleary/JSON-java#609]
I need to convert the below XML to JSON with the nested HTML content intact.

```xml
<example>
    <value attribute="value">some treatment <b>plant</b> with bio chemicals</value>
</example>
```
Expected Json :
```json
{
  "example": {
    "value": {
      "attribute": "value",
      "content": "some treatment <b>plant</b> with bio chemicals"
    }
  }
}
```
Actual json output from the converter : 
```json
{
  "water" : {
    "value" : {
      "b" : "plant",
      "content" : [ "water treatment", "with bio chemicals" ]
    }
  }
}
```

I can understand this can be expected behavior but any chance do you to support this use case ?

**Comment by stleary** [comment]
Can you try wrapping your value content in CDATA?

For example,
````
<example>
    <value attribute="value">
        <![CDATA[some treatment <b>plant</b> with bio chemicals]]>
    </value>
</example>
````

**Comment by nagarajan4** [comment]
Yeah that is probably correct, but the xml generated by an old framework that doesn't follow the CDATA inclusion for characters with mark up. If there is any other way please let me know, since we parse XML based on the occurrence of '<' tag I feel there not much which can be done.

**Comment by nagarajan4** [comment]
Thank you. Ended up parsed the XML directly and converted such fields as strings and stored them as a Map which is converted to JSON. Closing the issue as it is not a problem of the JSON-java library. But it can be considered as an enhancement ?.
