### ISSUE TITLE
Bugfix in JSONObject.Similar()

### ISSUE THREAD

**Issue by eyalb40** [stleary/JSON-java#611]
I JSONObject.Similar() you return true\false after comparing a number property. Should only return if false.

Should replace 
                    return isNumberSimilar((Number)valueThis, (Number)valueOther);
with
                    if (!isNumberSimilar((Number)valueThis, (Number)valueOther))
                        return false;

**Comment by stleary** [comment]
Agreed, good catch @eyalb40, and thanks for the heads-up. Feel free to submit a pull request to fix this, if you want.

**Comment by stleary** [comment]
Fixed in #613

**Comment by johnjaylward** [comment]
@stleary, you should also correct the `similar` in `JSONArray`
