### ISSUE TITLE
missing public pgp key on keys servers 

### ISSUE THREAD

**Issue by slawekjaranowski** [stleary/JSON-java#612]
pgp public key used for signing maven artifacts is not available on keys servers ... so signature verification is not possible

For latest two version key of fingerprint: 0x83D7DB7C18913CA4 was used - please upload this key to key server

for version: 20200518 was used key 0xCDCAA216B086A7B603B638C5145D819475314D97 and it is avaliable.

```
mvn org.simplify4u.plugins:pgpverify-maven-plugin:show -Dartifact=org.json:json:20210307

[WARNING] {https://keyserver.ubuntu.com} throw exception: PGP server returned an error: HTTP/1.1 404 Not Found for: https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0x83D7DB7C18913CA4 - fallback try next client
[WARNING] {https://keys.openpgp.org} throw exception: PGP server returned an error: HTTP/1.1 404 Not Found for: https://keys.openpgp.org/pks/lookup?op=get&options=mr&search=0x83D7DB7C18913CA4 - fallback try next client
[WARNING] {https://pgp.mit.edu} throw exception: PGP server returned an error: HTTP/1.1 404 Not Found for: https://pgp.mit.edu/pks/lookup?op=get&options=mr&search=0x83D7DB7C18913CA4 - fallback try next client
[ERROR] All servers from list was failed
[INFO] 

Artifact:
	groupId:     org.json
	artifactId:  json
	type:        jar
	version:     20210307

PGP signature:
	version:     4
	algorithm:   SHA1withRSA
	keyId:       0x83D7DB7C18913CA4
	create date: Mon Mar 08 04:55:24 CET 2021
	status:      invalid


PGP server returned an error: HTTP/1.1 404 Not Found for: https://pgp.mit.edu/pks/lookup?op=get&options=mr&search=0x83D7DB7C18913CA4
```

and last valid

```
mvn org.simplify4u.plugins:pgpverify-maven-plugin:show -Dartifact=org.json:json:20200518

Artifact:
	groupId:     org.json
	artifactId:  json
	type:        jar
	version:     20200518

PGP signature:
	version:     4
	algorithm:   SHA1withRSA
	keyId:       0x145D819475314D97
	create date: Wed May 20 02:30:14 CEST 2020
	status:      valid

PGP key:
	version:     4
	algorithm:   RSA (Encrypt or Sign)
	bits:        2048
	fingerprint: 0xCDCAA216B086A7B603B638C5145D819475314D97
	create date: Sun Aug 23 22:29:27 CEST 2015
	uids:        [Sean Leary (stleary) <xxxx>]

```

**Comment by stleary** [comment]
Thanks @slawekjaranowski I will look into this.

**Comment by stleary** [comment]
Please retry, let me know if you are still seeing a problem.

**Comment by slawekjaranowski** [comment]
problem still exist, please try run:

```
mvn org.simplify4u.plugins:pgpverify-maven-plugin:show -Dartifact=org.json:json:20210307
```

**Comment by stleary** [comment]
Confirmed, working on it...

**Comment by stleary** [comment]
It's odd - the command works correctly on one computer, but fails on another, on the same network. Of course, it works on the machine where I created the key, so perhaps that is not a fair test. I am getting `gpg: keyserver send failed: No data` errors now on pgp.mit.edu, so I don't trust that server. Next release, I will use a different key server. Unless someone has a better idea, that may be the best I can do.

**Comment by slawekjaranowski** [comment]
you can use another key server to publish your key, like:

```
gpg --keyserver keyserver.ubuntu.com --send-keys 83D7DB7C18913CA4
```
https://central.sonatype.org/publish/requirements/gpg/#distributing-your-public-key

by the way it is strange that my example command `mvn ...` works on one host and doesn't work on another - this plugin doesn't use `gpg` so should be independent of having or not `gpg` key on host.

**Comment by slawekjaranowski** [comment]
@stleary - kindly reminder you don't need to wait for next release for publishing public key ...

**Comment by stleary** [comment]
@slawekjaranowski  Thanks, good point. The computer that holds the key is not accessible to me until mid-next week. Will take care of it then.

**Comment by slawekjaranowski** [comment]
@stleary - kindly reminder - be will possible for publishing your public key?

**Comment by stleary** [comment]
@slawekjaranowski Thanks, I will try to get to it this weekend.

**Comment by stleary** [comment]
Should be fixed with release 20211205

**Comment by slawekjaranowski** [comment]
Version 20211205 can be verified - public key is available on key servers

**Comment by stleary** [comment]
So glad to hear it's working!
