### ISSUE TITLE
Please reopen #614

### ISSUE THREAD

**Issue by johnjaylward** [stleary/JSON-java#615]
Please reopen #614 . I believe it requires further discussion.

I don't believe the original author would have any qualms about updating the Java requirements. In 2014, he added support for java 1.8 (see commit a9a07623834b6da2c2c3d47b440e002dedfd9e17). It was later reverted (I believe after he did the hand-off to you). I don't believe he'd be against the update today if we ensured functionality.

Also, Some historical tickets referencing old support for java 8 (requesting lower version) as well as feature requests for java8+:
* #156
* #172 
* #181
* #197, #195
* #201
* #295

**Comment by stleary** [comment]
#614 reopened, toxic comments removed.
