### ISSUE TITLE
Not working in threads

### ISSUE THREAD

**Issue by ArianKG** [stleary/JSON-java#619]
I making a Minecraft launcher and I need to parse JSON. So, I used JSON-java. But it seems like JSON-java not working in threads.
My Minecraft launcher code: [JLXLauncher.txt](https://github.com/stleary/JSON-java/files/6924593/JLXLauncher.txt)

**Comment by johnjaylward** [comment]
Correct. The underlying storage for JSONObject and JSONArray are not thread safe. If you need to share a single json object, you should use a monitor/lock to access it

i.e.

```java
class MyConfig {
    private JSONObject configObj;
    private static Object LOCK = new Object();

    public MyConfig() { this.configObj = new JSONObject(); }

    public String getConfig(String key) {
        lock(LOCK) {
            final Object val = this.configObj.opt(key);
            if (val == null) return "";
            return val.toString();
        }
    }

    public void setConfig(String key, String value) {
        lock(LOCK) {
            final Object val = this.configObj.put(key, value);
        }
    }
}
```

Your other option may be to read your configuration into a JSON object, then convert it to a ConcurrentHashMap, and then share the hash map

```java
JSONObject jsonConfig = new JSONObject(source);
ConcurrentHashMap<String,Object> config = new ConcurrentHashMap<>(jsonConfig.toMap());
// pass around the `config` object to the other threads
```

Then to save changes to the config back to disk:

```java
JSONObject jsonConfig = new JSONObject(config); // where `config` is our concurrent map
String saveThisToDisk = jsonConfig.toString(); // or optionally use the JSONObject.write(writer) method

**Comment by johnjaylward** [comment]
Actually, looking at your implementation, I don't see any multithreading at all related to JSONObject.

What is that actual exception/problem you are having?

**Comment by ArianKG** [comment]
@johnjaylward My problem is:
When I run my launcher, "Test 1" (that is in line 105) will print, but "Test 2" (that is in line 107) will not print.

**Comment by johnjaylward** [comment]
Also, I see issues with your use of file paths. It is not OS agnostic. You should not be concatenating the directory separators yourself. instead your use of `Paths.get` should look like this:

```java
Paths.get(gameDir , "versions","version_manifest_v2.json")

Paths.get(gameDir , "versions", version ,  version , ".json");

new FileOutputStream(Paths.get(gameDir , "versions" , version, version , ".jar").toFile());
```

URLs always use the same path separator regardless of the OS, so no worries with those. It's only the local files that you need to worry about.

**Comment by johnjaylward** [comment]
> 
> 
> @johnjaylward My problem is:
> When I run my launcher, "Test 1" (that is in line 105) will print, but "Test 2" (that is in line 107) will not print.

Yes, but what is the error that is output? surely the `e.printStackTrace();` is giving you something?

**Comment by ArianKG** [comment]
@johnjaylward There is no error. The only problem is "Test 2" will not print.

**Comment by johnjaylward** [comment]
what is the content of the JSON that is causing the issue?

**Comment by ArianKG** [comment]
@johnjaylward Just look at the code. It generates according to the Minecraft version. Also, I even changed the JSON content to "{}", but not working.

**Comment by johnjaylward** [comment]
I did. There is no reason for the code to stop at that point with no error. There is either an error you are not noticing, or the json content has found a bug in the parse that is creating an infinate loop.

If you can debug and step into the code to see what the issue is exactly, that will help, otherwise we will have to close this as not having enough information

**Comment by ArianKG** [comment]
![Output of my program](https://user-images.githubusercontent.com/72304422/128093769-b48056d3-7c16-48a1-b001-be689064718a.png)

**Comment by ArianKG** [comment]
@stleary If it's not a JSON-java issue, how can I fix it?

**Comment by stleary** [comment]
@ArianKG sorry, that was not a useful label. Posting a screenshot is unlikely to be helpful. But if you upload your code to a GitHub repo and post a link here, then someone may be able to offer assistance.

**Comment by ArianKG** [comment]
@stleary I uploaded my code in this issue. Is it needed to make a GitHub repository?

**Comment by ArianKG** [comment]
@stleary Sorry, this is not a JSON-java issue. I should add classpath to the JAR file.
