### ISSUE TITLE
Integrate fuzzing into JSON-java by way of OSS-fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [stleary/JSON-java#641]
Hi!

I was wondering if you would be interested in getting JSON-java fuzzed by OSS-Fuzz? Fuzzing is a technique for stress-testing applications and OSS-Fuzz is a free service run by Google for fuzzing important open source projects, and it would be great to get JSON-java integrated with OSS-Fuzz. OSS-Fuzz will run the fuzzers continuously and report back with bug reports when bugs are found. These reports will have full stack traces, input triggers and more. If you are interested, then the only thing needed is an email(s) connected to a Google account that can be used for receiving the bugs reports, which can be put in the configuration file (`project.yaml`) over at the OSS-Fuzz repository.

I have set up an initial integration with OSS-Fuzz here: https://github.com/google/oss-fuzz/pull/6733 and this PR on the OSS-Fuzz repository includes a simple initial fuzzer. We can always extend with more fuzzers if you are happy to integrate. I would just need an email and then get this PR merged, following that we should be good to go and down the line we can also migrate fuzzers from OSS-Fuzz to JSON-java owns repository.

**Comment by stleary** [comment]
@DavidKorczynski Sounds interesting. You can use jsonjava060@gmail.com to get started.

**Comment by DavidKorczynski** [comment]
Thanks @stleary - the integration has now completed (https://github.com/google/oss-fuzz/pull/6733). You should receive notifications on your email if any issues arise. Thanks!
