### ISSUE TITLE
Incorrect key generated when creating JSONObject from a Java Object with fieldname having second character in upper case

### ISSUE THREAD

**Issue by ranju-kv** [stleary/JSON-java#644]
If you have a Java class which has a field with second character in upper case, then the key derived for that field is incorrect.

Example:
field name: iAmOk
getter method: getIAmOk

When new JSONObject(object) is used to generate a JSONObject representation of an object of above class, then the key for that field is derived as "IAmOk" instead of "iAmOk"

Looking at the JSONObject source code, the issue is in the last part of getKeyNameFromMethod where it checks if the second character in the field name is upper case and if yes, does not do anything.

Is this intentional? What is the reasoning behind this?

**Comment by johnjaylward** [comment]
You can override the property name generation using the `@JSONPropertyName` annotation.

The reason for the casing rule is that it's assuming that something like `getIAmOK` is actually an abbreviation like `getURL` where you probably don't want that converted to `uRL`.

In the history of the project, the rules for casing were made before the override annotation, and we've left it for backwards compatibility.

**Comment by stleary** [comment]
Closed due to working as designed | workaround provided
