### ISSUE TITLE
Suggestion: Allow comments in parsed JSON

### ISSUE THREAD

**Issue by Simulant87** [stleary/JSON-java#647]
Some projects like to read data from a JSON data store, where comments in the JSON can help humans to understand the data better. However the parser fails (correctly) when trying to parse from a json file, that contains comments, as it is not valid JSON.

A general question to answer first would be: Does the project want to be strict to the JSON definition and reject not compliant JSON files to be parsed, or would it be benifitial if the parser would be more relaxed and would allow JSON input to contain comments, which would be simply ignored during parsing? Like the parser already accepts strings in single quotes while only double quotes are strictly correct JSON.

Example:

```
{
// this would be ignored instead of failing
"key":"value"
/*
 * Muliti line comments would be fine, too.
 */
}
```

Some inspiration from other projects around that topic: https://spec.json5.org/#comments

**Comment by johnjaylward** [comment]
I can't speak to it being accepted... but I will say, it won't be accepted if implemented poorly. In general JSON Parsers can be pretty lax, so I personally don't see an issue with having support to ignore, or even track comments in a given JSON input. Our parser is already not a "strict parser", so extending the parser to allow comments wouldn't be too far fetched, and it would closer match the Google implementation of this API that they did for Android.

However, **Comments are not valid JSON. The writer should default to ignoring any comments noted in the JSONObject or JSONArray. The Writer will need an optional parameter to allow writing back out the comments.**

### Possible Implementations I see with our existing structure:

1.  We could give them "fake" keys like `comment_<index>` but no one has given the reader an option to track read order, so output would end up having the comments in random positions making them possibly useless or worse confusing. I kinda hate this option, and would rather just have the parser skip over the comments and throw them away than do this.
1.  We could add a secondary map (`Map<String,String>`) in the JsonObject just for comments. If the comment is followed by a `key`, the comment gets the same key and the writer could output the comment in the same location. We still have the issue of unkeyed comments, but that shouldn't be too big of a problem if we just output them consistently at the end of the object. We could also "tag" a trailing comment to the last parsed key.
1. Along a similar vein, we could treat comments in Arrays with a similar comments map (`Map<Integer,String>`) to map the comments to the position they are relevant to. This will allow the writer to easily ignore the comments, or to optionally publish them if implemented as an option.

### Some issues:

1. As noted above, comments are not valid JSON. The writer should default to ignoring any comments noted in the JSONObject or JSONArray. The Writer will need an optional parameter to allow writing back out the comments.
2. What happens for a comment at the start of the file? e.g. `/* header comment */ { "key":"value"}` or `/* header comment */ [1,2,3]`
3. Will there be API functions for retrieving and adding/updating comments?
4. How should we standardize on comment output by the writer. My personal thought is to force all to the multi-line syntax `/**/` which is a single character more than the single line syntax `//\n`, but it should simplify the writer logic (no need to see if the comment has a newline or not). I don't think the parser should bother tracking if the comment originated as a `//` or `/**/` comment. It seems irrelevant.
5. How to handle a comment followed by another comment? Should we just append them together? Should we track comments on a field as an array? Personally, I'm leaning towards just appending them. I think it would make any API to access/update them a lot easier to work with.

### Some example documents (not conclusive, just what I have off the top of my head) that could be used for test cases:

#### JSON Object based tests

```json
// header comment
{
   "a" : 1,
   "b": "two"
}
```

```json
{
   // comment on a
   "a" : 1,
   // comment on b
   "b": "two"
}
```

```json
{
   /* comment on a */
   "a" : 1,
   /* comment on b */
   "b": "two"
}
```

```json
{
   "a" : 1/* comment on a */,
   /* comment on b */
   "b": "two"
}
```

```json
{
   "a" : 1/* comment on a */,
   "b": "two"/* comment on b or a lose comment... */
}
```

```json
{
   // multiple single line comments
   // for item a. Should roll to a single
   // comment with multiple lines
   "a" : 1,
   "b": "two"/* comment on b or a lose comment... */
}
```

```json
{
   /* multiple line comment
    * for item 1. Should roll to a single
    * comment with multiple lines. What should we do
    * about the `*` prefixing each line? Strip or Keep?
    * Same with white space for comments, Strip or Keep?
    */
   "a" : 1,
   "b": "two"/* comment on b or a lose comment... */
}
```

#### JSON Array based tests

```json
// header comment
[
   1,
   "two"
]
```

```json
[
// comment on one
   1,
   "two"
]
```

```json
[
   1 // comment on one
    ,
   "two"
]
```

```json
[
   1 /* comment on one */,
   "two"
]
```

```json
[
   1,
    /* comment on 2 */"two"
]
```

```json
[
   1,
    "two"/* comment on 2 or a lose comment*/
]
```

```json
[
   // multiple single line comments
   // for item 1. Should roll to a single
   // comment with multiple lines
   1,
    "two"/* comment on 2 or a lose comment*/
]
```

```json
[
   /* multiple line comment
    * for item 1. Should roll to a single
    * comment with multiple lines. What should we do
    * about the `*` prefixing each line? Strip or Keep?
    * Same with white space for comments, Strip or Keep?
    */
   1,
    "two"/* comment on 2 or a lose comment*/
]
```

**Comment by stleary** [comment]
Support for comments seems to have done no great harm for YAML, but the person who wrote this package and also co-created JSON decided not to include them. For now, we lean towards his decisions. But keep in mind that ownership of this repo will change at some point, and then all kinds of decisions may be revisited.
