### ISSUE TITLE
Suggestion: more helpful wrong-type errors

### ISSUE THREAD

**Issue by bherw** [stleary/JSON-java#649]
Currently the exception just states that the value was the wrong type, for example:
```
org.json.JSONException: JSONObject["layers"] is not a JSONArray.
```

It would be helpful if the exception told us what the type actually was as well. Was it null? JSONObject? something else?

**Comment by stleary** [comment]
@bherw thanks for raising this issue. No objections if you want to try some type of implementation. More helpful errors are always welcome.
