### ISSUE TITLE
Why are semicolons accepted as key/value-pair separators?

### ISSUE THREAD

**Issue by rhoehener** [stleary/JSON-java#664]
Is this on purpose? It's been there since the initial commit: https://github.com/stleary/JSON-java/blame/master/src/main/java/org/json/JSONObject.java#L271

```
    JSONObject jsonObject = new JSONObject("{ \"1\" : 1 ; \"2\" : 2 }");
    System.out.print(jsonObject.getInt("1"));
    System.out.print(jsonObject.getInt("2"));
```
Prints 12

**Comment by rhoehener** [comment]
https://github.com/stleary/JSON-java/blame/master/src/main/java/org/json/JSONObject.java#L273 also accepts (ignores) trailing commas and semicolons.

```
    System.out.println(new JSONObject("{ \"1\" : 1 , }").getInt("1"));
    System.out.println(new JSONObject("{ \"1\" : 1 ; }").getInt("1"));
```

**Comment by stleary** [comment]
Yes, I think you are referring to something like #556
