### ISSUE TITLE
DEL control character (0x007F) is not escaped

### ISSUE THREAD

**Issue by rhoehener** [stleary/JSON-java#666]
https://github.com/stleary/JSON-java/blame/master/src/main/java/org/json/JSONObject.java#L2080

```
    System.out.println(java.lang.Character.isISOControl(0x007f));
    System.out.println(new JSONObject("{\"a\":\"\u007f\"}").toString(0));
```

**Comment by johnjaylward** [comment]
Thanks, this does look like a bug. Please feel free to post a PR.

**Comment by johnjaylward** [comment]
adding an additional ` || java.lang.Character.isISOControl(c)` to the `if` should be sufficient. Jhe function was added in 1.5 so it should be available for all our supported platforms.

**Comment by johnjaylward** [comment]
or better may be to just replace the first 2 check with that function, so the new `if` would look like:

```java
if (Character.isISOControl(c) || (c >= '\u2000' && c < '\u2100')) {
```

**Comment by rhoehener** [comment]
- or copy the (optimized) implementation of Character.isISOControl(int)
- or use Character.isISOControl((int) c) (to save one method call)

**Comment by johnjaylward** [comment]
I would prefer the `Character.isISOControl((int) c)` call over the copy/paste so any future changes to the call would be available on a JVM update.

**Comment by stleary** [comment]
Closed due to lack of activity.
