### ISSUE TITLE
Cannot be used in android studio !

### ISSUE THREAD

**Issue by ErrorxCode** [stleary/JSON-java#669]
Since both android.jar (Android framework)  and org-json.jar (This library) have the same package "org.json", We can't use this library in android studio. If we import `import org.json.JSONObject` then the android implementation is imported which cannot be used in a non-android platform. The only way to fix this is to **change the package name** of the library.

I have made a copy of this jar with a different package name (org.java.json). Please allow me to contribute to this project and publish this jar in the repo.

**Comment by johnjaylward** [comment]
no. please see the [Wiki](https://github.com/stleary/JSON-java/wiki/JSON-Java-for-Android-developers). We are not changing this project package.

**Comment by stleary** [comment]
I believe this project was the original org.json package.
