### ISSUE TITLE
Documentation on JSONPropertyIgnore doesn't show on the website

### ISSUE THREAD

**Issue by gqqnbig** [stleary/JSON-java#670]
In https://github.com/stleary/JSON-java/blob/master/src/main/java/org/json/JSONPropertyIgnore.java  the class has documentation, but the docs doesn't show on the website http://stleary.github.io/JSON-java/org/json/JSONPropertyIgnore.html.

Can it get fixed?

**Comment by stleary** [comment]
Thanks @gqqnbig I will look into it. Not sure why the JavaDocs are not showing up.

**Comment by stleary** [comment]
Haven't forgotten this, just haven't had time to track it down. Will try to find time before end of the week.

**Comment by gqqnbig** [comment]
Thanks for the update. Take your time buddy.

**Comment by niranjanib** [comment]
Hi @stleary, I've raised PR #704  to fix this issue happening in both `JSONPropertyIgnore` and `JSONPropertyName` classes. 

This doesn't affect the source code execution, I've only rearranged Javadoc comments to the start of the interface definition. Please review and let me know if there is anything to be changed :) 

Thanks!
