### ISSUE TITLE
Getter for org.json.JSONArray::myArrayList

### ISSUE THREAD

**Issue by jacekpodgorz** [stleary/JSON-java#672]
Please add getter to "myArrayList" field in JSONArray. 
It will allow further self-processing without the need to use "toList".

**Comment by johnjaylward** [comment]
There is no reason for us to expose the back end data types used and would limit us possibly changing the implementation in the future if a better option presents itself.

**Comment by johnjaylward** [comment]
What are you trying to accomplish? Perhaps there is a better way to do what you want without exposing the internals?

**Comment by jacekpodgorz** [comment]
Thank you for your answer.

I create Array:
`[{" x ": 1}, {" x ": 2," y ": 2.5}, {" x ": 3}]`
the variable "myArrayList" is "ArrayList <JSONObject>".

If use method "toList()" I get an "ArrayList <HashMap>".

The variable is garbled. Working on JSONArray using "toList", I will always get a new object.

It would be helpful to download "Stream".

**Comment by jacekpodgorz** [comment]
Thank you for your answer.

I understand the objections. I am using old code for this library which has been rewritten previously. Performs multiple operations on "myArrayList" such as sorting. The library was not "Iterable". I want to use the current via Maven.
Thank you for your help. Regards and I close.
