### ISSUE TITLE
Suggestion: JSONArray#toList(class)

### ISSUE THREAD

**Issue by Chew** [stleary/JSON-java#674]
The current `JSONArray#toList()` converts the array to a list of Object. This makes things a little tough to work with.

When, for example, you have a list of typically JSON Objects or Strings, you have to do something like this:

```java
jarr.toList().stream().map(Object::toString).toList(); // List of string
jarr.toList().stream().map(o -> (JSONObject) o).toList(); // List of JSONObject
```

I wrote a function that implments this, but I'm not too Java experty to know if it's ideal:

```java
    /**
     * Converts a JSONArray to a list of {@code <T>}.
     *
     * @param array The JSONArray
     * @param cast The class to cast to
     * @param <T> The type to cast to
     * @return A list of {@code <T>}
     */
    public static <T> List<T> toList(JSONArray array, Class<T> cast) {
        List<T> results = new ArrayList<>(array.length());
        for (Object element : array) {
            if (element == null || JSONObject.NULL.equals(element)) {
                results.add(null);
            } else {
                results.add(cast.cast(element));
            }
        }
        return results;
    }
```

It's a little messy but it essentially casts each item in the array to the specific object. This is of course missing any exception handling since ClassCastException is likely.

Am I going about my suggestion all wrong? Is there already a way to do this? Please let me know 😄

**Comment by johnjaylward** [comment]
personally, I wouldn't bother with toList at all in your use-case though. as in #672, I would just use the spliterator to get a stream and continue to use the Map option like you do:

```java
java.util.StreamSupport(jarr.spliterator(), false)
    .filter(Object::notNull)
    .filter(i-> JSONObject.class.isAssignableFrom(i.getClass())
    .map(i-> (JSONObject)i)
  // process
;
```

Using `toList` defeats the purpose of using a stream in the first place which is to prevent creation of extra object (in this case an entire array).

**Comment by johnjaylward** [comment]
if you want to make that as a helper method, it would look something like this:

```java
public static <T> Stream<T> toStream(JSONArray array, Class<T> cast) {
    return java.util.StreamSupport(jarr.spliterator(), false)
        .filter(Objects::nonNull)
        .filter(i-> cast.isAssignableFrom(i.getClass())
        .map(i-> cast.cast(i));
}
```

**Comment by stleary** [comment]
@Chew No objections if you would like to submit a pull request. Please make sure the code either handles exceptions has a language supported workaround. Keep in mind the project's Java version requirement: [What version of Java does this project require?](https://github.com/stleary/JSON-java/wiki/FAQ#what-version-of-java-does-this-project-require?)

**Comment by johnjaylward** [comment]
@stleary , looks like the wiki needs a quick update to note the move to Java8 : https://github.com/stleary/JSON-java/wiki/FAQ#what-version-of-java-does-this-project-require

**Comment by stleary** [comment]
@johnjaylward  Should be updated now, thanks for catching this.

**Comment by stleary** [comment]
Closing this issue. Please post here if you disagree.
