### ISSUE TITLE
JSONTokener is too lenient

### ISSUE THREAD

**Issue by whistlingdogg** [stleary/JSON-java#679]
Parsing of unquoted strings into a JSONObject using a JSONTokener is too lenient. It will allow the following:

{ "requestofsomesort": { "id": thisstringshouldbequoted }}

Using something like Everit to validate the schema then incorrectly reports that the json is compliant. I understand that the documentation states that the JSONObject can accept this sort of thing but this causes problems.

https://json-schema.org/understanding-json-schema/reference/string.html suggests that the above is not legal. Also https://jsonlint.com/

I have seen references to a JSONStrictTokener but can't find its implementation or distribution anywhere.

**Comment by stleary** [comment]
Lenient parsing has been part of this application from the beginning. If you want to propose a code change for an optional strict parser mode, feel free to go ahead. However, it must not have any effect on existing users unless they opt-in.

**Comment by stleary** [comment]
Closed due to Works as Designed.
