### ISSUE TITLE
Why is JSONObject(int initialCapacity) protected and not public ?

### ISSUE THREAD

**Issue by omasseau** [stleary/JSON-java#697]
Hello,

Is there any reason why JSONObject(int initialCapacity) is protected and not public ?
When building a JSONObject from scratch it would be nice to be able to provide the initial capacity for improved performances.

**Comment by stleary** [comment]
@omasseau how much of a performance improvement will this provide?

**Comment by stleary** [comment]
Closed due to lack of activity
