### ISSUE TITLE
Question regarding GitHub Actions pipeline definition

### ISSUE THREAD

**Issue by Okeanos** [stleary/JSON-java#698]
I had a look at the pipeline definition and I am somewhat confused at the fact that especially the Java 1.6 build works as expected.

I would have expected a `actions/setup-java@v3` task with the following inputs in place of what currently exists:

```yaml
- name: Set up JDK
  uses: actions/setup-java@v3
  with:
    distribution: zulu
    java-version: 6
```

As far as I can currently tell no `setup-java` distribution vendor offers `1.6` as version. The only Java 6 (1.6) version available I could find is offered by Azul via Zulu. Also, the selected runners of type `ubuntu-latest` (currently at [20.04](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) also doesn't include a [Java 1.6/6 version](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#java)).

I can see that the JDK for 1.6/6 is part of the [hosted tool cache](https://github.com/stleary/JSON-java/actions/runs/3255842510/jobs/5345584735#step:4:5), though.

What am I missing?

I am also wondering whether this would be an appropriate use case for [Maven Toolchains](https://maven.apache.org/guides/mini/guide-using-toolchains.html) so that Maven could be used to build the project instead of directly invoking the Java Compiler.

**Comment by stleary** [comment]
@Okeanos I am not sure, but will take a look when time permits. There are no plans to make changes to the build pipeline at this time.

**Comment by stleary** [comment]
Closed due to lack of activity.
