### ISSUE TITLE
License change request

### ISSUE THREAD

**Issue by kk-zu** [stleary/JSON-java#706]
@douglascrockford 

The license was changed to "Public Domain" in PR #688. However, the meaning of "public domain" is a bit ambiguous (e.g. "public domain" is not defined in the law of Japan.)
So users can't judge whether they can use JSON-java or not. I guess that it opposes your intention.

To resolve this problem, could you change the license to 0BSD or MIT-0? Or could you agree to change the license to one of two licenses?

I asked you because I read [this message](https://github.com/stleary/JSON-java/pull/688#issuecomment-1304654045)
> The original author of the application, Douglas Crockford, selected the license. Please reach out to him if you would like to see any changes.

**Comment by javadev** [comment]
MIT ➕

**Comment by sonots** [comment]
I also prefer MIT license.

**Comment by ColinSullivan1** [comment]
+1, MIT or Apache 2.0 would be great.

Great project and thanks for contributing to the open source community. We'd really like to use this project in NATS.io but it doesn't seem like we can due to the current license.  More here: https://opensource.org/node/878

CC @scottf

**Comment by douglascrockford** [comment]
If Public Domain is not liberal enough for you, I recommend that you do not use it.

**Comment by stleary** [comment]
Closing this issue due to a provided authoritative answer.

**Comment by scottf** [comment]
@douglascrockford It's not that it's not liberal enough for us, it's the fact that public domain is not a license and is interpreted differently in different countries which can make it incompatible with opensource projects. The lawyers just don't want to deal with it.

**Comment by douglascrockford** [comment]
Coders arguing about international intellectual property law: ridiculous. The facts are that it is absolutely free and I gave up claim of ownership. You are of course entitled to believe all of the non-facts that you like.

**Comment by johnjaylward** [comment]
Not to beat a dead horse... but ok I will.

I believe they are just looking for something more "formal" to satiate corporate lawyers. I believe a [license like this](https://opensource.org/license/unlicense/) matches what your intent is @douglascrockford .
