### ISSUE TITLE
The test testToJSONObject_reversibility() in JSONMLTest is flaky

### ISSUE THREAD

**Issue by aditya-kumbhar** [stleary/JSON-java#709]
The test testToJSONObject_reversibility() in JSONMLTest is found to be flaky using the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool.
The reason is that two JSON objects are being compared for equality but the order of the elements in the constructed JSONs is not deterministic, hence the objects should only be compared for similarity and not for equality.

NonDex error log:
```
[ERROR] org.json.junit.JSONMLTest.testToJSONObject_reversibility  Time elapsed: 0 s  <<< FAILURE!
org.junit.ComparisonFailure: original JSON does not equal the new JSON expected:<{"[tagName":"readResult","childNodes":[{"someAttr":"arrtValue","childNodes":[{"childNodes":[400],"tagName":"code"}],"tagName":"errors"},{"tagName":"errors","childNodes":[{"childNodes":[402],"tagName":"code"}]}]]}> but was:<{"[childNodes":[{"tagName":"errors","childNodes":[{"childNodes":[400],"tagName":"code"}],"someAttr":"arrtValue"},{"childNodes":[{"childNodes":[402],"tagName":"code"}],"tagName":"errors"}],"tagName":"readResult"]}>
```
Assertions that are made in the test:
```
assertTrue("JSON Objects are not similar",originalObject.similar(revertedObject)); // this passes
assertEquals("original JSON does not equal the new JSON",originalJson, newJson); //fails
```
So, the solution would be to remove the assertEquals() as the similarity of the two JSONs is already being checked. 
I can raise a PR for the small change, but wanted to discuss the approach first before raising the PR.

**Comment by stleary** [comment]
@aditya-kumbhar I think the test needs both asserts. One checks object similarity, and the other checks string equality. The assertEquals() is arguably more critical than the assertTrue(). I am not sure that NonDex is adding value by flagging this test.

**Comment by aditya-kumbhar** [comment]
That is fair.
