### ISSUE TITLE
Escaping string - can it be switched off?

### ISSUE THREAD

**Issue by richastral** [stleary/JSON-java#710]
Hi,

I have identified an issue with string escaping. The JSONObject by default escapes strings and cannot be switched off, in particular, my use case of a path in the JSON.

**Example:**
```
Map valuesMap = new HashMap();

// Actual path should be \\myserver\home\username, but it is required that we escape the string for it to be valid Java.
valuesMap.put("path", "\\\\myserver\\home\\username");

System.out.println(valuesMap.get("path");
// Returns correct string: \\myserver\home\username

System.out.println(new asg.org.json.JSONObject(attributeMap).toString());
Returns incorrect: {"path":"\\\\myserver\\home\\username"}
```

I have noticed that in JSONObject, the quote(String string, Writer w) method has the following:

```
for (i = 0; i < len; i += 1) {
	b = c;
	c = string.charAt(i);
	switch (c) {
	case '\\':   <<<<<<<<< Always escapes...
	case '"':
		w.write('\\');
		w.write(c);
		break;
	case '/':
```

Is there any way prevent this happening? I cannot see any?

I am thinking of creating a pull request; however I am not quite sure of which way I want to tackle it:

1) Could have a static boolean QUOTE_STRINGS defaulting as true as to not affect current implementations, and in the quote, method check for this and just return the input if the boolean is false?
org

```
public static boolean QUOTE_STRINGS = true;
```

And something like this (not correect, but you get the point):

```
public static String quote(String string) {
	
	if(QUOTE_STRINGS) {
		return string;
	}
	
	StringWriter sw = new StringWriter();
	synchronized (sw.getBuffer()) {
		try {
			return quote(string, sw).toString();
		} catch (IOException ignored) {
			// will never happen - we are writing to a string writer
			return "";
		}
	}
}
```

2) update and override ever constructor and add String escapeStrngs parameter, but ensuring that a default is also there:

**Example:**

```
/**
 * Construct an empty JSONObject.
 */
public JSONObject() {
	// HashMap is used on purpose to ensure that elements are unordered by
	// ...
	this(true);
}

/**
 * Construct an empty JSONObject and specify escaped strings flag.
 * 
 * @param escapeString flag to escape strings.
 */
public JSONObject(boolean escapeStrings) {
	// HashMap is used on purpose to ensure that elements are unordered by
	// ...
	this.map = new HashMap<String, Object>();
	this.escapeStrings = escapeStrings;
}
```

Or if there is any other way you prefer, I am happy to help contribute.

Regards

Richard

**Comment by javadev** [comment]
Json

```
{"key": "\\\\myserver\\home\\username"}
```

may be converted to xml

```
<?xml version="1.0" encoding="UTF-8"?>
<key>\\myserver\home\username</key>
```

**Comment by richastral** [comment]
Thanks for your response, and sorry for my ignorance, but can you please explain further, does this solve my issue?  The output has to be JSON.  Are you saying set the attribute in the map to the XML, doesn't seem right to me?

**Comment by javadev** [comment]
@richastral xml value the same how it may be stored in  map.

There is escaping in json and real value in xml.

**Comment by johnjaylward** [comment]
This is working as it should per the spec.

**Comment by richastral** [comment]
@johnjaylward Thanks for the clarification.

Seems a bit strange that the same string inserted is not the same as the string returned.  But I understand why it is done.

In the application which is consuming the JSON unfortunately is poorly written and treats the string literally rather than escaping.

I just thought there may be a way to override this, and if not maybe submit a feature request.

**Comment by johnjaylward** [comment]
The consuming app should be fixed. It is wrong

**Comment by richastral** [comment]
Agreed, there is **a lot** wrong with it. It is supposed to be an enterprise application, it is far from it. Unfortunately getting issues resolved is problematic.

All good I will close this issue as it is not related to the library, thanks for your help.
