### ISSUE TITLE
JSONObject uses HashMap that is a problem if data is required to be sequence.

### ISSUE THREAD

**Issue by Ahsan-sys** [stleary/JSON-java#716]
JSONObject uses HashMap in its constructor, this cause the data to change its sequence, but some times we need sequenced data. For that we have to use LinkedHashMap. This is problem specially in code which is large and that JSONObject is used at many places in the code.
Why not make a function which works same but override constructor of JSONObject to LinkedHashMap.
I have faced this issue and solved by overriding it. I would love to contribute.

**Comment by stleary** [comment]
@Ahsan-sys JSON-Java is a reference application, so it should follow the specs, which define JSON objects as _"an unordered collection of zero or more name/value pairs"_. If an application must use ordered objects, then then the repo should be forked and HashMap replaced with your preferred implementation.

**Comment by stleary** [comment]
Closed due to response given.
