### ISSUE TITLE
Configure Java 11 as the minimum required version

### ISSUE THREAD

**Issue by javadev** [stleary/JSON-java#742]
I suggest establishing Java 11 as the minimum required version for the library.

https://github.com/stleary/JSON-java/pull/741

**Comment by michael-o** [comment]
> I suggest establishing Java 11 as the minimum required version for the library.
> 
> #741

WTF, what for?

**Comment by benzman81** [comment]
Plz not. Some systems still sadly require 1.8.

**Comment by michael-o** [comment]
> Plz not. Some systems still sadly require 1.8.

Even if not, if there is no technical need/benefit, why enforce?

**Comment by stleary** [comment]
#614 **Is it time for Java8+ support?** contains a thorough discussion of the Java version upgrade options, but we are limited by users' Java version requirements, as mentioned in this thread. 

I think an argument can be made for upgrading to Java 8 in order to get `stream` classes e.g. for #737. Would you be interested in updating #741 to require Java 8?

**Comment by javadev** [comment]
According to Twistlock's findings, the Java 8 runtime is considered insecure.

**Comment by michael-o** [comment]
> #614 **Is it time for Java8+ support?** contains a thorough discussion of the Java version upgrade options, but we are limited by users' Java version requirements, as mentioned in this thread.
> 
> I think an argument can be made for upgrading to Java 8 in order to get `stream` classes e.g. for #737. Would you be interested in updating #741 to require Java 8 instead of 11?

Looking at #614 I see a few for Java 8, granted. Anything up has very little value for something so simple like this lib, moreover the EOL date for Java 8 are just wrong. OpenJDK 8 will live until 2030 and believe me, many will use it for a plethora of reasons.

**Comment by johnjaylward** [comment]
I believe this was resolved with #741

**Comment by stleary** [comment]
Closing due to the decision to update to v8 in #741.
