### ISSUE TITLE
Compatibility with Java 17

### ISSUE THREAD

**Issue by kspmmitt** [stleary/JSON-java#746]
Hello,

I want to use latest version (20230227) of JSON-Java in my project, is it compatible with Java 17?

Right now document says as below - https://github.com/stleary/JSON-java/
 **> Designed and tested to use on Java versions 1.6 - 1.11**

Please suggest the way forward.

Rgds,
Kamal

**Comment by javadev** [comment]
The existing application underwent testing using Java 17.

https://github.com/stleary/JSON-java/pull/741

**Comment by kspmmitt** [comment]
Hello,

When the guide will be updated for java versions supported as currently it is restricted to java 11 as per documentation?

Rgds,
Kamal

**Comment by javadev** [comment]
> Hello,
> 
> When the guide will be updated for java versions supported as currently it is restricted to java 11 as per documentation?
> 
> Rgds, Kamal

I have created a pull request https://github.com/stleary/JSON-java/pull/747

**Comment by stleary** [comment]
Pending until #745 is addressed. Will try to get to that this weekend.

**Comment by johnjaylward** [comment]
Looks like if #741 is merged, we should have a follow-on PR that addresses the warnings in the Test cases related to Deprecated APIs (Java 17 "Run Tests"):

https://github.com/stleary/JSON-java/actions/runs/6002192162/job/16278097359?pr=741#step:5:32

**Comment by stleary** [comment]
Closing this issue, I don't think there is anything left to address. Please post here if you disagree.
