### ISSUE TITLE
Add a closing tag flag for XML output

### ISSUE THREAD

**Issue by derily** [stleary/JSON-java#748]
when JSONObject value is empty string,i need XML.toString output `<name></name> not <name/>`

**Comment by stleary** [comment]
@derily Can you provide a sample input and the output that you want to get?

**Comment by derily** [comment]
> @derily Can you provide a sample input and the output that you want to get?

input(JSONObject):
`{
  "name":"derily",
  "job":""
}`
output:
`<name>derily</name>
<job/>
`
expect(just not use self closing tag syntax):
`<name>derily</name>
<job></job>
`

**Comment by stleary** [comment]
@derily It might be possible to accommodate this with an XMLConfiguration option. If no one else picks this up, I will try to get something working this weekend.

**Comment by madhavgupta2011** [comment]
Hi, Can I take this up? I'm thinking of adding one more boolean parameter in toString() method of XML class handle the string as per the boolean parameter. Please let me know if this solution can be improved. I'm willing to take up on this issue.

**Comment by stleary** [comment]
@madhavgupta2011 Thanks, yes you can work on this ticket - FYI you don't need to ask first. Please check whether you can use XMLParserConfiguration to trigger the new behavior.

**Comment by madhavgupta2011** [comment]
@stleary I have opened a pull request with my changes and added two unit test cases as well. 
Can you please review it?
[Link to PR](https://github.com/stleary/JSON-java/pull/754)

**Comment by stleary** [comment]
Fix in progress - #754.

**Comment by stleary** [comment]
Re-opening since the PR was not accepted

**Comment by stleary** [comment]
Please use XMLParserConfiguration for the implementation.

**Comment by dubeyaditya29** [comment]
Please ignore the above commits, I am still on it

**Comment by dubeyaditya29** [comment]
https://github.com/dubeyaditya29/JSON-java/commit/fa49d83612c5494a659423a34343c966b57ec303

@stleary  can you verify this.

**Comment by stleary** [comment]
See comments in your repo.

**Comment by rudrajyotib** [comment]
@stleary  - is this issue still open to be picked?

**Comment by rudrajyotib** [comment]
@stleary - if no one else is working on it, can you assign it to my name?

**Comment by stleary** [comment]
@rudrajyotib You can work on this issue. The new behavior should be opt-in, by adding a new property to XMLParserConfiguration.

**Comment by rudrajyotib** [comment]
@stleary sure, I'll start working on it and share the design.

**Comment by rudrajyotib** [comment]
@stleary @johnjaylward  - I am creating a configuration "explicitClosureOfEmptyTag" in XMLParserConfiguration. By default this value will be false, and an explicit end tag will not be created for tag with empty values.
Do you see any issue with the name?

**Comment by stleary** [comment]
Closing due to fixed in #820
