### ISSUE TITLE
Update License information in the wiki

### ISSUE THREAD

**Issue by froque** [stleary/JSON-java#756]
https://github.com/stleary/JSON-java/pull/688 and https://github.com/stleary/JSON-java/issues/686 changed the license but https://github.com/stleary/JSON-java/wiki/The-JSON-Java-license still refers to the old license. 

There is also a non functional link in https://github.com/stleary/JSON-java/wiki/FAQ
 - [Can you change the license to remove the "The Software shall be used for Good, not Evil." line?](https://github.com/stleary/JSON-java/wiki/FAQ#can-you-change-the-license-to-remove-the-the-software-shall-be-used-for-good-not-evil-line)

**Comment by stleary** [comment]
@froque Thanks for catching this! Will fix it tonight.

**Comment by stleary** [comment]
Fixed by updating the wiki and license page
