### ISSUE TITLE
xml to json, when xml has many elements, json will be only to jsonobject, I think it will be a jsonArray

### ISSUE THREAD

**Issue by yujingweivip** [stleary/JSON-java#757]
there is xml 
`<PAFlightsAvailResponse><Solns id='432PC202234'><Soln><Seg><Orig>HKG</Orig><Dest>YVR</Dest><Dept>2023/09/06 18:00:00</Dept><Arr>2023/09/06 15:00:00</Arr><FNum>AC 8</FNum><Carr>Air Canada</Carr><AirC>789</AirC><SCnt>0</SCnt></Seg><Seg><Orig>YVR</Orig><Dest>YYC</Dest><Dept>2023/09/06 16:40:00</Dept><Arr>2023/09/06 19:07:00</Arr><FNum>AC 222</FNum><Carr>Air Canada</Carr><AirC>7M8</AirC><SCnt>0</SCnt></Seg><Elig>1</Elig><Seats>9</Seats></Soln><Soln><Seg><Orig>HKG</Orig><Dest>YVR</Dest><Dept>2023/09/06 18:00:00</Dept><Arr>2023/09/06 15:00:00</Arr><FNum>AC 8</FNum><Carr>Air Canada</Carr><AirC>789</AirC><SCnt>0</SCnt></Seg><Seg><Orig>YVR</Orig><Dest>YYC</Dest><Dept>2023/09/06 18:35:00</Dept><Arr>2023/09/06 21:02:00</Arr><FNum>AC 224</FNum><Carr>Air Canada</Carr><AirC>7M8</AirC><SCnt>0</SCnt></Seg><Elig>1</Elig><Seats>9</Seats></Soln></Solns><RC>0</RC></PAFlightsAvailResponse>`
and there is convert json 
`{
    "PAFlightsAvailResponse": {
        "Solns": {
            "Soln": [
                {
                    "Seg": [
                        {
                            "Arr": "2023/09/06 15:00:00",
                            "SCnt": 0,
                            "FNum": "AC 8",
                            "Carr": "Air Canada",
                            "Dest": "YVR",
                            "Orig": "HKG",
                            "Dept": "2023/09/06 18:00:00",
                            "AirC": 789
                        },
                        {
                            "Arr": "2023/09/06 19:07:00",
                            "SCnt": 0,
                            "FNum": "AC 222",
                            "Carr": "Air Canada",
                            "Dest": "YYC",
                            "Orig": "YVR",
                            "Dept": "2023/09/06 16:40:00",
                            "AirC": "7M8"
                        }
                    ],
                    "Elig": 1,
                    "Seats": 9
                },
                {
                    "Seg": [
                        {
                            "Arr": "2023/09/06 15:00:00",
                            "SCnt": 0,
                            "FNum": "AC 8",
                            "Carr": "Air Canada",
                            "Dest": "YVR",
                            "Orig": "HKG",
                            "Dept": "2023/09/06 18:00:00",
                            "AirC": 789
                        },
                        {
                            "Arr": "2023/09/06 21:02:00",
                            "SCnt": 0,
                            "FNum": "AC 224",
                            "Carr": "Air Canada",
                            "Dest": "YYC",
                            "Orig": "YVR",
                            "Dept": "2023/09/06 18:35:00",
                            "AirC": "7M8"
                        }
                    ],
                    "Elig": 1,
                    "Seats": 9
                }
            ],
            "id": "432PC202234"
        },
        "RC": 0
    }
}`

now there only have one element 
`<PAFlightsAvailResponse><Solns id='432PC202234'><Soln><Seg><Orig>HKG</Orig><Dest>YVR</Dest><Dept>2023/09/06 18:00:00</Dept><Arr>2023/09/06 15:00:00</Arr><FNum>AC 8</FNum><Carr>Air Canada</Carr><AirC>789</AirC><SCnt>0</SCnt></Seg><Seg><Orig>YVR</Orig><Dest>YCG</Dest><Dept>2023/09/07 09:00:00</Dept><Arr>2023/09/07 10:08:00</Arr><FNum>AC 8466</FNum><Carr>AIR CANADA EXPRESS JAZZ</Carr><AirC>DH4</AirC><SCnt>0</SCnt></Seg><Elig>1</Elig><Seats>9</Seats></Soln></Solns><RC>0</RC></PAFlightsAvailResponse>`
and there is convert json 
`{
    "PAFlightsAvailResponse": {
        "Solns": {
            "Soln": {
                "Seg": [
                    {
                        "Arr": "2023/09/06 15:00:00",
                        "SCnt": 0,
                        "FNum": "AC 8",
                        "Carr": "Air Canada",
                        "Dest": "YVR",
                        "Orig": "HKG",
                        "Dept": "2023/09/06 18:00:00",
                        "AirC": 789
                    },
                    {
                        "Arr": "2023/09/07 10:08:00",
                        "SCnt": 0,
                        "FNum": "AC 8466",
                        "Carr": "AIR CANADA EXPRESS - JAZZ",
                        "Dest": "YCG",
                        "Orig": "YVR",
                        "Dept": "2023/09/07 09:00:00",
                        "AirC": "DH4"
                    }
                ],
                "Elig": 1,
                "Seats": 9
            },
            "id": "432PC202234"
        },
        "RC": 0
    }
}`
I think there need "[]"
![image](https://github.com/stleary/JSON-java/assets/23494013/1c64a2ab-b9de-4ba8-a783-fdf79535c1f4)

this code could sovle this problem
### ` //将xml转为json
                    org.json.JSONObject xmlJSONObj = XML.toJSONObject(content);
                    org.json.JSONObject jsonObject = xmlJSONObj.getJSONObject("PAFlightsAvailResponse").getJSONObject("Solns");

                    if (jsonObject instanceof org.json.JSONObject) {
                        // if exist but is a JSONObject, I force it to JSONArray
                        org.json.JSONObject myJSONObj = (org.json.JSONObject) jsonObject;
                        JSONArray jsonArray = new JSONArray();
                        jsonArray.put(myJSONObj);
                        xmlJSONObj.put("Soln", jsonArray);
                    } `

**Comment by yujingweivip** [comment]
> 

how to use XMLParserConfiguration  and forceList property ,now I am using this 
![image](https://github.com/stleary/JSON-java/assets/23494013/563b8d74-3196-4116-9bee-77b11c2dc7de)

**Comment by stleary** [comment]
@yujingweivip try something like this:
```
        Set<String> set = new HashSet<>(Collections.singleton("Soln"));
        JSONObject jsonObject = XML.toJSONObject(xmlStr, new XMLParserConfiguration().withForceList(set));
```

```
{"PAFlightsAvailResponse": {
  "Solns": {
    "Soln": [{
      "Seg": [
        {
          "Arr": "2023/09/06 15:00:00",
          "SCnt": 0,
          "FNum": "AC 8",
          "Carr": "Air Canada",
          "Dest": "YVR",
          "Orig": "HKG",
          "Dept": "2023/09/06 18:00:00",
          "AirC": 789
        },
        {
          "Arr": "2023/09/07 10:08:00",
          "SCnt": 0,
          "FNum": "AC 8466",
          "Carr": "AIR CANADA EXPRESS JAZZ",
          "Dest": "YCG",
          "Orig": "YVR",
          "Dept": "2023/09/07 09:00:00",
          "AirC": "DH4"
        }
      ],
      "Elig": 1,
      "Seats": 9
    }],
    "id": "432PC202234"
  },
  "RC": 0
}}

```

**Comment by stleary** [comment]
@yujingweivip I think this issue is addressed with XmlParserConfiguration.forceList. 
If anyone disagrees or needs additional explanation, please post here.
