### ISSUE TITLE
JLink support

### ISSUE THREAD

**Issue by bowbahdoe** [stleary/JSON-java#760]
This is effectively a duplicate of #513 

Because this does not have a `module-info.java` in the packaged release, it cannot be used with `jlink` without manual configuration

```
$ jlink --module-path json-20230618.jar --add-modules ALL-MODULE-PATH --output out
Error: automatic module cannot be used with jlink: org.json from file:///Users/emccue/Downloads/json-20230618.jar
```

This, in turn, means every downstream library cannot be used with `jlink` without manual configuration. So if I am using redis and want to use [Jedis](https://github.com/redis/jedis) I need to manually figure out what modules that requires.

I can't ask Jedis to fix that until their dependencies fix it, ... its a PITA.

The commands to make this work are relatively straight forward, so it *should* just be a matter of configuring maven and gradle + updating the wiki. (I know how to do it for maven, not gradle). It will mean that people who want to build from source would need java 9, but consumers won't.

Given [this is one of the most popular libraries](https://github.com/sormuras/modules/blob/main/doc/Top1000-2022.txt.md) and is often deep in a dependency tree, its a one of many needed steps if the ecosystem writ. large is ever going to adopt modules more widely.

```java
module org.json {
    exports org.json;
}
```

**Comment by stleary** [comment]
Can you submit a pull request to implement the change, and include in the PR description exactly how this will impact users who are not on Java 9 yet?

**Comment by bowbahdoe** [comment]
Sure #761

**Comment by stleary** [comment]
Closing due to code was merged.
