### ISSUE TITLE
Suspicious conversion from xml to json

### ISSUE THREAD

**Issue by heitorbarbieri** [stleary/JSON-java#762]
### Environment
JSON In Java - version 20230618
mongodb-driver-sync - version 4.10.2
java  - version openjdk version "11.0.18" 2023-01-17
scala - version 2.13.11

### Given a small program:

```
import org.bson.Document
import org.json.{JSONObject, XML}

object Xml2Document extends App {
  val xml: String = "<GrantID>815721008160186381772405</GrantID>"
  val json: JSONObject = XML.toJSONObject(xml)
  val jsonStr: String = json.toString(2)

  println(jsonStr)

  val doc: Document = Document.parse(jsonStr)
  println(doc)
}
```

### It's output is:
{"GrantID": 815721008160186381772405}
Exception in thread "main" java.lang.NumberFormatException: For input string: "815721008160186381772405"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Long.parseLong(Long.java:692)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at org.bson.json.JsonScanner.scanNumber(JsonScanner.java:448)
	at org.bson.json.JsonScanner.nextToken(JsonScanner.java:97)
	at org.bson.json.JsonReader.popToken(JsonReader.java:503)
	at org.bson.json.JsonReader.readBsonType(JsonReader.java:154)
	at org.bson.codecs.DocumentCodec.decode(DocumentCodec.java:174)
	at org.bson.codecs.DocumentCodec.decode(DocumentCodec.java:44)
	at org.bson.Document.parse(Document.java:129)
	at org.bson.Document.parse(Document.java:114)
       ...

The problem is that given a valid xml, the XML.toJSONObject function considers the content inside 'GrantID' as a number and the Document.parse function cannot convert it to Long.
I don't know if it's a bug of the XML.toJSONObject function, but it could be smart enough to check if the content is a valid number and if not, consider it as a String.

**Comment by heitorbarbieri** [comment]
Sorry if I don't agree with you because the org.bjson library will work if the json is
{"GrantID": "815721008160186381772405"}. Without quotes, you are indicating that this is a number (which was generated by the org.json library).

**Comment by heitorbarbieri** [comment]
Please see the "The JavaScript Object Notation (JSON) Data Interchange Format" document (https://datatracker.ietf.org/doc/html/rfc7159#page-6)

"This specification allows implementations to set limits on the range
   and precision of numbers accepted.  Since software that implements
   IEEE 754-2008 binary64 (double precision) numbers [[IEEE754](https://datatracker.ietf.org/doc/html/rfc7159#ref-IEEE754)] is
   generally available and widely used, good interoperability can be
   achieved by implementations that expect no more precision or range
   than these provide, in the sense that implementations will
   approximate JSON numbers within the expected precision.  A JSON
   number such as 1E400 or 3.141592653589793238462643383279 may indicate
   potential interoperability problems, since it suggests that the
   software that created it expects receiving software to have greater
   capabilities for numeric magnitude and precision than is widely
   available.

   Note that when such software is used, numbers that are integers and
   are in the range [-(2**53)+1, (2**53)-1] are interoperable in the
   sense that implementations will agree exactly on their numeric
   values."

**Comment by johnjaylward** [comment]
your stack trace does not have `org.json` anywhere in it. only `org.bjson`. So at this point, without a reproducible test case showing this issue with the current version of this library, it looks like your issue does not belong here, but instead belong with org.bjson.

**Comment by heitorbarbieri** [comment]
You're right, the org.json library in my program is never throwing an exception, so it won't appear in the execution stack of the exception shown.
As my last argument, I would suggest thinking from a new point of view where given an xml containing a number so large that it cannot be converted to the long type, the library generates a json that does not follow the portability suggestion described in the official document cited above.
It's not a bug, I got it. I just leave my suggestion for improving the library since it is a reference implementation for the json specification.

Thank you for your attention.

**Comment by heitorbarbieri** [comment]
Thanks, it works!
