### ISSUE TITLE
use new JSONObject cannot convert negative float/double value correclty

### ISSUE THREAD

**Issue by quanchentg** [stleary/JSON-java#763]
I have a json string 
  String s = "{a : 1 , b : - 1.5 , beta : 0.5 }";
then I use
JSONObject data= new JSONObject(s);

data is "{"a":1, "b":"- 1.5","beta":0.5}".
however, it should return {"a":1, "b":-1.5,"beta":0.5}

but if i use 
 String s = "{a : 1 , b : -1.5 , beta : 0.5 }";
it returns correct result as {"a":1, "b":-1.5,"beta":0.5}

is the space between "-" and number not allowed?

**Comment by johnjaylward** [comment]
Correct, no spaces

**Comment by quanchentg** [comment]
thanks for confirmation.

**Comment by stleary** [comment]
Closing due to question answered.
