### ISSUE TITLE
I would like to add JSON to HTML parser

### ISSUE THREAD

**Issue by pallavi704** [stleary/JSON-java#780]

**Comment by stleary** [comment]
Feel free to attempt this if you want, but I think it may be difficult or impossible. It will need a \*\*lot\*\* of unit test coverage.

**Comment by pallavi704** [comment]
Can we split the entire process as 2 PRs then? 
PR1 would be parser generation. 
PR2 would be adding needed test cases?

**Comment by stleary** [comment]
@pallavi704 Sorry, I don't think that works.

**Comment by rudrajyotib** [comment]
@pallavi704 - can you please chalk out the key abilities/api actions of the parser. I think it would be wise to focus on What before How.

**Comment by stleary** [comment]
This should get you started:

**Key Abilities**
- HTML-to-JSON Mapping: Map HTML elements, attributes, and text to JSON objects, arrays, and values.
- JSON-to-HTML Mapping: Reverse map JSON objects to generate a valid HTML document.
- Preserve HTML Semantics: Maintain the semantic structure of the HTML document in the JSON representation.
- Idempotency: Ensure that converting from HTML to JSON and back to HTML results in an equivalent document.
- Error Handling: Detect malformed HTML and terminate parsing.
- Attribute Handling: Correctly map HTML tag attributes to appropriate JSON fields.
- Metadata Capture: Optionally capture metadata like DOCTYPE, comments, or scripts.
- Compatibility: Ensure that the parser is compatible with Java 8 and integrates smoothly with the existing JSON-Java library.

**Key Actions**
- HTML Parsing: Tokenize the HTML into elements like tags, attributes, and text.
- HTML-to-JSON Transformation: Convert the intermediate representation to a JSON object.
- When converting from HTML to JSON, map attributes to JSON fields. When converting from JSON to HTML, do the reverse mapping.
- Error Handling: Validate the HTML and throw a JSONException for badly invalid HTML.
- Serialize the HTML: Serialize to a string and deserialize from a string.
- Integration and API Design: Add methods for HTML-to-JSON and JSON-to-HTML conversion in the JSON-Java library.
- Testing: Write unit tests to confirm that HTML-to-JSON and JSON-to-HTML conversions work as expected.

**Comment by johnjaylward** [comment]
This solution in Javascript seems like it may be a good starting point 

https://stackoverflow.com/a/44293677

**Comment by rudrajyotib** [comment]
@pallavi704  @stleary  @johnjaylward  - Can I get some more context on the use case of this feature. Everyday HTMLs are becoming more complex than ever. Which means, before we start implementing this library feature, we need to know what sort of complexity are we going to support. E.g., All the embedded scripts, event listeners, aria tags, svg and image references etc would make the parser an overwhelming affair. 
Shall we say that we start with HTML without any script/scriptlet embedded in it.
And the produced JSON will have an uniform structure 

{
tag:"HTMLTagName",
attributes:[
{name:"AttributeName",value:"AttributeValue"
],
content:"Tag  Content"
children:[{tag.....},{tag....}
]

Is this what we are aiming for ?

**Comment by johnjaylward** [comment]
@rudrajyotib , neither stleary or I have a real use case for this. we were simply trying to point out places to start if the requester (@pallavi704) needed help with organizing and implementing their request.

**Comment by rudrajyotib** [comment]
@pallavi704  - do you still have some use case for this issue? 
If there is no use case presented, @stleary  @johnjaylward  - this issue can be closed, what do you think ?

**Comment by stleary** [comment]
@rudrajyotib I think it's OK to leave this open for a little longer.

**Comment by pallavi704** [comment]
Hey @stleary and @johnjaylward, thanks for helping in where to start. Actually I wanted to pickup a complex task and to work on it to improve my open source skills. But I was stuck in the middle. 

@rudrajyotib , I was thinking about the following use case: 
Most of the websites have user login/signup page where the credentials of the users are entered and then they are stored in the database. 

So, while a user signup to the portal then their data can be parsed to a JSON data and there by storing in the database would be a easier and time optimized task. (HTML to JSON use case of a signup page)

when an existing user is logging into the portal then, the credentials are checked to open the respective user profile in the html. (JSON to HTML use case of a login page). 

Please do let me know if this idea would fit in your project so that I can give it a try,

**Comment by johnjaylward** [comment]
I don't think that is a useful use-case. That is not how anyone would process form input. In general, these days this would be handled using Javascript and an "XMLHttpRequest". These are a great many frameworks out there that already wrap this type of process up nicely in a bow.

- Very easy sample of a JavaScript based HTTP Request: https://www.w3schools.com/js/js_json_http.asp
- [Sencha ExtJs](https://www.sencha.com/products/extjs/) is one framework I've used over the years
- Alternatives to Sencha: https://www.slant.co/options/35/alternatives/~extjs-alternatives

At a high-level, the standard flow for what you are presenting would be:

# Flow 1 - no Javascript

1. Have a form with some user information input.
2. For is submitted using standard HTTP POST form method
3. Server-side action translates the form post data to the database.

In this case JSON is not involved at all unless someone wants to jump through extra hoops on the server side to use it explicitly when it's not needed. An exception may be that the database is JSON based, like Elastic or some other "no-sql" backend. However, there is still no conversion from "HTML to JSON". The data format that the server receives is not HTML.

# Flow 2 - Using Javascript to send to a REST/JSON endpoint

1. Have a form with some user information input.
2. For is submitted using a Javascript XMLHttpRequest
3. Server expects the data in JSON format before translating that data to the database

In this case, step 2 would need to pre-translate the form data into a valid JSON object that the server expects. But again, you would not be doing a conversion from "HTML to JSON". You would instead probably just pick the form values you want and convert the form to a valid JSON object.

sample JavaScript that likely won't work at all:

```javascript
var form = document.forms[0];
var postObj = {
 userName:  form.username,
 password: form.password,
 email: form.email
};
// use XMLHttpRequest to send the "postObj" to the server.

**Comment by stleary** [comment]
This issue can be re-opened if progress is made at some point in the future. It seems to me that there is a low probability of this succeeding due to the difficulty of parsing HTML in a JSON parser.
