### ISSUE TITLE
XMLTest.testIndentComplicatedJsonObjectWithArrayAndWithConfig fails on Windows

### ISSUE THREAD

**Issue by mureinik** [stleary/JSON-java#781]
When running the test suite on Windows, XMLTest.testIndentComplicatedJsonObjectWithArrayAndWithConfig fails due to differences in the newline character being used in the expected and actual XMLs being compared - differences that are no functionally interesting.

The test properly canonized the newline character in the actual string produced by calling `XML.toString`, but fails to do so for the expected string that was read from a file. Since this file was not produced on a Windows machine, it won't contain the linebreaks expected when the test is run on Windows.

**Comment by stleary** [comment]
@mureinik Isn't this fixed in #782?

**Comment by mureinik** [comment]
@stleary yes, it is.

**Comment by stleary** [comment]
Fixed in #782
