### ISSUE TITLE
Compiler warnings to be fixed

### ISSUE THREAD

**Issue by stleary** [stleary/JSON-java#800]
src/main/java/org/json/ParserConfiguration.java:77: warning: no @param for <T>
     public <T extends ParserConfiguration> T withKeepStrings(final boolean newVal) {
src/main/java/org/json/ParserConfiguration.java:101: warning: no @param for <T>
     public <T extends ParserConfiguration> T withMaxNestingDepth(int maxNestingDepth) {

**Comment by farukhfrk** [comment]
I would like to work on this, could you please assign it to me?

**Comment by stleary** [comment]
@farukhfrk Issues are not assigned, contributers are free to work on any issue.

**Comment by theKnightsOfRohan** [comment]
@farukhfrk Sorry for taking this issue from you, please look through my PR and provide any suggestions

**Comment by stleary** [comment]
Closing due to fixed in #808
