### ISSUE TITLE
Suggestion: Code Coverage Badge

### ISSUE THREAD

**Issue by Simulant87** [stleary/JSON-java#865]
This project has a very good unit test coverage, something to show and be proud of.

Would you like to add a code coverage badge on the Readme?
There are some examples on how to do it with github actions:

https://github.com/marketplace/actions/badge-action
https://stackoverflow.com/a/63765701/1515052

**Comment by stleary** [comment]
@Simulant87 Actually there are a lot of gaps in the unit tests, which is probably unavoidable for a non-trivial application. I would prefer not to claim code-coverage glory for the project at this time.
