### ISSUE TITLE
Minor: "latest release" points not to the newest release

### ISSUE THREAD

**Issue by Simulant87** [stleary/JSON-java#866]
the release [20231013](https://github.com/stleary/JSON-java/releases/tag/20231013) is still marked as the "latest release", although version [20240205](https://github.com/stleary/JSON-java/releases/tag/20240205) is already released and should be the latest.

It's a little bit confusing when looking on the releases outline on the right on the main page, having the "latest" release on github not in sync with the latest release on maven central.

**Comment by stleary** [comment]
@Simulant87 Thanks for posting, this is a known problem. A workflow was added to deploy to maven from github, but I am still engaged with a manual process. Will be fixed at a future time.

**Comment by stleary** [comment]
Closing due to problem has been resolved in #874
