### ISSUE TITLE
Update Wiki: Where are the unit tests

### ISSUE THREAD

**Issue by Simulant87** [stleary/JSON-java#878]
I think the wiki section [where are the unit tests](https://github.com/stleary/JSON-java/wiki/FAQ#where-are-the-unit-tests) is outdated as it still refers to the project [JSON-Java-unit-test](https://github.com/stleary/JSON-Java-unit-test), where the readme says that the tests are ported to this project.

I would suggest to keep the FAQ section and update the link to the tests directory within this project.
I addition the [JSON-Java-unit-test](https://github.com/stleary/JSON-Java-unit-test) could be marked as "archived" in the project settings, clearly indicating that the project is readonly and no longer actively maintained as stated in the readme.

From my understanding PRs to the wiki are not possible.

**Comment by stleary** [comment]
Closed due to Wiki is updated.
