### ISSUE TITLE
Complete strictMode for JSONArray

### ISSUE THREAD

**Issue by stleary** [stleary/JSON-java#887]
Garbage chars at the end of JSONArray docs are still allowed in strict mode. This needs to be fixed.

Here is a list of examples of JSON text strings that should be allowed in default mode, but not in strict mode. This is not an exhaustive list. Unit tests should confirm expected behavior when strictMode is true and false.
```
"[]asdf",
"[]]",
"[]}",
"[][",
"[]{",
"[],",
"[]:",
"[],[",
"[],{"
```

**Note:** It should not be necessary for the code to check for specific trailing chars; strict mode is violated if parsing is completed and there are still chars left in the JSONTokener instance.

**Comment by rikkarth** [comment]
Hi stleary would you please be able to provide one or two examples?

**Comment by stleary** [comment]
Description updated

**Comment by rikkarth** [comment]
![image](https://github.com/stleary/JSON-java/assets/76500344/07be6c4d-e11c-415d-8c12-e1e89f4364ad)

**Comment by stleary** [comment]
Closing due to feature accepted and merged.
