### ISSUE TITLE
All unit tests must pass in strict mode

### ISSUE THREAD

**Issue by stleary** [stleary/JSON-java#891]
The unit tests should yield the same result for default and strict mode parsing. 
Tests may fail for the following reasons:
* The test data inadvertently does not include double quotes around some string values. These should be fixed.
* The test is specifically intended to test the parsing of unquoted chars. These should be omitted from the strict mode test run. 
* The test has specific conditions (e.g. working with unquoted strings for CDL or XML testing) that are impacted by the strict mode parser changes.

The unit tests will be updated as a separate issue from #887 and #888. After merging the unit test fixes, the review of strict mode may continue.

**Comment by stleary** [comment]
@rikkarth No worries, I will go ahead and accept this PR and merge it in 3 days. Will also hold off on merging #894 so that you don't have yet another commit to merge to. 
However, your code still has this line in JSONParserConfiguration:
`this.strictMode = true;`
This must be deleted or at least commented out. You can do it yourself if you have time, or I can edit the file in place.
I also think that `smallCharMemory` and `arrayLevel` can still be optimized away, but that is a task for another day.
Thanks for all of the work you put into #888!

**Comment by rikkarth** [comment]
I will clean it up for you. Thank you @stleary

**Comment by rikkarth** [comment]
Merged.

**Comment by stleary** [comment]
Closing due to revert of strict mode feature. Will address strict mode again after the next release.
