### ISSUE TITLE
Update JsonPath version

### ISSUE THREAD

**Issue by anabright** [stleary/JSON-java#893]
Test dependency JsonPath 2.4.0 [seems to have](https://mvnrepository.com/artifact/com.jayway.jsonpath/json-path/2.4.0) 1 direct vulnerability and 58 transitive vulnerabilities.
Can it be updated to 2.9.0 (which has no vulnerabilities as of today) for the next release?
Thank you!

**Comment by stleary** [comment]
@anabright Thanks, will look into an update.
