### ISSUE TITLE
Enhancement: Improve performance when parsing from String

### ISSUE THREAD

**Issue by Simulant87** [stleary/JSON-java#899]
When parsing a JSONObject or JSONArray from a String input, a lot of the time is spent in the `StringReader.read()` method on synchronizing on a lock object. But [the reader is never shared](https://github.com/stleary/JSON-java/blob/14f71274f79ac50afb316845539f4195facc33ee/src/main/java/org/json/JSONTokener.java#L75) so the synchronization is not neccessary and a waste of time.

Enhancement: Re-implement a NonSynchronizedStringReader without synchronization on the lock for faster access to the input and use it instead of the StringReader.

**Comment by stleary** [comment]
@Simulant87 Thanks, but we cannot modify licensed files and then re-publish them as public domain.

**Comment by Simulant87** [comment]
I understand. I might haven been too much inspired by other sources in my first attempt.
Is there a chance that it will be accepted, when I completely write it offline from scratch?

**Comment by stleary** [comment]
@Simulant87 You would need a firewall (AKA Chinese Wall). One developer reviews the licensed code, then gives design requirements to a second developer who does the implementation. The second developer does not have access to the licensed code. However, in this particular instance, I think the risk of introducing problems with the new StringReader outweighs the marginal improvement in performance.

**Comment by Simulant87** [comment]
For everyone interested: The same performance improvement can also be achieved by passing the improved `Reader` without synchronisation to an explicit` JSONTokener` in the constructor of the `JSONObject`. And there is also an open implementation with the same benefits available by [apache commons io](https://mvnrepository.com/artifact/commons-io/commons-io).

`new JSONObject(new JSONTokener(new org.apache.commons.io.input.CharSequenceReader(content)));`
