### ISSUE TITLE
Inquiry about License Changes for the JSON Library

### ISSUE THREAD

**Issue by gumingyu6689** [stleary/JSON-java#902]
Dear Author of the JSON Library,

I am writing to you to inquire about the licensing of the JSON library. I have observed that the license for the library prior to the version dated 20220320 was listed as "JSON License." Forexample ：https://repo1.maven.org/maven2/org/json/json/20170516/json-20170516.pom
However, following that version, it appears the license has been changed to "Public Domain," for example：https://repo1.maven.org/maven2/org/json/json/20240205/json-20240205.pom
with no additional license text provided.

I have two concerns regarding this change I hope you can clarify:

1. What prompted the decision to transition from the JSON License to the public domain for the JSON library?

2. We know that "public domain" is not a license and sometimes leads to legal ambiguity. So here we need to double check whether we are allowed to freely use, distribute and modify the source code？

I appreciate your time and any information you can provide on this matter

**Comment by gumingyu6689** [comment]
Hi @stleary ，
I have read the comments of OSS related [issue-904](https://github.com/stleary/JSON-java/issues/904). 
If my understanding is correct , in later version plans to update the license to MIT, which is a very friendly，permissive  license.
 But our current software dependency is: 20240205. So it is necessary to double-check whether public in this version of the license now means: **we are allowed to freely use, distribute and modify the source code?**
 thanks and waiting for your back！

**Comment by stleary** [comment]
Hi @gumingyu6689 Yes, you are allowed to freely use, distribute, and modify the JSON-Java source code.

My understanding of Public Domain with regards to this project is:
1. No copyright: The creator has relinquished all copyrights to the work.
2. Free to use: Anyone can use, modify, distribute, or sell the software without permission or attribution.
3. No restrictions: There are no licenses or conditions attached to the use of the software.
4. Irreversible: Once this software has entered the public domain, it cannot be taken back under copyright protection.
5. No warranty: This software comes with no warranty or support from the original creator.

**Comment by My1** [comment]
sorry for necro but might it not be a better idea to use an "explicit" public domain-style license like CC0, as you might not be able to just say "public domain" everywhere, while CC0 basically does both, firstly waiving any copyright you do have and secondly, if option 1 is not possible, explicitly gives an irrevocable license to do everything that is possible within the confines of users' jurisdictions.

**Comment by jebeaudet** [comment]
I'm also running into problems with this license within my organization which leverage GitHub dependency-review. This [dependency is listed](https://github.com/clearlydefined/curated-data/pull/26813) as having the `NONE` license because the public domain is not a valid license. Using `CC0` would be more aligned with SPDX.

**Comment by stleary** [comment]
Requests to change the license can be directed to the original author.
