### ISSUE TITLE
Update license from https://opensource.org/license

### ISSUE THREAD

**Issue by ssibrahimpur** [stleary/JSON-java#904]
Can you please update the appropriate license - https://opensource.org/license/mit

Though it is mentioned as public domain, there is no license defined in here for it https://opensource.org/license?ls=MIT

I would really appreciate making this change quickly!

**Comment by stleary** [comment]
The license was chosen by the project author.
#902 tracks a request to change the license. Please add any comments to that issue.
Closing due to duplicate request.
