### ISSUE TITLE
JSON-PATH 2.4.0 has vulnerabilities, any eta for a new release with 2.9.0?

### ISSUE THREAD

**Issue by gabesalvador** [stleary/JSON-java#909]
Today i got a fail security check in Fortify due to the vulnerabilities in JSON-PATH 2.4.0, any ETA on when the new release is coming with JSON-PATH bumped to 2.9.0?

**Comment by stleary** [comment]
@gabesalvador I will take care of this before the end of the week (Sunday, not Friday)

**Comment by stleary** [comment]
Closing due to issue fixed in #894. The next release will hopefully be completed this month.
