### ISSUE TITLE
clarify minimum required Java Version 6 or 8

### ISSUE THREAD

**Issue by Simulant87** [stleary/JSON-java#915]
It is a little bit unclear to me, which should be the minimum required Java version for this project. I would like to get clarity on it.

https://github.com/stleary/JSON-java/pull/815 brings back the Java 1.6 build pipeline check after it was removed by https://github.com/stleary/JSON-java/pull/741

[In the readme is says:](https://github.com/stleary/JSON-java?tab=readme-ov-file#overview)
> Designed and tested to use on Java versions 1.6 - 21

[In the FAQ is says:](https://github.com/stleary/JSON-java/wiki/FAQ#what-version-of-java-does-this-project-require)
> At the present time Java 8 is required, in order to support pre-existing Java users that are still on 8. It was decided that Android users are probably no longer tied to Java 6. The last release to support Java 6 is 20230618.

In the [maven](https://github.com/stleary/JSON-java/blob/2ee5bf13f403a9e95203f794be30732e20929429/pom.xml#L105) and [gradle](https://github.com/stleary/JSON-java/blob/2ee5bf13f403a9e95203f794be30732e20929429/build.gradle#L35) build files it specifies Java 1.8

I recommend that all stated references should define the same minimum version.

If Java 8 should be the minimum, I submitted these 2 PRs:
https://github.com/stleary/JSON-java/pull/914
https://github.com/stleary/JSON-java/pull/913

If Java 1.6 should still be the minimum, please close the PRs, update the FAQ and the build definition.

**Comment by stleary** [comment]
@Simulant87 The Wiki page was not correct. Although the code requires Java 8 for unit testing, and the build automation uses Java 8, the source code remains compatible with Java 6. For example, a developer who needs Java6 for an embedded system or an old Android phone can still compile and execute the library. There are no plans to remove support at this time.

I have corrected the text in [What version of Java does this project require?](https://github.com/stleary/JSON-java/wiki/FAQ#what-version-of-java-does-this-project-require). Thanks for letting me know.

**Comment by Simulant87** [comment]
Thank you for the quick response and update in the FAQ. I closed my PRs.
